In [1]:
import pandas as pd

In [ ]:
# csv 폴더 안에 있는 corona.csv 파일 로드
# 현재 작업중인 폴더(./)(생략이 가능) -> 상위 폴더로 이동 (../) -> csv 하위 폴더로 이동 (csv/) -> corona.csv
# 상대 경로는 내 파일의 위치에서부터 시작
corona=pd.read_csv("../csv/corona.csv")

In [4]:
corona.head()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,3,2022-06-05 08:53:19.426,24258,18163648,901,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,4,2022-06-04 08:56:49.219,24238,18153814,900,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [5]:
corona.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [8]:
# 데이터프레임에서 컬럼들의 목록 확인
# DataFrame라는 Class에는 3개 변수 -> values, index, columns
corona.columns

Index(['Unnamed: 0', 'createDt', 'deathCnt', 'decideCnt', 'seq', 'stateDt',
       'stateTime', 'updateDt', 'accExamCnt', 'accDefRate'],
      dtype='str')

In [ ]:
# Unnamed: 0 컬럼은 인덱스로 사용이 됐었구나 -> 필요가 없다. -> 해당 컬럼의 데이터는 제거
# seq 컬럼의 데이터는 게시글의 번호 -> 제거
# 특정 데이터를 제거(drop())
# dropna() -> 매개변수 축 설정(axis) -> 인덱스를 제거할것인가? 컬럼을 제거할것인가?
#           -> 매개변수 inplace -> 원본의 데이터를 변화 시킬것인가
#           -> 결측치를 제거한다.
# drop() -> axis, inplace 매개변수 존재 
#       -> 첫번째 인자는 어떠한 것을 제거할것인가?
#       -> drop() 함수에서 기본 설정은 인덱스를 제거
corona.drop(
    ['Unnamed: 0','seq'], axis=1, inplace=True
)
# 우리가 제거할 컬럼의 개수가 2개
# drop(inplace=True)의 함수를 실행하면 -> 첫번째 실행에서 정상 처리가 되더라도 -> 같은 블록을 다시 실행하면 에러 발생 (해당 데이터가 제거되고 다시 제거하려니 없다.)

KeyError: "['Unnamed: 0', 'seq'] not found in axis"

In [13]:
corona.head(1)

,createDt,deathCnt,decideCnt,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [16]:
# 컬럼의 이름을 변경
# case1. rename() 함수를 이용하여 컬럼의 이름을 변경
# 특정 컬럼의 이름을 변경할때 사용
corona.rename(
    columns={
        'createDt':'등록일시',
        'deathCnt':'총사망자',
        'decideCnt':'총확진자',
        'stateDt':'기준일',
        'stateTime':'기준시간',
        'updateDt':'수정일시',
        'accExamCnt':'누적의심자',
        'accDefRate':'누적확진율'
        
    }
)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [19]:
# case2 : Class 내부의 columns 변수에 접근해서 다른 데이터를 대입 (데이터를 변경하기 전에 확인은 불가능) -> 이 방법은 모든 컬럼의 이름을 변경할때 주로 사용
# 주의사항 : 컬럼의 개수가 같은 자료형 데이터를 대입 (길이가 다르면 에러 발생)
corona.columns = ['등록일시','총사망자','총확진자','기준일','기준시간','수정일시','누적의심자','누적확진율']

In [22]:
corona.head(10)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
5,2022-06-03 09:08:18.729,24229,18141775,20220603,00:00,2022-06-08 09:11:38.938,NaN,NaN
6,2022-06-02 08:58:19.746,24212,18129236,20220602,00:00,2022-06-08 09:11:51.985,NaN,NaN
7,2022-06-01 09:07:30.461,24197,18119345,20220601,00:00,2022-06-08 09:12:05.316,NaN,NaN
8,2022-05-31 08:55:39.977,24176,18103577,20220531,00:00,2022-06-04 08:59:23.637,NaN,NaN
9,2022-05-30 09:01:30.847,24167,18086392,20220530,00:00,2022-06-04 08:59:37.203,NaN,NaN

In [24]:
# 데이터를 확인하는 방법 : info(), isna().sum(), describe()
corona.info()

# 인덱스는 일반적으로 범위형태로 구성
# range(0,100)
# 시간 데이터(시계열 데이터)
# 일반적으로 인덱스(기준값)는 고유값 (primary key)
# 고유값을 사용하는 이유는? -> 전체의 데이터에서 특정 데이터를 찾기 편하기 위함
# 개인 정보의 데이터 -> 이름, 생년월일, 주소 (3개의 데이터는 고유값을 가질수가 없다.) -> 고유 값 컬럼을 생성 (숫자가 1씩 증가하는 형태(auto increament), 주민등록번호, ID) -> 하나의 행, 열에 접근하기 편하기 위해서

<class 'pandas.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   등록일시    820 non-null    str
 1   총사망자    820 non-null    int64
 2   총확진자    820 non-null    int64
 3   기준일     820 non-null    int64
 4   기준시간    820 non-null    str
 5   수정일시    817 non-null    str
 6   누적의심자   692 non-null    float64
 7   누적확진율   623 non-null    float64
dtypes: float64(2), int64(3), str(3)
memory usage: 51.4 KB

In [26]:
# 결측치의 개수를 확인 -> 결측치가 맞느냐 (isna()) -> 합산 (sum())
# false -> 0, true -> 1, --> 합산을 하면 true의 개수가 나온다. (결측치의 개수)
corona.isna().sum()

등록일시       0
총사망자       0
총확진자       0
기준일        0
기준시간       0
수정일시       3
누적의심자    128
누적확진율    197
dtype: int64

In [27]:
# 통계 정보 확인 -> 일반적으로 수치형 데이터의 통계 정보
corona.describe()

               총사망자          총확진자           기준일         누적의심자       누적확진율
count    820.000000  8.200000e+02  8.200000e+02  6.920000e+02  623.000000
mean    3927.832927  1.913097e+06  2.020897e+07  7.545057e+06    1.556435
std     6164.310693  4.857030e+06  7.118265e+03  6.172020e+06    0.543014
min       54.000000  7.513000e+03  2.020031e+07  2.101440e+05    0.902205
25%      415.750000  2.393525e+04  2.020100e+07  1.934309e+06    1.078089
50%     1812.500000  1.185640e+05  2.021042e+07  6.368310e+06    1.416159
75%     3120.500000  3.979915e+05  2.021112e+07  1.216890e+07    1.816009
max    24305.000000  1.818820e+07  2.022061e+07  2.151807e+07    3.919308

In [ ]:
# 문자형 데이터의 통계 정보? (데이터의 개수, 고유값의 개수, 0번 인덱스의 데이터, 최빈값)
corona[['등록일시','기준시간']].describe()

                           등록일시   기준시간
count                       820    820
unique                      820      1
top     2022-06-08 09:09:05.982  00:00
freq                          1    820

In [47]:
# 데이터 프레임에서 정렬을 변경
# list에서 정렬을 변경하는 함수 -> sort() (기본적으로는 오름차순, reverse=True로 변경하면 내림차순)
# 데이터프레임은 정렬을 변경할 수 있는 방법이 2개 -> index, values(기준이 될 수 있는 값을 여러)
# 데이터프레임은 sort() 함수가 2개 존재 -> sort_index(), sort_values()
# corona 데이터에서 등록일시를 기준으로 정렬을 오름차순 정렬로 변경
# sort_values() : 특정 컬럼의 값들을 기준으로 정렬을 오름차순 / 내림차순
# ascending의 기본값은 true임
corona.sort_values('등록일시',ascending=False, inplace=False)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [48]:
# 인덱스가 역순으로 되어있는게 좀 걸립니다..
# 인덱스는 재지정(초기화)
# 초기화(reset) + 인덱스(index)
# 인덱스는 초기화 -> 기존의 인덱스는 index라는 컬럼을 생성하여 데이터를 유지
# 기존의 인덱스를 제거하려면? -> reset_index().drop('index',axis=1) // -> reset_index() 함수 안에 drop 매개변수 존재 (기본값 false, True로 변경하면 기존은 인덱스는 제거)
corona.reset_index(drop=True, inplace=True)

In [49]:
# 1차 작업이 종료 -> 백업본 하나 생성
origin_data=corona.copy()

In [50]:
# 결측치가 존재하는 컬럼이 3개 (수정일시, 누적의심자, 누적확진율)
# 수정일시가 결측치인 데이터를 확인 (수정일시가 결측치인 이유는? -> 수정이 되지 않았다?)
# 수정일시가 결측치인(인덱스의 조건식) 데이터 출력 (전체 데이터에서 특정 데이터들만 확인)
# 데이터프레임에서 수정일시 데이터만 추출 -> 결측치와 같은가?
flag_null=corona['수정일시'].isna()

In [51]:
corona.loc[flag_null,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
119,2022-02-09 10:37:00.08,6943,1131239,20220209,00:00,NaN,NaN,NaN
179,2021-12-11 06:19:00.000,4210,510578,20211211,00:00,NaN,18024403.0,NaN

In [53]:
# 640 index를 기준으로 상위 2부터 하위 2개까지의 데이터를 출력
# loc[] -> 범위 지정하면 종료값 포함
corona.loc[638:642,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
638,2020-09-08 00:00:00.000,341,21431,20200908,00:00,2021-10-07 10:30:51.51,2066078.0,1.059520
639,2020-09-07 00:00:00.000,336,21295,20200907,00:00,2021-10-07 10:30:51.51,2051297.0,1.062525
640,2020-09-06 00:00:00.000,334,21176,20200906,00:00,2021-10-07 10:30:51.51,2045935.0,1.060755
641,2020-09-05 00:00:00.000,333,21009,20200905,00:00,2021-10-07 10:30:51.51,2037045.0,1.058405
642,2020-09-04 00:00:00.000,331,20841,20200904,00:00,2021-10-07 10:30:51.51,2018906.0,1.059726

In [54]:
# 누적의심자, 누적확진율 
# 결측치가 왜 생겼을까? -> 코로나의 감염자가 재감염이 되는 경우가 발생 (많은 수가 발생) -> 2개의 컬럼의 데이터의 신뢰도가 떨어져서 데이터를 더 이상 입력하지 않았다고 추측함.
flag_null2=corona['누적확진율'].isna()

In [56]:
corona.loc[flag_null2,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
192,2021-11-28 08:58:53.394,3548,440884,20211128,00:00,2021-12-02 09:06:50.152,17158535.0,NaN
193,2021-11-27 09:32:36.026,3492,436959,20211127,00:00,2021-12-02 09:06:37.327,17115754.0,NaN
194,2021-11-26 09:03:03.973,3440,432892,20211126,00:00,2021-12-02 09:06:24.138,17056003.0,NaN
195,2021-11-25 09:00:47.897,3401,428996,20211125,00:00,2021-12-02 09:06:12.94,16998733.0,NaN
196,2021-11-24 09:08:22.071,3362,425059,20211124,00:00,2021-12-02 09:06:01.826,16939923.0,NaN

In [58]:
flag_null3=corona['누적의심자'].isna()

corona.loc[flag_null3,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
123,2022-02-05 10:25:08.782,6858,970983,20220205,00:00,2022-02-09 13:05:01.221,NaN,NaN
124,2022-02-04 08:58:40.476,6836,934638,20220204,00:00,2022-02-09 13:04:52.382,NaN,NaN
125,2022-02-03 08:46:14.856,6812,907200,20220203,00:00,2022-02-09 13:04:42.741,NaN,NaN
126,2022-02-02 09:04:49.92,6787,884294,20220202,00:00,2022-02-09 13:04:29.013,NaN,NaN
127,2022-02-01 09:06:24.411,6772,864026,20220201,00:00,2022-02-09 13:04:21.424,NaN,NaN

In [61]:
# 2개의 컬럼의 데이터는 특정 날짜 이후로는 데이터를 수집하지 않았다.
# 데이터의 필요성이 없어졌다. -> 컬럼의 데이터를 제거해도 되겠다. -> drop 사용
corona.drop(
    ['누적의심자','누적확진율'],axis=1,inplace=True
)

KeyError: "['누적의심자', '누적확진율'] not found in axis"

In [64]:
# 데이터셋에서 우리가 필요한 데이터가 존재하지 않는다면 -> 데이터를 생성
# 일일확진자 -> 어제의 총확진자와 오늘의 총확진자의 수의 차이
# 파생변수를 생성 -> 컬럼이 하나 추가
# 일일확진자 = 오늘의 총확진자 - 어제의 총확진자 
corona.loc[1,'총확진자']-corona.loc[0,'총확진자']
corona.loc[2,'총확진자']-corona.loc[1,'총확진자']
corona.loc[3,'총확진자']-corona.loc[2,'총확진자']

corona.loc[819, '총확진자'] - corona.loc[818,'총확진자']
# .... 819번 실행 -> 첫날짜는 일일확진자를 계산 불가능

np.int64(-242)

In [65]:
new_list=[]

# 819번 반복을 하는 반복문
for i in range(819):
    # i는 0부터 818까지 대입
    result=corona.loc[i+1,'총확진자']-corona.loc[i,'총확진자']
    # 계산 결과를 new_list에 추가
    new_list.append(result)

new_list

[np.int64(-13358),
 np.int64(-6172),
 np.int64(-5022),
 np.int64(-9834),
 np.int64(-12039),
 np.int64(-12539),
 np.int64(-9891),
 np.int64(-15768),
 np.int64(-17185),
 np.int64(-6135),
 np.int64(-12647),
 np.int64(-14374),
 np.int64(-16572),
 np.int64(-18805),
 np.int64(-23936),
 np.int64(-26331),
 np.int64(-9971),
 np.int64(-19289),
 np.int64(-23450),
 np.int64(-25113),
 np.int64(-28109),
 np.int64(-31333),
 np.int64(-35085),
 np.int64(-13290),
 np.int64(-25425),
 np.int64(-29572),
 np.int64(-32435),
 np.int64(-35882),
 np.int64(-43881),
 np.int64(-49896),
 np.int64(-20588),
 np.int64(-40048),
 np.int64(-39563),
 np.int64(-26678),
 np.int64(-42279),
 np.int64(-49046),
 np.int64(-51106),
 np.int64(-20076),
 np.int64(-37760),
 np.int64(-43244),
 np.int64(-50556),
 np.int64(-57446),
 np.int64(-76764),
 np.int64(-80267),
 np.int64(-34361),
 np.int64(-64704),
 np.int64(-75423),
 np.int64(-81033),
 np.int64(-90843),
 np.int64(-111289),
 np.int64(-118462),
 np.int64(-47730),
 np.int64(-92978),
 np.int64(-107882),
 np.int64(-125800),
 np.int64(-148409),
 np.int64(-195382),
 np.int64(-210715),
 np.int64(-90917),
 np.int64(-164456),
 np.int64(-185525),
 np.int64(-205299),
 np.int64(-224784),
 np.int64(-286247),
 np.int64(-266085),
 np.int64(-127163),
 np.int64(-234265),
 np.int64(-264120),
 np.int64(-280231),
 np.int64(-320683),
 np.int64(-424466),
 np.int64(-347500),
 np.int64(-187182),
 np.int64(-318075),
 np.int64(-335541),
 np.int64(-339451),
 np.int64(-395526),
 np.int64(-490771),
 np.int64(-353828),
 np.int64(-209139),
 np.int64(-334653),
 np.int64(-381413),
 np.int64(-406839),
 np.int64(-621204),
 np.int64(-400593),
 np.int64(-362283),
 np.int64(-309779),
 np.int64(-350182),
 np.int64(-383617),
 np.int64(-282973),
 np.int64(-327538),
 np.int64(-342429),
 np.int64(-202702),
 np.int64(-210709),
 np.int64(-243625),
 np.int64(-254327),
 np.int64(-266850),
 np.int64(-198800),
 np.int64(-219228),
 np.int64(-138990),
 np.int64(-139624),
 np.int64(-163561),
 np.int64(-166182),
 np.int64(-165887),
 np.int64(-170015),
 np.int64(-171442),
 np.int64(-99569),
 np.int64(-95339),
 np.int64(-104814),
 np.int64(-102210),
 np.int64(-109823),
 np.int64(-93132),
 np.int64(-90435),
 np.int64(-57164),
 np.int64(-54617),
 np.int64(-56428),
 np.int64(-54935),
 np.int64(-53903),
 np.int64(-54122),
 np.int64(-49567),
 np.int64(-36717),
 np.int64(-35283),
 np.int64(-38689),
 np.int64(-36345),
 np.int64(-27438),
 np.int64(-22906),
 np.int64(-20268),
 np.int64(-18338),
 np.int64(-17077),
 np.int64(-17522),
 np.int64(-17513),
 np.int64(-16093),
 np.int64(-14514),
 np.int64(-13009),
 np.int64(-8570),
 np.int64(-7511),
 np.int64(-7626),
 np.int64(-7004),
 np.int64(-6766),
 np.int64(-6600),
 np.int64(-5803),
 np.int64(-4062),
 np.int64(-3854),
 np.int64(-4189),
 np.int64(-4419),
 np.int64(-4538),
 np.int64(-4164),
 np.int64(-4383),
 np.int64(-3092),
 np.int64(-3005),
 np.int64(-3371),
 np.int64(-3507),
 np.int64(-3713),
 np.int64(-4122),
 np.int64(-4441),
 np.int64(-3021),
 np.int64(-3125),
 np.int64(-3831),
 np.int64(-4415),
 np.int64(-4873),
 np.int64(-5034),
 np.int64(-5407),
 np.int64(-3864),
 np.int64(-4203),
 np.int64(-5413),
 np.int64(-5840),
 np.int64(-6233),
 np.int64(-6914),
 np.int64(-7452),
 np.int64(-5192),
 np.int64(-5316),
 np.int64(-6233),
 np.int64(-7310),
 np.int64(-7434),
 np.int64(-7619),
 np.int64(-7849),
 np.int64(-5567),
 np.int64(-5816),
 np.int64(-6681),
 np.int64(-6977),
 np.int64(-6748),
 np.int64(-7375),
 np.int64(-7173),
 np.int64(-4953),
 np.int64(-4324),
 np.int64(-5125),
 np.int64(-5352),
 np.int64(-4944),
 np.int64(-5263),
 np.int64(-5122),
 np.int64(-3031),
 np.int64(-3307),
 np.int64(-3925),
 np.int64(-4067),
 np.int64(-3896),
 np.int64(-3937),
 np.int64(-4113),
 np.int64(-2697),
 np.int64(-2827),
 np.int64(-3120),
 np.int64(-3205),
 np.int64(-3033),
 np.int64(-3292),
 np.int64(-3189),
 np.int64(-2122),
 np.int64(-2004),
 np.int64(-2418),
 np.int64(-2324),
 np.int64(-2368),
 np.int64(-2518),
 np.int64(-2425),
 np.int64(-1717),
 np.int64(-1754),
 np.int64(-2225),
 np.int64(-2246),
 np.int64(-2343),
 np.int64(-2482),
 np.int64(-2667),
 np.int64(-1588),
 np.int64(-1685),
 np.int64(-2061),
 np.int64(-2104),
 np.int64(-2121),
 np.int64(-2111),
 np.int64(-1945),
 np.int64(-1272),
 np.int64(-1190),
 np.int64(-1421),
 np.int64(-1508),
 np.int64(-1438),
 np.int64(-1441),
 np.int64(-1571),
 np.int64(-1073),
 np.int64(-1050),
 np.int64(-1420),
 np.int64(-1617),
 np.int64(-1683),
 np.int64(-1939),
 np.int64(-1583),
 np.int64(-1346),
 np.int64(-1297),
 np.int64(-1594),
 np.int64(-1953),
 np.int64(-2171),
 np.int64(-2425),
 np.int64(-2027),
 np.int64(-1574),
 np.int64(-1670),
 np.int64(-2085),
 np.int64(-2247),
 np.int64(-2484),
 np.int64(-2561),
 np.int64(-2881),
 np.int64(-2288),
 np.int64(-2381),
 np.int64(-2768),
 np.int64(-3270),
 np.int64(-2429),
 np.int64(-1715),
 np.int64(-1720),
 np.int64(-1729),
 np.int64(-1604),
 np.int64(-1909),
 np.int64(-2087),
 np.int64(-2008),
 np.int64(-1942),
 np.int64(-2065),
 np.int64(-1508),
 np.int64(-1433),
 np.int64(-1755),
 np.int64(-1864),
 np.int64(-1893),
 np.int64(-2049),
 np.int64(-2047),
 np.int64(-1597),
 np.int64(-1375),
 np.int64(-1490),
 np.int64(-1803),
 np.int64(-1708),
 np.int64(-1960),
 np.int64(-2024),
 np.int64(-1370),
 np.int64(-1485),
 np.int64(-1619),
 np.int64(-1791),
 np.int64(-1837),
 np.int64(-1882),
 np.int64(-2154),
 np.int64(-1507),
 np.int64(-1417),
 np.int64(-1626),
 np.int64(-1787),
 np.int64(-2140),
 np.int64(-2152),
 np.int64(-1803),
 np.int64(-1372),
 np.int64(-1554),
 np.int64(-1816),
 np.int64(-1928),
 np.int64(-1989),
 np.int64(-1987),
 np.int64(-2221),
 np.int64(-1537),
 np.int64(-1491),
 np.int64(-1727),
 np.int64(-1823),
 np.int64(-1704),
 np.int64(-1775),
 np.int64(-1725),
 np.int64(-1200),
 np.int64(-1218),
 np.int64(-1442),
 np.int64(-1538),
 np.int64(-1710),
 np.int64(-1673),
 np.int64(-1895),
 np.int64(-1363),
 np.int64(-1318),
 np.int64(-1487),
 np.int64(-1627),
 np.int64(-1629),
 np.int64(-1841),
 np.int64(-1781),
 np.int64(-1278),
 np.int64(-1251),
 np.int64(-1453),
 np.int64(-1449),
 np.int64(-1535),
 np.int64(-1599),
 np.int64(-1613),
 np.int64(-1150),
 np.int64(-1100),
 np.int64(-1324),
 np.int64(-1378),
 np.int64(-1316),
 np.int64(-1275),
 np.int64(-1211),
 np.int64(-746),
 np.int64(-711),
 np.int64(-743),
 np.int64(-794),
 np.int64(-825),
 np.int64(-761),
 np.int64(-794),
 np.int64(-595),
 np.int64(-501),
 np.int64(-614),
 np.int64(-668),
 np.int64(-634),
 np.int64(-610),
 np.int64(-645),
 np.int64(-394),
 np.int64(-357),
 np.int64(-429),
 np.int64(-482),
 np.int64(-507),
 np.int64(-540),
 np.int64(-545),
 np.int64(-373),
 np.int64(-399),
 np.int64(-452),
 np.int64(-565),
 np.int64(-556),
 np.int64(-610),
 np.int64(-602),
 np.int64(-454),
 np.int64(-485),
 np.int64(-556),
 np.int64(-744),
 np.int64(-695),
 np.int64(-681),
 np.int64(-677),
 np.int64(-889),
 np.int64(430),
 np.int64(-910),
 np.int64(-533),
 np.int64(-587),
 np.int64(-629),
 np.int64(-705),
 np.int64(-516),
 np.int64(-530),
 np.int64(-585),
 np.int64(-666),
 np.int64(-561),
 np.int64(-646),
 np.int64(-654),
 np.int64(-528),
 np.int64(-619),
 np.int64(-610),
 np.int64(-681),
 np.int64(-747),
 np.int64(-715),
 np.int64(-634),
 np.int64(-510),
 np.int64(-463),
 np.int64(-564),
 np.int64(-701),
 np.int64(-525),
 np.int64(-574),
 np.int64(-676),
 np.int64(-541),
 np.int64(-488),
 np.int64(-606),
 np.int64(-627),
 np.int64(-661),
 np.int64(-679),
 np.int64(-769),
 np.int64(-512),
 np.int64(-499),
 np.int64(-644),
 np.int64(-785),
 np.int64(-797),
 np.int64(-735),
 np.int64(-731),
 np.int64(-549),
 np.int64(-532),
 np.int64(-671),
 np.int64(-658),
 np.int64(-673),
 np.int64(-698),
 np.int64(-731),
 np.int64(-542),
 np.int64(-587),
 np.int64(-614),
 np.int64(-677),
 np.int64(-671),
 np.int64(-700),
 np.int64(-668),
 np.int64(-477),
 np.int64(-473),
 np.int64(-543),
 np.int64(-543),
 np.int64(-557),
 np.int64(-551),
 np.int64(-506),
 np.int64(-447),
 np.int64(-382),
 np.int64(-482),
 np.int64(-505),
 np.int64(-489),
 np.int64(-430),
 np.int64(-428),
 np.int64(-346),
 np.int64(-415),
 np.int64(-456),
 np.int64(-447),
 np.int64(-463),
 np.int64(-445),
 np.int64(-469),
 np.int64(-363),
 np.int64(-379),
 np.int64(-459),
 np.int64(-490),
 np.int64(-488),
 np.int64(-465),
 np.int64(-470),
 np.int64(-446),
 np.int64(-346),
 np.int64(-416),
 np.int64(-418),
 np.int64(-398),
 np.int64(-424),
 np.int64(-444),
 np.int64(-344),
 np.int64(-355),
 np.int64(-355),
 np.int64(-415),
 np.int64(-387),
 np.int64(-395),
 np.int64(-440),
 np.int64(-356),
 np.int64(-332),
 np.int64(-416),
 np.int64(-448),
 np.int64(-561),
 np.int64(-621),
 np.int64(-621),
 np.int64(-457),
 np.int64(-343),
 np.int64(-326),
 np.int64(-362),
 np.int64(-403),
 np.int64(-504),
 np.int64(-444),
 np.int64(-303),
 np.int64(-288),
 np.int64(-371),
 np.int64(-390),
 np.int64(-370),
 np.int64(-451),
 np.int64(-467),
 np.int64(-336),
 np.int64(-305),
 np.int64(-354),
 np.int64(-456),
 np.int64(-469),
 np.int64(-497),
 np.int64(-559),
 np.int64(-349),
 np.int64(-437),
 np.int64(-392),
 np.int64(-431),
 np.int64(-346),
 np.int64(-400),
 np.int64(-404),
 np.int64(-386),
 np.int64(-389),
 np.int64(-520),
 np.int64(-580),
 np.int64(-512),
 np.int64(-524),
 np.int64(-561),
 np.int64(-537),
 np.int64(-451),
 np.int64(-657),
 np.int64(-641),
 np.int64(-674),
 np.int64(-869),
 np.int64(-838),
 np.int64(-714),
 np.int64(-1020),
 np.int64(-657),
 np.int64(-820),
 np.int64(-1027),
 np.int64(-967),
 np.int64(-1050),
 np.int64(-1044),
 np.int64(-806),
 np.int64(-970),
 np.int64(-1131),
 np.int64(-1240),
 np.int64(-985),
 np.int64(-1090),
 np.int64(-866),
 np.int64(-924),
 np.int64(-1096),
 np.int64(-1045),
 np.int64(-1064),
 np.int64(-1014),
 np.int64(-1078),
 np.int64(-880),
 np.int64(-718),
 np.int64(-1030),
 np.int64(-950),
 np.int64(-689),
 np.int64(-680),
 np.int64(-670),
 np.int64(-587),
 np.int64(-615),
 np.int64(-631),
 np.int64(-577),
 np.int64(-628),
 np.int64(-540),
 np.int64(-511),
 np.int64(-451),
 np.int64(-438),
 np.int64(-450),
 np.int64(-503),
 np.int64(-555),
 np.int64(-581),
 np.int64(-382),
 np.int64(-349),
 np.int64(-271),
 np.int64(-330),
 np.int64(-386),
 np.int64(-348),
 np.int64(-325),
 np.int64(-285),
 np.int64(-230),
 np.int64(-222),
 np.int64(-208),
 np.int64(-205),
 np.int64(-191),
 np.int64(-143),
 np.int64(-145),
 np.int64(-100),
 np.int64(-126),
 np.int64(-143),
 np.int64(-89),
 np.int64(-145),
 np.int64(-125),
 np.int64(-117),
 np.int64(-75),
 np.int64(-97),
 np.int64(-124),
 np.int64(-127),
 np.int64(-113),
 np.int64(-125),
 np.int64(-103),
 np.int64(-88),
 np.int64(-119),
 np.int64(-61),
 np.int64(-77),
 np.int64(-155),
 np.int64(-121),
 np.int64(-89),
 np.int64(-58),
 np.int64(-76),
 np.int64(-91),
 np.int64(-73),
 np.int64(-47),
 np.int64(-110),
 np.int64(-84),
 np.int64(-91),
 np.int64(-98),
 np.int64(-58),
 np.int64(-72),
 np.int64(-54),
 np.int64(-69),
 np.int64(-114),
 np.int64(-75),
 np.int64(-73),
 np.int64(-64),
 np.int64(-75),
 np.int64(-63),
 np.int64(-77),
 np.int64(-113),
 np.int64(-38),
 np.int64(-50),
 np.int64(-95),
 np.int64(-61),
 np.int64(-114),
 np.int64(-125),
 np.int64(-110),
 np.int64(-61),
 np.int64(-70),
 np.int64(-82),
 np.int64(-110),
 np.int64(-126),
 np.int64(-153),
 np.int64(-113),
 np.int64(-106),
 np.int64(-109),
 np.int64(-121),
 np.int64(-136),
 np.int64(-176),
 np.int64(-155),
 np.int64(-156),
 np.int64(-136),
 np.int64(-119),
 np.int64(-167),
 np.int64(-168),
 np.int64(-198),
 np.int64(-195),
 np.int64(-267),
 np.int64(-235),
 np.int64(-248),
 np.int64(-299),
 np.int64(-323),
 np.int64(-371),
 np.int64(-441),
 np.int64(-320),
 np.int64(-280),
 np.int64(-266),
 np.int64(-396),
 np.int64(-332),
 np.int64(-324),
 np.int64(-288),
 np.int64(-297),
 np.int64(-246),
 np.int64(-197),
 np.int64(-279),
 np.int64(-166),
 np.int64(-103),
 np.int64(-56),
 np.int64(-54),
 np.int64(-34),
 np.int64(-28),
 np.int64(-36),
 np.int64(-43),
 np.int64(-20),
 np.int64(-43),
 np.int64(-33),
 np.int64(-34),
 np.int64(-23),
 np.int64(-30),
 np.int64(-31),
 np.int64(-36),
 np.int64(-18),
 np.int64(-48),
 np.int64(-28),
 np.int64(-25),
 np.int64(-58),
 np.int64(-113),
 np.int64(-41),
 np.int64(-59),
 np.int64(-63),
 np.int64(-45),
 np.int64(-26),
 np.int64(-34),
 np.int64(-39),
 np.int64(-60),
 np.int64(-61),
 np.int64(-39),
 np.int64(-33),
 np.int64(-62),
 np.int64(-44),
 np.int64(-35),
 np.int64(-45),
 np.int64(-50),
 np.int64(-62),
 np.int64(-44),
 np.int64(-48),
 np.int64(-61),
 np.int64(-63),
 np.int64(-61),
 np.int64(-54),
 np.int64(-51),
 np.int64(-42),
 np.int64(-42),
 np.int64(-62),
 np.int64(-51),
 np.int64(-39),
 np.int64(-28),
 np.int64(-51),
 np.int64(-46),
 np.int64(-17),
 np.int64(-48),
 np.int64(-67),
 np.int64(-49),
 np.int64(-59),
 np.int64(-43),
 np.int64(-34),
 np.int64(-37),
 np.int64(-34),
 np.int64(-48),
 np.int64(-56),
 np.int64(-45),
 np.int64(-50),
 np.int64(-38),
 np.int64(-37),
 np.int64(-57),
 np.int64(-51),
 np.int64(-39),
 np.int64(-39),
 np.int64(-49),
 np.int64(-38),
 np.int64(-35),
 np.int64(-27),
 np.int64(-39),
 np.int64(-58),
 np.int64(-79),
 np.int64(-40),
 np.int64(-19),
 np.int64(-16),
 np.int64(-25),
 np.int64(-23),
 np.int64(-20),
 np.int64(-12),
 np.int64(-32),
 np.int64(-13),
 np.int64(-15),
 np.int64(-13),
 np.int64(-19),
 np.int64(-56),
 np.int64(-26),
 np.int64(-27),
 np.int64(-35),
 np.int64(-34),
 np.int64(-18),
 np.int64(-12),
 np.int64(-4),
 np.int64(-2),
 np.int64(-3),
 np.int64(-8),
 np.int64(-13),
 np.int64(-6),
 np.int64(-9),
 np.int64(-4),
 np.int64(-9),
 np.int64(-14),
 np.int64(-10),
 np.int64(-10),
 np.int64(-10),
 np.int64(-6),
 np.int64(-8),
 np.int64(-11),
 np.int64(-9),
 np.int64(-13),
 np.int64(-8),
 np.int64(-18),
 np.int64(-22),
 np.int64(-22),
 np.int64(-27),
 np.int64(-27),
 np.int64(-25),
 np.int64(-32),
 np.int64(-30),
 np.int64(-27),
 np.int64(-39),
 np.int64(-53),
 np.int64(-47),
 np.int64(-47),
 np.int64(-81),
 np.int64(-94),
 np.int64(-86),
 np.int64(-89),
 np.int64(-101),
 np.int64(-125),
 np.int64(-78),
 np.int64(-105),
 np.int64(-146),
 np.int64(-91),
 np.int64(-104),
 np.int64(-100),
 np.int64(-76),
 np.int64(-64),
 np.int64(-98),
 np.int64(-147),
 np.int64(-87),
 np.int64(-152),
 np.int64(-93),
 np.int64(-84),
 np.int64(-74),
 np.int64(-76),
 np.int64(-107),
 np.int64(-110),
 np.int64(-114),
 np.int64(-242)]

In [ ]:
new_list2=[0]

for i in range(1,820,1):
    result=corona.loc[i,'총확진자']-corona.loc[i-1,'총확진자']
    new_list2.append(result)

len(new_list2)

819

In [67]:
# 819번 반복하면서 일일확진자의 데이터는 819개 -> 첫번째 데이터는 일일확진자를 구할 수 없기 때문
# 첫날의 데이터는 0으로 생성
# 만들어진 리스트에 0을 첫번째 데이터로 대입 -> list.insert(0,0)
# 리스트+리스트->연결[0]+new_list
# 반복 실행하기 전 new_list를 빈 리스트가 아니라 [0] 대입한 뒤 append()
# case1
[0]+new_list

[0,
 np.int64(-13358),
 np.int64(-6172),
 np.int64(-5022),
 np.int64(-9834),
 np.int64(-12039),
 np.int64(-12539),
 np.int64(-9891),
 np.int64(-15768),
 np.int64(-17185),
 np.int64(-6135),
 np.int64(-12647),
 np.int64(-14374),
 np.int64(-16572),
 np.int64(-18805),
 np.int64(-23936),
 np.int64(-26331),
 np.int64(-9971),
 np.int64(-19289),
 np.int64(-23450),
 np.int64(-25113),
 np.int64(-28109),
 np.int64(-31333),
 np.int64(-35085),
 np.int64(-13290),
 np.int64(-25425),
 np.int64(-29572),
 np.int64(-32435),
 np.int64(-35882),
 np.int64(-43881),
 np.int64(-49896),
 np.int64(-20588),
 np.int64(-40048),
 np.int64(-39563),
 np.int64(-26678),
 np.int64(-42279),
 np.int64(-49046),
 np.int64(-51106),
 np.int64(-20076),
 np.int64(-37760),
 np.int64(-43244),
 np.int64(-50556),
 np.int64(-57446),
 np.int64(-76764),
 np.int64(-80267),
 np.int64(-34361),
 np.int64(-64704),
 np.int64(-75423),
 np.int64(-81033),
 np.int64(-90843),
 np.int64(-111289),
 np.int64(-118462),
 np.int64(-47730),
 np.int64(-92978),
 np.int64(-107882),
 np.int64(-125800),
 np.int64(-148409),
 np.int64(-195382),
 np.int64(-210715),
 np.int64(-90917),
 np.int64(-164456),
 np.int64(-185525),
 np.int64(-205299),
 np.int64(-224784),
 np.int64(-286247),
 np.int64(-266085),
 np.int64(-127163),
 np.int64(-234265),
 np.int64(-264120),
 np.int64(-280231),
 np.int64(-320683),
 np.int64(-424466),
 np.int64(-347500),
 np.int64(-187182),
 np.int64(-318075),
 np.int64(-335541),
 np.int64(-339451),
 np.int64(-395526),
 np.int64(-490771),
 np.int64(-353828),
 np.int64(-209139),
 np.int64(-334653),
 np.int64(-381413),
 np.int64(-406839),
 np.int64(-621204),
 np.int64(-400593),
 np.int64(-362283),
 np.int64(-309779),
 np.int64(-350182),
 np.int64(-383617),
 np.int64(-282973),
 np.int64(-327538),
 np.int64(-342429),
 np.int64(-202702),
 np.int64(-210709),
 np.int64(-243625),
 np.int64(-254327),
 np.int64(-266850),
 np.int64(-198800),
 np.int64(-219228),
 np.int64(-138990),
 np.int64(-139624),
 np.int64(-163561),
 np.int64(-166182),
 np.int64(-165887),
 np.int64(-170015),
 np.int64(-171442),
 np.int64(-99569),
 np.int64(-95339),
 np.int64(-104814),
 np.int64(-102210),
 np.int64(-109823),
 np.int64(-93132),
 np.int64(-90435),
 np.int64(-57164),
 np.int64(-54617),
 np.int64(-56428),
 np.int64(-54935),
 np.int64(-53903),
 np.int64(-54122),
 np.int64(-49567),
 np.int64(-36717),
 np.int64(-35283),
 np.int64(-38689),
 np.int64(-36345),
 np.int64(-27438),
 np.int64(-22906),
 np.int64(-20268),
 np.int64(-18338),
 np.int64(-17077),
 np.int64(-17522),
 np.int64(-17513),
 np.int64(-16093),
 np.int64(-14514),
 np.int64(-13009),
 np.int64(-8570),
 np.int64(-7511),
 np.int64(-7626),
 np.int64(-7004),
 np.int64(-6766),
 np.int64(-6600),
 np.int64(-5803),
 np.int64(-4062),
 np.int64(-3854),
 np.int64(-4189),
 np.int64(-4419),
 np.int64(-4538),
 np.int64(-4164),
 np.int64(-4383),
 np.int64(-3092),
 np.int64(-3005),
 np.int64(-3371),
 np.int64(-3507),
 np.int64(-3713),
 np.int64(-4122),
 np.int64(-4441),
 np.int64(-3021),
 np.int64(-3125),
 np.int64(-3831),
 np.int64(-4415),
 np.int64(-4873),
 np.int64(-5034),
 np.int64(-5407),
 np.int64(-3864),
 np.int64(-4203),
 np.int64(-5413),
 np.int64(-5840),
 np.int64(-6233),
 np.int64(-6914),
 np.int64(-7452),
 np.int64(-5192),
 np.int64(-5316),
 np.int64(-6233),
 np.int64(-7310),
 np.int64(-7434),
 np.int64(-7619),
 np.int64(-7849),
 np.int64(-5567),
 np.int64(-5816),
 np.int64(-6681),
 np.int64(-6977),
 np.int64(-6748),
 np.int64(-7375),
 np.int64(-7173),
 np.int64(-4953),
 np.int64(-4324),
 np.int64(-5125),
 np.int64(-5352),
 np.int64(-4944),
 np.int64(-5263),
 np.int64(-5122),
 np.int64(-3031),
 np.int64(-3307),
 np.int64(-3925),
 np.int64(-4067),
 np.int64(-3896),
 np.int64(-3937),
 np.int64(-4113),
 np.int64(-2697),
 np.int64(-2827),
 np.int64(-3120),
 np.int64(-3205),
 np.int64(-3033),
 np.int64(-3292),
 np.int64(-3189),
 np.int64(-2122),
 np.int64(-2004),
 np.int64(-2418),
 np.int64(-2324),
 np.int64(-2368),
 np.int64(-2518),
 np.int64(-2425),
 np.int64(-1717),
 np.int64(-1754),
 np.int64(-2225),
 np.int64(-2246),
 np.int64(-2343),
 np.int64(-2482),
 np.int64(-2667),
 np.int64(-1588),
 np.int64(-1685),
 np.int64(-2061),
 np.int64(-2104),
 np.int64(-2121),
 np.int64(-2111),
 np.int64(-1945),
 np.int64(-1272),
 np.int64(-1190),
 np.int64(-1421),
 np.int64(-1508),
 np.int64(-1438),
 np.int64(-1441),
 np.int64(-1571),
 np.int64(-1073),
 np.int64(-1050),
 np.int64(-1420),
 np.int64(-1617),
 np.int64(-1683),
 np.int64(-1939),
 np.int64(-1583),
 np.int64(-1346),
 np.int64(-1297),
 np.int64(-1594),
 np.int64(-1953),
 np.int64(-2171),
 np.int64(-2425),
 np.int64(-2027),
 np.int64(-1574),
 np.int64(-1670),
 np.int64(-2085),
 np.int64(-2247),
 np.int64(-2484),
 np.int64(-2561),
 np.int64(-2881),
 np.int64(-2288),
 np.int64(-2381),
 np.int64(-2768),
 np.int64(-3270),
 np.int64(-2429),
 np.int64(-1715),
 np.int64(-1720),
 np.int64(-1729),
 np.int64(-1604),
 np.int64(-1909),
 np.int64(-2087),
 np.int64(-2008),
 np.int64(-1942),
 np.int64(-2065),
 np.int64(-1508),
 np.int64(-1433),
 np.int64(-1755),
 np.int64(-1864),
 np.int64(-1893),
 np.int64(-2049),
 np.int64(-2047),
 np.int64(-1597),
 np.int64(-1375),
 np.int64(-1490),
 np.int64(-1803),
 np.int64(-1708),
 np.int64(-1960),
 np.int64(-2024),
 np.int64(-1370),
 np.int64(-1485),
 np.int64(-1619),
 np.int64(-1791),
 np.int64(-1837),
 np.int64(-1882),
 np.int64(-2154),
 np.int64(-1507),
 np.int64(-1417),
 np.int64(-1626),
 np.int64(-1787),
 np.int64(-2140),
 np.int64(-2152),
 np.int64(-1803),
 np.int64(-1372),
 np.int64(-1554),
 np.int64(-1816),
 np.int64(-1928),
 np.int64(-1989),
 np.int64(-1987),
 np.int64(-2221),
 np.int64(-1537),
 np.int64(-1491),
 np.int64(-1727),
 np.int64(-1823),
 np.int64(-1704),
 np.int64(-1775),
 np.int64(-1725),
 np.int64(-1200),
 np.int64(-1218),
 np.int64(-1442),
 np.int64(-1538),
 np.int64(-1710),
 np.int64(-1673),
 np.int64(-1895),
 np.int64(-1363),
 np.int64(-1318),
 np.int64(-1487),
 np.int64(-1627),
 np.int64(-1629),
 np.int64(-1841),
 np.int64(-1781),
 np.int64(-1278),
 np.int64(-1251),
 np.int64(-1453),
 np.int64(-1449),
 np.int64(-1535),
 np.int64(-1599),
 np.int64(-1613),
 np.int64(-1150),
 np.int64(-1100),
 np.int64(-1324),
 np.int64(-1378),
 np.int64(-1316),
 np.int64(-1275),
 np.int64(-1211),
 np.int64(-746),
 np.int64(-711),
 np.int64(-743),
 np.int64(-794),
 np.int64(-825),
 np.int64(-761),
 np.int64(-794),
 np.int64(-595),
 np.int64(-501),
 np.int64(-614),
 np.int64(-668),
 np.int64(-634),
 np.int64(-610),
 np.int64(-645),
 np.int64(-394),
 np.int64(-357),
 np.int64(-429),
 np.int64(-482),
 np.int64(-507),
 np.int64(-540),
 np.int64(-545),
 np.int64(-373),
 np.int64(-399),
 np.int64(-452),
 np.int64(-565),
 np.int64(-556),
 np.int64(-610),
 np.int64(-602),
 np.int64(-454),
 np.int64(-485),
 np.int64(-556),
 np.int64(-744),
 np.int64(-695),
 np.int64(-681),
 np.int64(-677),
 np.int64(-889),
 np.int64(430),
 np.int64(-910),
 np.int64(-533),
 np.int64(-587),
 np.int64(-629),
 np.int64(-705),
 np.int64(-516),
 np.int64(-530),
 np.int64(-585),
 np.int64(-666),
 np.int64(-561),
 np.int64(-646),
 np.int64(-654),
 np.int64(-528),
 np.int64(-619),
 np.int64(-610),
 np.int64(-681),
 np.int64(-747),
 np.int64(-715),
 np.int64(-634),
 np.int64(-510),
 np.int64(-463),
 np.int64(-564),
 np.int64(-701),
 np.int64(-525),
 np.int64(-574),
 np.int64(-676),
 np.int64(-541),
 np.int64(-488),
 np.int64(-606),
 np.int64(-627),
 np.int64(-661),
 np.int64(-679),
 np.int64(-769),
 np.int64(-512),
 np.int64(-499),
 np.int64(-644),
 np.int64(-785),
 np.int64(-797),
 np.int64(-735),
 np.int64(-731),
 np.int64(-549),
 np.int64(-532),
 np.int64(-671),
 np.int64(-658),
 np.int64(-673),
 np.int64(-698),
 np.int64(-731),
 np.int64(-542),
 np.int64(-587),
 np.int64(-614),
 np.int64(-677),
 np.int64(-671),
 np.int64(-700),
 np.int64(-668),
 np.int64(-477),
 np.int64(-473),
 np.int64(-543),
 np.int64(-543),
 np.int64(-557),
 np.int64(-551),
 np.int64(-506),
 np.int64(-447),
 np.int64(-382),
 np.int64(-482),
 np.int64(-505),
 np.int64(-489),
 np.int64(-430),
 np.int64(-428),
 np.int64(-346),
 np.int64(-415),
 np.int64(-456),
 np.int64(-447),
 np.int64(-463),
 np.int64(-445),
 np.int64(-469),
 np.int64(-363),
 np.int64(-379),
 np.int64(-459),
 np.int64(-490),
 np.int64(-488),
 np.int64(-465),
 np.int64(-470),
 np.int64(-446),
 np.int64(-346),
 np.int64(-416),
 np.int64(-418),
 np.int64(-398),
 np.int64(-424),
 np.int64(-444),
 np.int64(-344),
 np.int64(-355),
 np.int64(-355),
 np.int64(-415),
 np.int64(-387),
 np.int64(-395),
 np.int64(-440),
 np.int64(-356),
 np.int64(-332),
 np.int64(-416),
 np.int64(-448),
 np.int64(-561),
 np.int64(-621),
 np.int64(-621),
 np.int64(-457),
 np.int64(-343),
 np.int64(-326),
 np.int64(-362),
 np.int64(-403),
 np.int64(-504),
 np.int64(-444),
 np.int64(-303),
 np.int64(-288),
 np.int64(-371),
 np.int64(-390),
 np.int64(-370),
 np.int64(-451),
 np.int64(-467),
 np.int64(-336),
 np.int64(-305),
 np.int64(-354),
 np.int64(-456),
 np.int64(-469),
 np.int64(-497),
 np.int64(-559),
 np.int64(-349),
 np.int64(-437),
 np.int64(-392),
 np.int64(-431),
 np.int64(-346),
 np.int64(-400),
 np.int64(-404),
 np.int64(-386),
 np.int64(-389),
 np.int64(-520),
 np.int64(-580),
 np.int64(-512),
 np.int64(-524),
 np.int64(-561),
 np.int64(-537),
 np.int64(-451),
 np.int64(-657),
 np.int64(-641),
 np.int64(-674),
 np.int64(-869),
 np.int64(-838),
 np.int64(-714),
 np.int64(-1020),
 np.int64(-657),
 np.int64(-820),
 np.int64(-1027),
 np.int64(-967),
 np.int64(-1050),
 np.int64(-1044),
 np.int64(-806),
 np.int64(-970),
 np.int64(-1131),
 np.int64(-1240),
 np.int64(-985),
 np.int64(-1090),
 np.int64(-866),
 np.int64(-924),
 np.int64(-1096),
 np.int64(-1045),
 np.int64(-1064),
 np.int64(-1014),
 np.int64(-1078),
 np.int64(-880),
 np.int64(-718),
 np.int64(-1030),
 np.int64(-950),
 np.int64(-689),
 np.int64(-680),
 np.int64(-670),
 np.int64(-587),
 np.int64(-615),
 np.int64(-631),
 np.int64(-577),
 np.int64(-628),
 np.int64(-540),
 np.int64(-511),
 np.int64(-451),
 np.int64(-438),
 np.int64(-450),
 np.int64(-503),
 np.int64(-555),
 np.int64(-581),
 np.int64(-382),
 np.int64(-349),
 np.int64(-271),
 np.int64(-330),
 np.int64(-386),
 np.int64(-348),
 np.int64(-325),
 np.int64(-285),
 np.int64(-230),
 np.int64(-222),
 np.int64(-208),
 np.int64(-205),
 np.int64(-191),
 np.int64(-143),
 np.int64(-145),
 np.int64(-100),
 np.int64(-126),
 np.int64(-143),
 np.int64(-89),
 np.int64(-145),
 np.int64(-125),
 np.int64(-117),
 np.int64(-75),
 np.int64(-97),
 np.int64(-124),
 np.int64(-127),
 np.int64(-113),
 np.int64(-125),
 np.int64(-103),
 np.int64(-88),
 np.int64(-119),
 np.int64(-61),
 np.int64(-77),
 np.int64(-155),
 np.int64(-121),
 np.int64(-89),
 np.int64(-58),
 np.int64(-76),
 np.int64(-91),
 np.int64(-73),
 np.int64(-47),
 np.int64(-110),
 np.int64(-84),
 np.int64(-91),
 np.int64(-98),
 np.int64(-58),
 np.int64(-72),
 np.int64(-54),
 np.int64(-69),
 np.int64(-114),
 np.int64(-75),
 np.int64(-73),
 np.int64(-64),
 np.int64(-75),
 np.int64(-63),
 np.int64(-77),
 np.int64(-113),
 np.int64(-38),
 np.int64(-50),
 np.int64(-95),
 np.int64(-61),
 np.int64(-114),
 np.int64(-125),
 np.int64(-110),
 np.int64(-61),
 np.int64(-70),
 np.int64(-82),
 np.int64(-110),
 np.int64(-126),
 np.int64(-153),
 np.int64(-113),
 np.int64(-106),
 np.int64(-109),
 np.int64(-121),
 np.int64(-136),
 np.int64(-176),
 np.int64(-155),
 np.int64(-156),
 np.int64(-136),
 np.int64(-119),
 np.int64(-167),
 np.int64(-168),
 np.int64(-198),
 np.int64(-195),
 np.int64(-267),
 np.int64(-235),
 np.int64(-248),
 np.int64(-299),
 np.int64(-323),
 np.int64(-371),
 np.int64(-441),
 np.int64(-320),
 np.int64(-280),
 np.int64(-266),
 np.int64(-396),
 np.int64(-332),
 np.int64(-324),
 np.int64(-288),
 np.int64(-297),
 np.int64(-246),
 np.int64(-197),
 np.int64(-279),
 np.int64(-166),
 np.int64(-103),
 np.int64(-56),
 np.int64(-54),
 np.int64(-34),
 np.int64(-28),
 np.int64(-36),
 np.int64(-43),
 np.int64(-20),
 np.int64(-43),
 np.int64(-33),
 np.int64(-34),
 np.int64(-23),
 np.int64(-30),
 np.int64(-31),
 np.int64(-36),
 np.int64(-18),
 np.int64(-48),
 np.int64(-28),
 np.int64(-25),
 np.int64(-58),
 np.int64(-113),
 np.int64(-41),
 np.int64(-59),
 np.int64(-63),
 np.int64(-45),
 np.int64(-26),
 np.int64(-34),
 np.int64(-39),
 np.int64(-60),
 np.int64(-61),
 np.int64(-39),
 np.int64(-33),
 np.int64(-62),
 np.int64(-44),
 np.int64(-35),
 np.int64(-45),
 np.int64(-50),
 np.int64(-62),
 np.int64(-44),
 np.int64(-48),
 np.int64(-61),
 np.int64(-63),
 np.int64(-61),
 np.int64(-54),
 np.int64(-51),
 np.int64(-42),
 np.int64(-42),
 np.int64(-62),
 np.int64(-51),
 np.int64(-39),
 np.int64(-28),
 np.int64(-51),
 np.int64(-46),
 np.int64(-17),
 np.int64(-48),
 np.int64(-67),
 np.int64(-49),
 np.int64(-59),
 np.int64(-43),
 np.int64(-34),
 np.int64(-37),
 np.int64(-34),
 np.int64(-48),
 np.int64(-56),
 np.int64(-45),
 np.int64(-50),
 np.int64(-38),
 np.int64(-37),
 np.int64(-57),
 np.int64(-51),
 np.int64(-39),
 np.int64(-39),
 np.int64(-49),
 np.int64(-38),
 np.int64(-35),
 np.int64(-27),
 np.int64(-39),
 np.int64(-58),
 np.int64(-79),
 np.int64(-40),
 np.int64(-19),
 np.int64(-16),
 np.int64(-25),
 np.int64(-23),
 np.int64(-20),
 np.int64(-12),
 np.int64(-32),
 np.int64(-13),
 np.int64(-15),
 np.int64(-13),
 np.int64(-19),
 np.int64(-56),
 np.int64(-26),
 np.int64(-27),
 np.int64(-35),
 np.int64(-34),
 np.int64(-18),
 np.int64(-12),
 np.int64(-4),
 np.int64(-2),
 np.int64(-3),
 np.int64(-8),
 np.int64(-13),
 np.int64(-6),
 np.int64(-9),
 np.int64(-4),
 np.int64(-9),
 np.int64(-14),
 np.int64(-10),
 np.int64(-10),
 np.int64(-10),
 np.int64(-6),
 np.int64(-8),
 np.int64(-11),
 np.int64(-9),
 np.int64(-13),
 np.int64(-8),
 np.int64(-18),
 np.int64(-22),
 np.int64(-22),
 np.int64(-27),
 np.int64(-27),
 np.int64(-25),
 np.int64(-32),
 np.int64(-30),
 np.int64(-27),
 np.int64(-39),
 np.int64(-53),
 np.int64(-47),
 np.int64(-47),
 np.int64(-81),
 np.int64(-94),
 np.int64(-86),
 np.int64(-89),
 np.int64(-101),
 np.int64(-125),
 np.int64(-78),
 np.int64(-105),
 np.int64(-146),
 np.int64(-91),
 np.int64(-104),
 np.int64(-100),
 np.int64(-76),
 np.int64(-64),
 np.int64(-98),
 np.int64(-147),
 np.int64(-87),
 np.int64(-152),
 np.int64(-93),
 np.int64(-84),
 np.int64(-74),
 np.int64(-76),
 np.int64(-107),
 np.int64(-110),
 np.int64(-114),
 np.int64(-242)]

In [68]:
# case2: insert()
new_list.insert(0,0)

In [70]:
new_list

[0,
 np.int64(-13358),
 np.int64(-6172),
 np.int64(-5022),
 np.int64(-9834),
 np.int64(-12039),
 np.int64(-12539),
 np.int64(-9891),
 np.int64(-15768),
 np.int64(-17185),
 np.int64(-6135),
 np.int64(-12647),
 np.int64(-14374),
 np.int64(-16572),
 np.int64(-18805),
 np.int64(-23936),
 np.int64(-26331),
 np.int64(-9971),
 np.int64(-19289),
 np.int64(-23450),
 np.int64(-25113),
 np.int64(-28109),
 np.int64(-31333),
 np.int64(-35085),
 np.int64(-13290),
 np.int64(-25425),
 np.int64(-29572),
 np.int64(-32435),
 np.int64(-35882),
 np.int64(-43881),
 np.int64(-49896),
 np.int64(-20588),
 np.int64(-40048),
 np.int64(-39563),
 np.int64(-26678),
 np.int64(-42279),
 np.int64(-49046),
 np.int64(-51106),
 np.int64(-20076),
 np.int64(-37760),
 np.int64(-43244),
 np.int64(-50556),
 np.int64(-57446),
 np.int64(-76764),
 np.int64(-80267),
 np.int64(-34361),
 np.int64(-64704),
 np.int64(-75423),
 np.int64(-81033),
 np.int64(-90843),
 np.int64(-111289),
 np.int64(-118462),
 np.int64(-47730),
 np.int64(-92978),
 np.int64(-107882),
 np.int64(-125800),
 np.int64(-148409),
 np.int64(-195382),
 np.int64(-210715),
 np.int64(-90917),
 np.int64(-164456),
 np.int64(-185525),
 np.int64(-205299),
 np.int64(-224784),
 np.int64(-286247),
 np.int64(-266085),
 np.int64(-127163),
 np.int64(-234265),
 np.int64(-264120),
 np.int64(-280231),
 np.int64(-320683),
 np.int64(-424466),
 np.int64(-347500),
 np.int64(-187182),
 np.int64(-318075),
 np.int64(-335541),
 np.int64(-339451),
 np.int64(-395526),
 np.int64(-490771),
 np.int64(-353828),
 np.int64(-209139),
 np.int64(-334653),
 np.int64(-381413),
 np.int64(-406839),
 np.int64(-621204),
 np.int64(-400593),
 np.int64(-362283),
 np.int64(-309779),
 np.int64(-350182),
 np.int64(-383617),
 np.int64(-282973),
 np.int64(-327538),
 np.int64(-342429),
 np.int64(-202702),
 np.int64(-210709),
 np.int64(-243625),
 np.int64(-254327),
 np.int64(-266850),
 np.int64(-198800),
 np.int64(-219228),
 np.int64(-138990),
 np.int64(-139624),
 np.int64(-163561),
 np.int64(-166182),
 np.int64(-165887),
 np.int64(-170015),
 np.int64(-171442),
 np.int64(-99569),
 np.int64(-95339),
 np.int64(-104814),
 np.int64(-102210),
 np.int64(-109823),
 np.int64(-93132),
 np.int64(-90435),
 np.int64(-57164),
 np.int64(-54617),
 np.int64(-56428),
 np.int64(-54935),
 np.int64(-53903),
 np.int64(-54122),
 np.int64(-49567),
 np.int64(-36717),
 np.int64(-35283),
 np.int64(-38689),
 np.int64(-36345),
 np.int64(-27438),
 np.int64(-22906),
 np.int64(-20268),
 np.int64(-18338),
 np.int64(-17077),
 np.int64(-17522),
 np.int64(-17513),
 np.int64(-16093),
 np.int64(-14514),
 np.int64(-13009),
 np.int64(-8570),
 np.int64(-7511),
 np.int64(-7626),
 np.int64(-7004),
 np.int64(-6766),
 np.int64(-6600),
 np.int64(-5803),
 np.int64(-4062),
 np.int64(-3854),
 np.int64(-4189),
 np.int64(-4419),
 np.int64(-4538),
 np.int64(-4164),
 np.int64(-4383),
 np.int64(-3092),
 np.int64(-3005),
 np.int64(-3371),
 np.int64(-3507),
 np.int64(-3713),
 np.int64(-4122),
 np.int64(-4441),
 np.int64(-3021),
 np.int64(-3125),
 np.int64(-3831),
 np.int64(-4415),
 np.int64(-4873),
 np.int64(-5034),
 np.int64(-5407),
 np.int64(-3864),
 np.int64(-4203),
 np.int64(-5413),
 np.int64(-5840),
 np.int64(-6233),
 np.int64(-6914),
 np.int64(-7452),
 np.int64(-5192),
 np.int64(-5316),
 np.int64(-6233),
 np.int64(-7310),
 np.int64(-7434),
 np.int64(-7619),
 np.int64(-7849),
 np.int64(-5567),
 np.int64(-5816),
 np.int64(-6681),
 np.int64(-6977),
 np.int64(-6748),
 np.int64(-7375),
 np.int64(-7173),
 np.int64(-4953),
 np.int64(-4324),
 np.int64(-5125),
 np.int64(-5352),
 np.int64(-4944),
 np.int64(-5263),
 np.int64(-5122),
 np.int64(-3031),
 np.int64(-3307),
 np.int64(-3925),
 np.int64(-4067),
 np.int64(-3896),
 np.int64(-3937),
 np.int64(-4113),
 np.int64(-2697),
 np.int64(-2827),
 np.int64(-3120),
 np.int64(-3205),
 np.int64(-3033),
 np.int64(-3292),
 np.int64(-3189),
 np.int64(-2122),
 np.int64(-2004),
 np.int64(-2418),
 np.int64(-2324),
 np.int64(-2368),
 np.int64(-2518),
 np.int64(-2425),
 np.int64(-1717),
 np.int64(-1754),
 np.int64(-2225),
 np.int64(-2246),
 np.int64(-2343),
 np.int64(-2482),
 np.int64(-2667),
 np.int64(-1588),
 np.int64(-1685),
 np.int64(-2061),
 np.int64(-2104),
 np.int64(-2121),
 np.int64(-2111),
 np.int64(-1945),
 np.int64(-1272),
 np.int64(-1190),
 np.int64(-1421),
 np.int64(-1508),
 np.int64(-1438),
 np.int64(-1441),
 np.int64(-1571),
 np.int64(-1073),
 np.int64(-1050),
 np.int64(-1420),
 np.int64(-1617),
 np.int64(-1683),
 np.int64(-1939),
 np.int64(-1583),
 np.int64(-1346),
 np.int64(-1297),
 np.int64(-1594),
 np.int64(-1953),
 np.int64(-2171),
 np.int64(-2425),
 np.int64(-2027),
 np.int64(-1574),
 np.int64(-1670),
 np.int64(-2085),
 np.int64(-2247),
 np.int64(-2484),
 np.int64(-2561),
 np.int64(-2881),
 np.int64(-2288),
 np.int64(-2381),
 np.int64(-2768),
 np.int64(-3270),
 np.int64(-2429),
 np.int64(-1715),
 np.int64(-1720),
 np.int64(-1729),
 np.int64(-1604),
 np.int64(-1909),
 np.int64(-2087),
 np.int64(-2008),
 np.int64(-1942),
 np.int64(-2065),
 np.int64(-1508),
 np.int64(-1433),
 np.int64(-1755),
 np.int64(-1864),
 np.int64(-1893),
 np.int64(-2049),
 np.int64(-2047),
 np.int64(-1597),
 np.int64(-1375),
 np.int64(-1490),
 np.int64(-1803),
 np.int64(-1708),
 np.int64(-1960),
 np.int64(-2024),
 np.int64(-1370),
 np.int64(-1485),
 np.int64(-1619),
 np.int64(-1791),
 np.int64(-1837),
 np.int64(-1882),
 np.int64(-2154),
 np.int64(-1507),
 np.int64(-1417),
 np.int64(-1626),
 np.int64(-1787),
 np.int64(-2140),
 np.int64(-2152),
 np.int64(-1803),
 np.int64(-1372),
 np.int64(-1554),
 np.int64(-1816),
 np.int64(-1928),
 np.int64(-1989),
 np.int64(-1987),
 np.int64(-2221),
 np.int64(-1537),
 np.int64(-1491),
 np.int64(-1727),
 np.int64(-1823),
 np.int64(-1704),
 np.int64(-1775),
 np.int64(-1725),
 np.int64(-1200),
 np.int64(-1218),
 np.int64(-1442),
 np.int64(-1538),
 np.int64(-1710),
 np.int64(-1673),
 np.int64(-1895),
 np.int64(-1363),
 np.int64(-1318),
 np.int64(-1487),
 np.int64(-1627),
 np.int64(-1629),
 np.int64(-1841),
 np.int64(-1781),
 np.int64(-1278),
 np.int64(-1251),
 np.int64(-1453),
 np.int64(-1449),
 np.int64(-1535),
 np.int64(-1599),
 np.int64(-1613),
 np.int64(-1150),
 np.int64(-1100),
 np.int64(-1324),
 np.int64(-1378),
 np.int64(-1316),
 np.int64(-1275),
 np.int64(-1211),
 np.int64(-746),
 np.int64(-711),
 np.int64(-743),
 np.int64(-794),
 np.int64(-825),
 np.int64(-761),
 np.int64(-794),
 np.int64(-595),
 np.int64(-501),
 np.int64(-614),
 np.int64(-668),
 np.int64(-634),
 np.int64(-610),
 np.int64(-645),
 np.int64(-394),
 np.int64(-357),
 np.int64(-429),
 np.int64(-482),
 np.int64(-507),
 np.int64(-540),
 np.int64(-545),
 np.int64(-373),
 np.int64(-399),
 np.int64(-452),
 np.int64(-565),
 np.int64(-556),
 np.int64(-610),
 np.int64(-602),
 np.int64(-454),
 np.int64(-485),
 np.int64(-556),
 np.int64(-744),
 np.int64(-695),
 np.int64(-681),
 np.int64(-677),
 np.int64(-889),
 np.int64(430),
 np.int64(-910),
 np.int64(-533),
 np.int64(-587),
 np.int64(-629),
 np.int64(-705),
 np.int64(-516),
 np.int64(-530),
 np.int64(-585),
 np.int64(-666),
 np.int64(-561),
 np.int64(-646),
 np.int64(-654),
 np.int64(-528),
 np.int64(-619),
 np.int64(-610),
 np.int64(-681),
 np.int64(-747),
 np.int64(-715),
 np.int64(-634),
 np.int64(-510),
 np.int64(-463),
 np.int64(-564),
 np.int64(-701),
 np.int64(-525),
 np.int64(-574),
 np.int64(-676),
 np.int64(-541),
 np.int64(-488),
 np.int64(-606),
 np.int64(-627),
 np.int64(-661),
 np.int64(-679),
 np.int64(-769),
 np.int64(-512),
 np.int64(-499),
 np.int64(-644),
 np.int64(-785),
 np.int64(-797),
 np.int64(-735),
 np.int64(-731),
 np.int64(-549),
 np.int64(-532),
 np.int64(-671),
 np.int64(-658),
 np.int64(-673),
 np.int64(-698),
 np.int64(-731),
 np.int64(-542),
 np.int64(-587),
 np.int64(-614),
 np.int64(-677),
 np.int64(-671),
 np.int64(-700),
 np.int64(-668),
 np.int64(-477),
 np.int64(-473),
 np.int64(-543),
 np.int64(-543),
 np.int64(-557),
 np.int64(-551),
 np.int64(-506),
 np.int64(-447),
 np.int64(-382),
 np.int64(-482),
 np.int64(-505),
 np.int64(-489),
 np.int64(-430),
 np.int64(-428),
 np.int64(-346),
 np.int64(-415),
 np.int64(-456),
 np.int64(-447),
 np.int64(-463),
 np.int64(-445),
 np.int64(-469),
 np.int64(-363),
 np.int64(-379),
 np.int64(-459),
 np.int64(-490),
 np.int64(-488),
 np.int64(-465),
 np.int64(-470),
 np.int64(-446),
 np.int64(-346),
 np.int64(-416),
 np.int64(-418),
 np.int64(-398),
 np.int64(-424),
 np.int64(-444),
 np.int64(-344),
 np.int64(-355),
 np.int64(-355),
 np.int64(-415),
 np.int64(-387),
 np.int64(-395),
 np.int64(-440),
 np.int64(-356),
 np.int64(-332),
 np.int64(-416),
 np.int64(-448),
 np.int64(-561),
 np.int64(-621),
 np.int64(-621),
 np.int64(-457),
 np.int64(-343),
 np.int64(-326),
 np.int64(-362),
 np.int64(-403),
 np.int64(-504),
 np.int64(-444),
 np.int64(-303),
 np.int64(-288),
 np.int64(-371),
 np.int64(-390),
 np.int64(-370),
 np.int64(-451),
 np.int64(-467),
 np.int64(-336),
 np.int64(-305),
 np.int64(-354),
 np.int64(-456),
 np.int64(-469),
 np.int64(-497),
 np.int64(-559),
 np.int64(-349),
 np.int64(-437),
 np.int64(-392),
 np.int64(-431),
 np.int64(-346),
 np.int64(-400),
 np.int64(-404),
 np.int64(-386),
 np.int64(-389),
 np.int64(-520),
 np.int64(-580),
 np.int64(-512),
 np.int64(-524),
 np.int64(-561),
 np.int64(-537),
 np.int64(-451),
 np.int64(-657),
 np.int64(-641),
 np.int64(-674),
 np.int64(-869),
 np.int64(-838),
 np.int64(-714),
 np.int64(-1020),
 np.int64(-657),
 np.int64(-820),
 np.int64(-1027),
 np.int64(-967),
 np.int64(-1050),
 np.int64(-1044),
 np.int64(-806),
 np.int64(-970),
 np.int64(-1131),
 np.int64(-1240),
 np.int64(-985),
 np.int64(-1090),
 np.int64(-866),
 np.int64(-924),
 np.int64(-1096),
 np.int64(-1045),
 np.int64(-1064),
 np.int64(-1014),
 np.int64(-1078),
 np.int64(-880),
 np.int64(-718),
 np.int64(-1030),
 np.int64(-950),
 np.int64(-689),
 np.int64(-680),
 np.int64(-670),
 np.int64(-587),
 np.int64(-615),
 np.int64(-631),
 np.int64(-577),
 np.int64(-628),
 np.int64(-540),
 np.int64(-511),
 np.int64(-451),
 np.int64(-438),
 np.int64(-450),
 np.int64(-503),
 np.int64(-555),
 np.int64(-581),
 np.int64(-382),
 np.int64(-349),
 np.int64(-271),
 np.int64(-330),
 np.int64(-386),
 np.int64(-348),
 np.int64(-325),
 np.int64(-285),
 np.int64(-230),
 np.int64(-222),
 np.int64(-208),
 np.int64(-205),
 np.int64(-191),
 np.int64(-143),
 np.int64(-145),
 np.int64(-100),
 np.int64(-126),
 np.int64(-143),
 np.int64(-89),
 np.int64(-145),
 np.int64(-125),
 np.int64(-117),
 np.int64(-75),
 np.int64(-97),
 np.int64(-124),
 np.int64(-127),
 np.int64(-113),
 np.int64(-125),
 np.int64(-103),
 np.int64(-88),
 np.int64(-119),
 np.int64(-61),
 np.int64(-77),
 np.int64(-155),
 np.int64(-121),
 np.int64(-89),
 np.int64(-58),
 np.int64(-76),
 np.int64(-91),
 np.int64(-73),
 np.int64(-47),
 np.int64(-110),
 np.int64(-84),
 np.int64(-91),
 np.int64(-98),
 np.int64(-58),
 np.int64(-72),
 np.int64(-54),
 np.int64(-69),
 np.int64(-114),
 np.int64(-75),
 np.int64(-73),
 np.int64(-64),
 np.int64(-75),
 np.int64(-63),
 np.int64(-77),
 np.int64(-113),
 np.int64(-38),
 np.int64(-50),
 np.int64(-95),
 np.int64(-61),
 np.int64(-114),
 np.int64(-125),
 np.int64(-110),
 np.int64(-61),
 np.int64(-70),
 np.int64(-82),
 np.int64(-110),
 np.int64(-126),
 np.int64(-153),
 np.int64(-113),
 np.int64(-106),
 np.int64(-109),
 np.int64(-121),
 np.int64(-136),
 np.int64(-176),
 np.int64(-155),
 np.int64(-156),
 np.int64(-136),
 np.int64(-119),
 np.int64(-167),
 np.int64(-168),
 np.int64(-198),
 np.int64(-195),
 np.int64(-267),
 np.int64(-235),
 np.int64(-248),
 np.int64(-299),
 np.int64(-323),
 np.int64(-371),
 np.int64(-441),
 np.int64(-320),
 np.int64(-280),
 np.int64(-266),
 np.int64(-396),
 np.int64(-332),
 np.int64(-324),
 np.int64(-288),
 np.int64(-297),
 np.int64(-246),
 np.int64(-197),
 np.int64(-279),
 np.int64(-166),
 np.int64(-103),
 np.int64(-56),
 np.int64(-54),
 np.int64(-34),
 np.int64(-28),
 np.int64(-36),
 np.int64(-43),
 np.int64(-20),
 np.int64(-43),
 np.int64(-33),
 np.int64(-34),
 np.int64(-23),
 np.int64(-30),
 np.int64(-31),
 np.int64(-36),
 np.int64(-18),
 np.int64(-48),
 np.int64(-28),
 np.int64(-25),
 np.int64(-58),
 np.int64(-113),
 np.int64(-41),
 np.int64(-59),
 np.int64(-63),
 np.int64(-45),
 np.int64(-26),
 np.int64(-34),
 np.int64(-39),
 np.int64(-60),
 np.int64(-61),
 np.int64(-39),
 np.int64(-33),
 np.int64(-62),
 np.int64(-44),
 np.int64(-35),
 np.int64(-45),
 np.int64(-50),
 np.int64(-62),
 np.int64(-44),
 np.int64(-48),
 np.int64(-61),
 np.int64(-63),
 np.int64(-61),
 np.int64(-54),
 np.int64(-51),
 np.int64(-42),
 np.int64(-42),
 np.int64(-62),
 np.int64(-51),
 np.int64(-39),
 np.int64(-28),
 np.int64(-51),
 np.int64(-46),
 np.int64(-17),
 np.int64(-48),
 np.int64(-67),
 np.int64(-49),
 np.int64(-59),
 np.int64(-43),
 np.int64(-34),
 np.int64(-37),
 np.int64(-34),
 np.int64(-48),
 np.int64(-56),
 np.int64(-45),
 np.int64(-50),
 np.int64(-38),
 np.int64(-37),
 np.int64(-57),
 np.int64(-51),
 np.int64(-39),
 np.int64(-39),
 np.int64(-49),
 np.int64(-38),
 np.int64(-35),
 np.int64(-27),
 np.int64(-39),
 np.int64(-58),
 np.int64(-79),
 np.int64(-40),
 np.int64(-19),
 np.int64(-16),
 np.int64(-25),
 np.int64(-23),
 np.int64(-20),
 np.int64(-12),
 np.int64(-32),
 np.int64(-13),
 np.int64(-15),
 np.int64(-13),
 np.int64(-19),
 np.int64(-56),
 np.int64(-26),
 np.int64(-27),
 np.int64(-35),
 np.int64(-34),
 np.int64(-18),
 np.int64(-12),
 np.int64(-4),
 np.int64(-2),
 np.int64(-3),
 np.int64(-8),
 np.int64(-13),
 np.int64(-6),
 np.int64(-9),
 np.int64(-4),
 np.int64(-9),
 np.int64(-14),
 np.int64(-10),
 np.int64(-10),
 np.int64(-10),
 np.int64(-6),
 np.int64(-8),
 np.int64(-11),
 np.int64(-9),
 np.int64(-13),
 np.int64(-8),
 np.int64(-18),
 np.int64(-22),
 np.int64(-22),
 np.int64(-27),
 np.int64(-27),
 np.int64(-25),
 np.int64(-32),
 np.int64(-30),
 np.int64(-27),
 np.int64(-39),
 np.int64(-53),
 np.int64(-47),
 np.int64(-47),
 np.int64(-81),
 np.int64(-94),
 np.int64(-86),
 np.int64(-89),
 np.int64(-101),
 np.int64(-125),
 np.int64(-78),
 np.int64(-105),
 np.int64(-146),
 np.int64(-91),
 np.int64(-104),
 np.int64(-100),
 np.int64(-76),
 np.int64(-64),
 np.int64(-98),
 np.int64(-147),
 np.int64(-87),
 np.int64(-152),
 np.int64(-93),
 np.int64(-84),
 np.int64(-74),
 np.int64(-76),
 np.int64(-107),
 np.int64(-110),
 np.int64(-114),
 np.int64(-242)]

In [74]:
new_list2

[np.int64(-13358),
 np.int64(-6172),
 np.int64(-5022),
 np.int64(-9834),
 np.int64(-12039),
 np.int64(-12539),
 np.int64(-9891),
 np.int64(-15768),
 np.int64(-17185),
 np.int64(-6135),
 np.int64(-12647),
 np.int64(-14374),
 np.int64(-16572),
 np.int64(-18805),
 np.int64(-23936),
 np.int64(-26331),
 np.int64(-9971),
 np.int64(-19289),
 np.int64(-23450),
 np.int64(-25113),
 np.int64(-28109),
 np.int64(-31333),
 np.int64(-35085),
 np.int64(-13290),
 np.int64(-25425),
 np.int64(-29572),
 np.int64(-32435),
 np.int64(-35882),
 np.int64(-43881),
 np.int64(-49896),
 np.int64(-20588),
 np.int64(-40048),
 np.int64(-39563),
 np.int64(-26678),
 np.int64(-42279),
 np.int64(-49046),
 np.int64(-51106),
 np.int64(-20076),
 np.int64(-37760),
 np.int64(-43244),
 np.int64(-50556),
 np.int64(-57446),
 np.int64(-76764),
 np.int64(-80267),
 np.int64(-34361),
 np.int64(-64704),
 np.int64(-75423),
 np.int64(-81033),
 np.int64(-90843),
 np.int64(-111289),
 np.int64(-118462),
 np.int64(-47730),
 np.int64(-92978),
 np.int64(-107882),
 np.int64(-125800),
 np.int64(-148409),
 np.int64(-195382),
 np.int64(-210715),
 np.int64(-90917),
 np.int64(-164456),
 np.int64(-185525),
 np.int64(-205299),
 np.int64(-224784),
 np.int64(-286247),
 np.int64(-266085),
 np.int64(-127163),
 np.int64(-234265),
 np.int64(-264120),
 np.int64(-280231),
 np.int64(-320683),
 np.int64(-424466),
 np.int64(-347500),
 np.int64(-187182),
 np.int64(-318075),
 np.int64(-335541),
 np.int64(-339451),
 np.int64(-395526),
 np.int64(-490771),
 np.int64(-353828),
 np.int64(-209139),
 np.int64(-334653),
 np.int64(-381413),
 np.int64(-406839),
 np.int64(-621204),
 np.int64(-400593),
 np.int64(-362283),
 np.int64(-309779),
 np.int64(-350182),
 np.int64(-383617),
 np.int64(-282973),
 np.int64(-327538),
 np.int64(-342429),
 np.int64(-202702),
 np.int64(-210709),
 np.int64(-243625),
 np.int64(-254327),
 np.int64(-266850),
 np.int64(-198800),
 np.int64(-219228),
 np.int64(-138990),
 np.int64(-139624),
 np.int64(-163561),
 np.int64(-166182),
 np.int64(-165887),
 np.int64(-170015),
 np.int64(-171442),
 np.int64(-99569),
 np.int64(-95339),
 np.int64(-104814),
 np.int64(-102210),
 np.int64(-109823),
 np.int64(-93132),
 np.int64(-90435),
 np.int64(-57164),
 np.int64(-54617),
 np.int64(-56428),
 np.int64(-54935),
 np.int64(-53903),
 np.int64(-54122),
 np.int64(-49567),
 np.int64(-36717),
 np.int64(-35283),
 np.int64(-38689),
 np.int64(-36345),
 np.int64(-27438),
 np.int64(-22906),
 np.int64(-20268),
 np.int64(-18338),
 np.int64(-17077),
 np.int64(-17522),
 np.int64(-17513),
 np.int64(-16093),
 np.int64(-14514),
 np.int64(-13009),
 np.int64(-8570),
 np.int64(-7511),
 np.int64(-7626),
 np.int64(-7004),
 np.int64(-6766),
 np.int64(-6600),
 np.int64(-5803),
 np.int64(-4062),
 np.int64(-3854),
 np.int64(-4189),
 np.int64(-4419),
 np.int64(-4538),
 np.int64(-4164),
 np.int64(-4383),
 np.int64(-3092),
 np.int64(-3005),
 np.int64(-3371),
 np.int64(-3507),
 np.int64(-3713),
 np.int64(-4122),
 np.int64(-4441),
 np.int64(-3021),
 np.int64(-3125),
 np.int64(-3831),
 np.int64(-4415),
 np.int64(-4873),
 np.int64(-5034),
 np.int64(-5407),
 np.int64(-3864),
 np.int64(-4203),
 np.int64(-5413),
 np.int64(-5840),
 np.int64(-6233),
 np.int64(-6914),
 np.int64(-7452),
 np.int64(-5192),
 np.int64(-5316),
 np.int64(-6233),
 np.int64(-7310),
 np.int64(-7434),
 np.int64(-7619),
 np.int64(-7849),
 np.int64(-5567),
 np.int64(-5816),
 np.int64(-6681),
 np.int64(-6977),
 np.int64(-6748),
 np.int64(-7375),
 np.int64(-7173),
 np.int64(-4953),
 np.int64(-4324),
 np.int64(-5125),
 np.int64(-5352),
 np.int64(-4944),
 np.int64(-5263),
 np.int64(-5122),
 np.int64(-3031),
 np.int64(-3307),
 np.int64(-3925),
 np.int64(-4067),
 np.int64(-3896),
 np.int64(-3937),
 np.int64(-4113),
 np.int64(-2697),
 np.int64(-2827),
 np.int64(-3120),
 np.int64(-3205),
 np.int64(-3033),
 np.int64(-3292),
 np.int64(-3189),
 np.int64(-2122),
 np.int64(-2004),
 np.int64(-2418),
 np.int64(-2324),
 np.int64(-2368),
 np.int64(-2518),
 np.int64(-2425),
 np.int64(-1717),
 np.int64(-1754),
 np.int64(-2225),
 np.int64(-2246),
 np.int64(-2343),
 np.int64(-2482),
 np.int64(-2667),
 np.int64(-1588),
 np.int64(-1685),
 np.int64(-2061),
 np.int64(-2104),
 np.int64(-2121),
 np.int64(-2111),
 np.int64(-1945),
 np.int64(-1272),
 np.int64(-1190),
 np.int64(-1421),
 np.int64(-1508),
 np.int64(-1438),
 np.int64(-1441),
 np.int64(-1571),
 np.int64(-1073),
 np.int64(-1050),
 np.int64(-1420),
 np.int64(-1617),
 np.int64(-1683),
 np.int64(-1939),
 np.int64(-1583),
 np.int64(-1346),
 np.int64(-1297),
 np.int64(-1594),
 np.int64(-1953),
 np.int64(-2171),
 np.int64(-2425),
 np.int64(-2027),
 np.int64(-1574),
 np.int64(-1670),
 np.int64(-2085),
 np.int64(-2247),
 np.int64(-2484),
 np.int64(-2561),
 np.int64(-2881),
 np.int64(-2288),
 np.int64(-2381),
 np.int64(-2768),
 np.int64(-3270),
 np.int64(-2429),
 np.int64(-1715),
 np.int64(-1720),
 np.int64(-1729),
 np.int64(-1604),
 np.int64(-1909),
 np.int64(-2087),
 np.int64(-2008),
 np.int64(-1942),
 np.int64(-2065),
 np.int64(-1508),
 np.int64(-1433),
 np.int64(-1755),
 np.int64(-1864),
 np.int64(-1893),
 np.int64(-2049),
 np.int64(-2047),
 np.int64(-1597),
 np.int64(-1375),
 np.int64(-1490),
 np.int64(-1803),
 np.int64(-1708),
 np.int64(-1960),
 np.int64(-2024),
 np.int64(-1370),
 np.int64(-1485),
 np.int64(-1619),
 np.int64(-1791),
 np.int64(-1837),
 np.int64(-1882),
 np.int64(-2154),
 np.int64(-1507),
 np.int64(-1417),
 np.int64(-1626),
 np.int64(-1787),
 np.int64(-2140),
 np.int64(-2152),
 np.int64(-1803),
 np.int64(-1372),
 np.int64(-1554),
 np.int64(-1816),
 np.int64(-1928),
 np.int64(-1989),
 np.int64(-1987),
 np.int64(-2221),
 np.int64(-1537),
 np.int64(-1491),
 np.int64(-1727),
 np.int64(-1823),
 np.int64(-1704),
 np.int64(-1775),
 np.int64(-1725),
 np.int64(-1200),
 np.int64(-1218),
 np.int64(-1442),
 np.int64(-1538),
 np.int64(-1710),
 np.int64(-1673),
 np.int64(-1895),
 np.int64(-1363),
 np.int64(-1318),
 np.int64(-1487),
 np.int64(-1627),
 np.int64(-1629),
 np.int64(-1841),
 np.int64(-1781),
 np.int64(-1278),
 np.int64(-1251),
 np.int64(-1453),
 np.int64(-1449),
 np.int64(-1535),
 np.int64(-1599),
 np.int64(-1613),
 np.int64(-1150),
 np.int64(-1100),
 np.int64(-1324),
 np.int64(-1378),
 np.int64(-1316),
 np.int64(-1275),
 np.int64(-1211),
 np.int64(-746),
 np.int64(-711),
 np.int64(-743),
 np.int64(-794),
 np.int64(-825),
 np.int64(-761),
 np.int64(-794),
 np.int64(-595),
 np.int64(-501),
 np.int64(-614),
 np.int64(-668),
 np.int64(-634),
 np.int64(-610),
 np.int64(-645),
 np.int64(-394),
 np.int64(-357),
 np.int64(-429),
 np.int64(-482),
 np.int64(-507),
 np.int64(-540),
 np.int64(-545),
 np.int64(-373),
 np.int64(-399),
 np.int64(-452),
 np.int64(-565),
 np.int64(-556),
 np.int64(-610),
 np.int64(-602),
 np.int64(-454),
 np.int64(-485),
 np.int64(-556),
 np.int64(-744),
 np.int64(-695),
 np.int64(-681),
 np.int64(-677),
 np.int64(-889),
 np.int64(430),
 np.int64(-910),
 np.int64(-533),
 np.int64(-587),
 np.int64(-629),
 np.int64(-705),
 np.int64(-516),
 np.int64(-530),
 np.int64(-585),
 np.int64(-666),
 np.int64(-561),
 np.int64(-646),
 np.int64(-654),
 np.int64(-528),
 np.int64(-619),
 np.int64(-610),
 np.int64(-681),
 np.int64(-747),
 np.int64(-715),
 np.int64(-634),
 np.int64(-510),
 np.int64(-463),
 np.int64(-564),
 np.int64(-701),
 np.int64(-525),
 np.int64(-574),
 np.int64(-676),
 np.int64(-541),
 np.int64(-488),
 np.int64(-606),
 np.int64(-627),
 np.int64(-661),
 np.int64(-679),
 np.int64(-769),
 np.int64(-512),
 np.int64(-499),
 np.int64(-644),
 np.int64(-785),
 np.int64(-797),
 np.int64(-735),
 np.int64(-731),
 np.int64(-549),
 np.int64(-532),
 np.int64(-671),
 np.int64(-658),
 np.int64(-673),
 np.int64(-698),
 np.int64(-731),
 np.int64(-542),
 np.int64(-587),
 np.int64(-614),
 np.int64(-677),
 np.int64(-671),
 np.int64(-700),
 np.int64(-668),
 np.int64(-477),
 np.int64(-473),
 np.int64(-543),
 np.int64(-543),
 np.int64(-557),
 np.int64(-551),
 np.int64(-506),
 np.int64(-447),
 np.int64(-382),
 np.int64(-482),
 np.int64(-505),
 np.int64(-489),
 np.int64(-430),
 np.int64(-428),
 np.int64(-346),
 np.int64(-415),
 np.int64(-456),
 np.int64(-447),
 np.int64(-463),
 np.int64(-445),
 np.int64(-469),
 np.int64(-363),
 np.int64(-379),
 np.int64(-459),
 np.int64(-490),
 np.int64(-488),
 np.int64(-465),
 np.int64(-470),
 np.int64(-446),
 np.int64(-346),
 np.int64(-416),
 np.int64(-418),
 np.int64(-398),
 np.int64(-424),
 np.int64(-444),
 np.int64(-344),
 np.int64(-355),
 np.int64(-355),
 np.int64(-415),
 np.int64(-387),
 np.int64(-395),
 np.int64(-440),
 np.int64(-356),
 np.int64(-332),
 np.int64(-416),
 np.int64(-448),
 np.int64(-561),
 np.int64(-621),
 np.int64(-621),
 np.int64(-457),
 np.int64(-343),
 np.int64(-326),
 np.int64(-362),
 np.int64(-403),
 np.int64(-504),
 np.int64(-444),
 np.int64(-303),
 np.int64(-288),
 np.int64(-371),
 np.int64(-390),
 np.int64(-370),
 np.int64(-451),
 np.int64(-467),
 np.int64(-336),
 np.int64(-305),
 np.int64(-354),
 np.int64(-456),
 np.int64(-469),
 np.int64(-497),
 np.int64(-559),
 np.int64(-349),
 np.int64(-437),
 np.int64(-392),
 np.int64(-431),
 np.int64(-346),
 np.int64(-400),
 np.int64(-404),
 np.int64(-386),
 np.int64(-389),
 np.int64(-520),
 np.int64(-580),
 np.int64(-512),
 np.int64(-524),
 np.int64(-561),
 np.int64(-537),
 np.int64(-451),
 np.int64(-657),
 np.int64(-641),
 np.int64(-674),
 np.int64(-869),
 np.int64(-838),
 np.int64(-714),
 np.int64(-1020),
 np.int64(-657),
 np.int64(-820),
 np.int64(-1027),
 np.int64(-967),
 np.int64(-1050),
 np.int64(-1044),
 np.int64(-806),
 np.int64(-970),
 np.int64(-1131),
 np.int64(-1240),
 np.int64(-985),
 np.int64(-1090),
 np.int64(-866),
 np.int64(-924),
 np.int64(-1096),
 np.int64(-1045),
 np.int64(-1064),
 np.int64(-1014),
 np.int64(-1078),
 np.int64(-880),
 np.int64(-718),
 np.int64(-1030),
 np.int64(-950),
 np.int64(-689),
 np.int64(-680),
 np.int64(-670),
 np.int64(-587),
 np.int64(-615),
 np.int64(-631),
 np.int64(-577),
 np.int64(-628),
 np.int64(-540),
 np.int64(-511),
 np.int64(-451),
 np.int64(-438),
 np.int64(-450),
 np.int64(-503),
 np.int64(-555),
 np.int64(-581),
 np.int64(-382),
 np.int64(-349),
 np.int64(-271),
 np.int64(-330),
 np.int64(-386),
 np.int64(-348),
 np.int64(-325),
 np.int64(-285),
 np.int64(-230),
 np.int64(-222),
 np.int64(-208),
 np.int64(-205),
 np.int64(-191),
 np.int64(-143),
 np.int64(-145),
 np.int64(-100),
 np.int64(-126),
 np.int64(-143),
 np.int64(-89),
 np.int64(-145),
 np.int64(-125),
 np.int64(-117),
 np.int64(-75),
 np.int64(-97),
 np.int64(-124),
 np.int64(-127),
 np.int64(-113),
 np.int64(-125),
 np.int64(-103),
 np.int64(-88),
 np.int64(-119),
 np.int64(-61),
 np.int64(-77),
 np.int64(-155),
 np.int64(-121),
 np.int64(-89),
 np.int64(-58),
 np.int64(-76),
 np.int64(-91),
 np.int64(-73),
 np.int64(-47),
 np.int64(-110),
 np.int64(-84),
 np.int64(-91),
 np.int64(-98),
 np.int64(-58),
 np.int64(-72),
 np.int64(-54),
 np.int64(-69),
 np.int64(-114),
 np.int64(-75),
 np.int64(-73),
 np.int64(-64),
 np.int64(-75),
 np.int64(-63),
 np.int64(-77),
 np.int64(-113),
 np.int64(-38),
 np.int64(-50),
 np.int64(-95),
 np.int64(-61),
 np.int64(-114),
 np.int64(-125),
 np.int64(-110),
 np.int64(-61),
 np.int64(-70),
 np.int64(-82),
 np.int64(-110),
 np.int64(-126),
 np.int64(-153),
 np.int64(-113),
 np.int64(-106),
 np.int64(-109),
 np.int64(-121),
 np.int64(-136),
 np.int64(-176),
 np.int64(-155),
 np.int64(-156),
 np.int64(-136),
 np.int64(-119),
 np.int64(-167),
 np.int64(-168),
 np.int64(-198),
 np.int64(-195),
 np.int64(-267),
 np.int64(-235),
 np.int64(-248),
 np.int64(-299),
 np.int64(-323),
 np.int64(-371),
 np.int64(-441),
 np.int64(-320),
 np.int64(-280),
 np.int64(-266),
 np.int64(-396),
 np.int64(-332),
 np.int64(-324),
 np.int64(-288),
 np.int64(-297),
 np.int64(-246),
 np.int64(-197),
 np.int64(-279),
 np.int64(-166),
 np.int64(-103),
 np.int64(-56),
 np.int64(-54),
 np.int64(-34),
 np.int64(-28),
 np.int64(-36),
 np.int64(-43),
 np.int64(-20),
 np.int64(-43),
 np.int64(-33),
 np.int64(-34),
 np.int64(-23),
 np.int64(-30),
 np.int64(-31),
 np.int64(-36),
 np.int64(-18),
 np.int64(-48),
 np.int64(-28),
 np.int64(-25),
 np.int64(-58),
 np.int64(-113),
 np.int64(-41),
 np.int64(-59),
 np.int64(-63),
 np.int64(-45),
 np.int64(-26),
 np.int64(-34),
 np.int64(-39),
 np.int64(-60),
 np.int64(-61),
 np.int64(-39),
 np.int64(-33),
 np.int64(-62),
 np.int64(-44),
 np.int64(-35),
 np.int64(-45),
 np.int64(-50),
 np.int64(-62),
 np.int64(-44),
 np.int64(-48),
 np.int64(-61),
 np.int64(-63),
 np.int64(-61),
 np.int64(-54),
 np.int64(-51),
 np.int64(-42),
 np.int64(-42),
 np.int64(-62),
 np.int64(-51),
 np.int64(-39),
 np.int64(-28),
 np.int64(-51),
 np.int64(-46),
 np.int64(-17),
 np.int64(-48),
 np.int64(-67),
 np.int64(-49),
 np.int64(-59),
 np.int64(-43),
 np.int64(-34),
 np.int64(-37),
 np.int64(-34),
 np.int64(-48),
 np.int64(-56),
 np.int64(-45),
 np.int64(-50),
 np.int64(-38),
 np.int64(-37),
 np.int64(-57),
 np.int64(-51),
 np.int64(-39),
 np.int64(-39),
 np.int64(-49),
 np.int64(-38),
 np.int64(-35),
 np.int64(-27),
 np.int64(-39),
 np.int64(-58),
 np.int64(-79),
 np.int64(-40),
 np.int64(-19),
 np.int64(-16),
 np.int64(-25),
 np.int64(-23),
 np.int64(-20),
 np.int64(-12),
 np.int64(-32),
 np.int64(-13),
 np.int64(-15),
 np.int64(-13),
 np.int64(-19),
 np.int64(-56),
 np.int64(-26),
 np.int64(-27),
 np.int64(-35),
 np.int64(-34),
 np.int64(-18),
 np.int64(-12),
 np.int64(-4),
 np.int64(-2),
 np.int64(-3),
 np.int64(-8),
 np.int64(-13),
 np.int64(-6),
 np.int64(-9),
 np.int64(-4),
 np.int64(-9),
 np.int64(-14),
 np.int64(-10),
 np.int64(-10),
 np.int64(-10),
 np.int64(-6),
 np.int64(-8),
 np.int64(-11),
 np.int64(-9),
 np.int64(-13),
 np.int64(-8),
 np.int64(-18),
 np.int64(-22),
 np.int64(-22),
 np.int64(-27),
 np.int64(-27),
 np.int64(-25),
 np.int64(-32),
 np.int64(-30),
 np.int64(-27),
 np.int64(-39),
 np.int64(-53),
 np.int64(-47),
 np.int64(-47),
 np.int64(-81),
 np.int64(-94),
 np.int64(-86),
 np.int64(-89),
 np.int64(-101),
 np.int64(-125),
 np.int64(-78),
 np.int64(-105),
 np.int64(-146),
 np.int64(-91),
 np.int64(-104),
 np.int64(-100),
 np.int64(-76),
 np.int64(-64),
 np.int64(-98),
 np.int64(-147),
 np.int64(-87),
 np.int64(-152),
 np.int64(-93),
 np.int64(-84),
 np.int64(-74),
 np.int64(-76),
 np.int64(-107),
 np.int64(-110),
 np.int64(-114),
 np.int64(-242)]

In [76]:
# corona 데이터프레임에 new_list로 만들어준 일일확진자를 대입
# 데이터프레임은 dict와 비슷한 특성을 가지고 있다.
# 데이터 프레임 [new_col] = 1차원 데이터(Series,list,tuple) // 단일 데이터
# 1차원 데이터를 대입하는 경우는 데이터프레임의 인덱스와 길이가 같아야 한다.
# 단일 데이터를 대입하는 경우 -> 모든 값이 단일데이터로 고정
# corona['test']=1
# corona.head(3)
corona['일일확진자']=new_list2
corona.head()

ValueError: Length of values (819) does not match length of index (820)

In [83]:
# 인덱스 이동(shift) 함수
# shift()는 기본값은 인덱스는 1씩 이동 (아래로 한칸씩 이동)
# 1차원 데이터중 list-list는 어떻게 됐었나? --> 에러 발생
# numpy의 ndarray형태(행렬) -> 행렬 - 행렬 -> 같은 위치의 원소끼리의 차를 구해서 행렬로 결과가 만들어진다.
# pandas가 설치될때 numpy가 같이 설치됨. --> pandas에서 numpy를 사용한다는 뜻임.
# DataFrame과 Series의 values 값들은 행렬로 표시
# series - series --> 행렬의 차로 계산
# corona['총사망자'].shift(-1)
corona['일일사망자']=corona['총사망자'] - corona['총사망자'].shift().fillna(0)
# int-int -> int
# 총사망자 shift()를 이용하여 계산을 하면 결측치가 우선 발생 (해당 데이터의 타입이 float 변환)

In [85]:
corona.head()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일사망자
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,1,24305.0
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,1,-6.0
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,1,-20.0
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,1,-21.0
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,1,-20.0

In [86]:
# 같은 컬럼내에서 데이터들간의 차이를 구하는 함수
# diff(n) : n만큼 이동한 데이터와의 차이를 구하는 함수
# diif(1)의 결과는 Series-Series.shift(1) 결과와 같다.
corona['일일사망자2']=corona['총사망자'].diff(1)

In [89]:
corona.tail()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일사망자,일일사망자2
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,1,-3.0,-3.0
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,1,-5.0,-5.0
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,1,-1.0,-1.0
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,1,-6.0,-6.0
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,1,-6.0,-6.0

In [92]:
(corona['일일사망자']==corona['일일사망자2'].fillna(0)).all()
# all() -> 모든 값이 True인 경우 True -> 하나라도 False가 존재하면 False
# sum() -> 합산
# any() -> 하나라도 true이면 true -> 모든 데이터가 false라면 false

np.False_

In [94]:
corona['일일사망자2']=corona['일일사망자2'].fillna(0)

In [97]:
# 파생변수 일일확진자, 일일사망자 생성 -> 확인
# 일일확진자와 일일사망자 데이터들의 범위는? 0~xxxx -> 음수가 아니여야된다.
# 음수인 데이터가 존재하는가? (조건식)
# 일일확진자가 음수라면
corona['일일확진자'] > 0

KeyError: '일일확진자'

In [98]:
# 특정 컬럼의 범위를 찾는다? 최솟값과 최댓값 --> describe()
corona['일일확진자'].describe()

KeyError: '일일확진자'

In [99]:
corona['일일사망자'].describe()

count      820.000000
mean         0.065854
std        852.559636
min       -469.000000
25%        -20.000000
50%         -5.000000
75%         -2.000000
max      24305.000000
Name: 일일사망자, dtype: float64

In [101]:
# 음수인 데이터으이 개수를 확인
(corona['일일확진자'] < 0).sum()

KeyError: '일일확진자'

In [102]:
(corona['일일사망자']<0).sum()

np.int64(739)

In [104]:
# 음수가 왜 발생했는가? 이유를 찾아보자.
# 이유를 찾기위해 >> 해당 데이터를 확인해야함.
# 일일사망자, 일일확진자 데이터들이 음수인 모든 데이터를 확인하자.
flag=(corona[['일일사망자','일일확진자']]<0).any(axis=1)
# flag로 되어있는 데이터셋이 2차원 이상의 데이터셋
corona.loc[flag,]

KeyError: "['일일확진자'] not in index"

In [106]:
# 2021년 5월 30일 데이터에서 음수가 발생
# 2일전부터 2일후까지의 데이터를 확인
# 인덱스가 444번부터 448번까지 확인
corona.loc[444:448,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일사망자,일일사망자2
444,2021-03-21 00:00:00.000,1696,98649,20210321,00:00,2021-10-07 10:30:51.51,1,-1.0,-1.0
445,2021-03-20 00:00:00.000,1693,98193,20210320,00:00,2021-10-07 10:30:51.51,1,-3.0,-3.0
446,2021-03-19 00:00:00.000,1690,97746,20210319,00:00,2021-10-07 10:30:51.51,1,-3.0,-3.0
447,2021-03-18 00:00:00.000,1688,97283,20210318,00:00,2021-10-07 10:30:51.51,1,-2.0,-2.0
448,2021-03-17 00:00:00.000,1686,96838,20210317,00:00,2021-10-07 10:30:51.51,1,-2.0,-2.0

In [107]:
# index 445 위치의 등록일시가 잘못 입력되었다.
# 2021-05-30 00:00:00.0이 아니라 2021-05-31 00:00:00.000 변경
# 데이터프레임에서 데이터를 변경하는 방법 -> 함수를 이용해서 변경, 특정영역을 선택한 뒤 대입연산자를 이용해서 변경
# 인덱스는 445, 컬럼은 등록일시 의 데이터를 추출하여 다른 데이터로 변환
corona.loc[445,'등록일시']='2021-05-31 00:00:00.000'

In [109]:
corona.loc[444:448,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일사망자,일일사망자2
444,2021-03-21 00:00:00.000,1696,98649,20210321,00:00,2021-10-07 10:30:51.51,1,-1.0,-1.0
445,2021-05-31 00:00:00.000,1693,98193,20210320,00:00,2021-10-07 10:30:51.51,1,-3.0,-3.0
446,2021-03-19 00:00:00.000,1690,97746,20210319,00:00,2021-10-07 10:30:51.51,1,-3.0,-3.0
447,2021-03-18 00:00:00.000,1688,97283,20210318,00:00,2021-10-07 10:30:51.51,1,-2.0,-2.0
448,2021-03-17 00:00:00.000,1686,96838,20210317,00:00,2021-10-07 10:30:51.51,1,-2.0,-2.0

- 데이터 수정
    1. 등록일시를 기준으로 오름차순 정렬
    2. 인덱스는 초기화하고 기존의 인덱스는 제거
    3. '일일사망자', '일일사망자2', '일일확진자' 컬럼을 제거
    4. '일일사망자' 컬럼을 생성하여 shift() 함수를 이용하여 계산
    5. '일일확진자' 컬럼을 생성하여 diff() 함수를 이용하여 계산
    6. 새롭게 생성한 파생변수들 데이터에서 음수가 존재하는가 확인

In [150]:
import pandas as pd
corona=pd.read_csv("../csv/corona.csv")

corona_list1=corona.drop(
    ['Unnamed: 0','seq'],axis=1
)
corona_list1.columns = ['등록일시','총사망자','총확진자','기준일','기준시간','수정일시','누적의심자','누적확진율']

corona_list1.sort_values('등록일시', inplace=True)

corona_list1.reset_index(drop=True,inplace=True)

try:
    corona_list1.drop(
        ['일일사망자','일일사망자2','일일확진자'],
        axis=1, inplace=True
    )
except:
    print("아무일도 없지롱")

#corona_list1.loc[:,'등록일시':'수정일시']

corona_list1['일일사망자']=(corona_list1['총사망자']-corona_list1['총사망자'].shift(1)).fillna(0)

corona_list1['일일확진자']=corona_list1['총확진자'].diff(1).fillna(0)

flag=(corona_list1[['일일확진자','일일사망자']]<0).any(axis=1)

corona_list1[['일일확진자','일일사망자']].describe()

아무일도 없지롱

               일일확진자       일일사망자
count     820.000000  820.000000
mean    22171.569512   29.574390
std     71013.854189   68.530863
min      -430.000000   -2.000000
25%       125.000000    2.000000
50%       642.500000    5.000000
75%      2782.750000   20.000000
max    621204.000000  469.000000