In [1]:
import pandas as pd

In [2]:
# csv 폴더에 있는 uriage.cvs 파일을 로드
uriage=pd.read_csv("../csv/uriage.csv")

In [4]:
uriage.head()

      purchase_date item_name  item_price customer_name
0  2019-06-13 18:02       상품A       100.0           김가온
1  2019-07-13 13:05     상 품 S         NaN           김우찬
2  2019-05-11 19:42     상 품 a         NaN           김유찬
3  2019-02-12 23:40       상품Z      2600.0           김재현
4   2019-04-22 3:09       상품a         NaN           김강현

### 문제점
1. 데이터 정형화 문제
    - 대, 소문자 문제
        - 대문자, 소문자로 통일
        - 문자열 함수 중 : upper(), lower(), titlee()
    - 문자 사이의 공백 문제
        - 문자열의 모든 공백을 제거 
        - 문자열 시작과 끝의 공백을 제거하는 함수 -> strip(), lstrip(), rstrip()
            - 이 데이터에서는 사용이 불가능 (문자 사이의 공백은 제거가 되지 않음)
        - 문자를 치환하는 함수 -> replace(' ','') (문자에서 모든 공백을 빈 텍스트로 치환)
2. 결측치가 존재
    - 결측치의 데이터의 개수 확인
    - 결측치를 다른 데이터로 채워준다.
    - item_price의 타입을 정수형으로 변환

In [6]:
# 데이터 로드 -> 정보 확인
uriage.info()

<class 'pandas.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   purchase_date  2999 non-null   str
 1   item_name      2999 non-null   str
 2   item_price     2612 non-null   float64
 3   customer_name  2999 non-null   str
dtypes: float64(1), str(3)
memory usage: 93.8 KB

In [8]:
# 결측치의 개수를 확인
uriage.isna().sum()

purchase_date      0
item_name          0
item_price       387
customer_name      0
dtype: int64

In [10]:
# item_name -> 대문자, 소문자 하나로 통일 -> 문자열 사이의 공백 제거 
uriage['item_name'].str.replace(' ','')
# replace() : 특정 데이터를 다른 데이터로 치환
    # str.replace() : 기준이되는 텍스트는 문자 하나하나씩 
    # Series.replace() : 기준이 되는 텍스트는 value 하나하나씩
    # Series에서 문자열과 같이 replace()를 사용하고싶다면? -> Series.str.replace() -> 문자열 replace() 함수 방식으로 호출

0       상품A
1       상품S
2       상품a
3       상품Z
4       상품a
       ...
2994    상품Y
2995    상품M
2996    상품Q
2997    상품H
2998    상품D
Name: item_name, Length: 2999, dtype: str

In [11]:
# 반복문 -> 문자열의 공백을 제거
df = uriage.copy()

In [17]:
# 반복 횟수는? -> df의 인덱스의 크기만큼(len(df))
# 반복하면서 item_name을 추출해서 공백을 제거
new_list=[]
for i in range(len(df)):
# # for i in df.index: 라고써야 df.loc[i,'item_name'] 돌아감.
#     # i -> 인덱스 0~2998 -> df의 인덱스는 자동생성된 인덱스이기 때문에 위치(iloc)로도 사용이 가능, 값(loc)으로도 사용이 가능
#     # print(df.loc[i,'item_name'])
#     print(df.iloc[i,1])
#     if i==3:
#         break
    result = df.iloc[i,1].replace(' ','')
    new_list.append(result)

new_list

['상품A',
 '상품S',
 '상품a',
 '상품Z',
 '상품a',
 '상품S',
 '상품a',
 '상품V',
 '상품O',
 '상품A',
 '상품U',
 '상품L',
 '상품V',
 '상품O',
 '상품A',
 '상품C',
 '상품V',
 '상품I',
 '상품r',
 '상품X',
 '상품O',
 '상품g',
 '상품X',
 '상품R',
 '상품P',
 '상품Q',
 '상품y',
 '상품P',
 '상품P',
 '상품R',
 '상품P',
 '상품A',
 '상품N',
 '상품R',
 '상품W',
 '상품A',
 '상품E',
 '상품K',
 '상품O',
 '상품W',
 '상품O',
 '상품K',
 '상품B',
 '상품F',
 '상품P',
 '상품X',
 '상품B',
 '상품s',
 '상품F',
 '상품X',
 '상품W',
 '상품n',
 '상품Q',
 '상품P',
 '상품I',
 '상품F',
 '상품D',
 '상품R',
 '상품M',
 '상품M',
 '상품Q',
 '상품A',
 '상품Y',
 '상품I',
 '상품U',
 '상품H',
 '상품P',
 '상품P',
 '상품T',
 '상품Y',
 '상품W',
 '상품M',
 '상품V',
 '상품D',
 '상품J',
 '상품O',
 '상품L',
 '상품F',
 '상품U',
 '상품N',
 '상품P',
 '상품S',
 '상품X',
 '상품O',
 '상품V',
 '상품K',
 '상품N',
 '상품I',
 '상품O',
 '상품R',
 '상품V',
 '상품Y',
 '상품E',
 '상품E',
 '상품H',
 '상품S',
 '상품W',
 '상품Y',
 '상품O',
 '상품F',
 '상품K',
 '상품B',
 '상품W',
 '상품Q',
 '상품Q',
 '상품N',
 '상품S',
 '상품M',
 '상품I',
 '상품T',
 '상품I',
 '상품H',
 '상품Y',
 '상품R',
 '상품C',
 '상품V',
 '상품T',
 '상품A',
 '상품T',
 '상품Q',
 '상품P',
 '상품W',
 '상품I',
 '상품T',
 '상품G',
 '상품N',
 '상품U',
 '상품S',
 '상품U',
 '상품M',
 '상품A',
 '상품P',
 '상품U',
 '상품X',
 '상품I',
 '상품U',
 '상품X',
 '상품L',
 '상품F',
 '상품G',
 '상품D',
 '상품X',
 '상품U',
 '상품N',
 '상품C',
 '상품W',
 '상품S',
 '상품U',
 '상품K',
 '상품G',
 '상품Q',
 '상품I',
 '상품L',
 '상품T',
 '상품P',
 '상품T',
 '상품V',
 '상품E',
 '상품P',
 '상품G',
 '상품L',
 '상품P',
 '상품M',
 '상품D',
 '상품O',
 '상품N',
 '상품X',
 '상품W',
 '상품J',
 '상품X',
 '상품R',
 '상품A',
 '상품W',
 '상품C',
 '상품O',
 '상품V',
 '상품U',
 '상품F',
 '상품K',
 '상품W',
 '상품E',
 '상품S',
 '상품N',
 '상품C',
 '상품I',
 '상품W',
 '상품D',
 '상품E',
 '상품V',
 '상품Y',
 '상품V',
 '상품X',
 '상품F',
 '상품F',
 '상품B',
 '상품C',
 '상품K',
 '상품M',
 '상품Y',
 '상품Q',
 '상품I',
 '상품G',
 '상품T',
 '상품D',
 '상품D',
 '상품Y',
 '상품E',
 '상품N',
 '상품F',
 '상품N',
 '상품A',
 '상품A',
 '상품B',
 '상품X',
 '상품Y',
 '상품S',
 '상품P',
 '상품V',
 '상품I',
 '상품O',
 '상품J',
 '상품J',
 '상품C',
 '상품A',
 '상품U',
 '상품J',
 '상품M',
 '상품F',
 '상품B',
 '상품N',
 '상품Q',
 '상품T',
 '상품L',
 '상품O',
 '상품A',
 '상품R',
 '상품R',
 '상품F',
 '상품Y',
 '상품R',
 '상품L',
 '상품B',
 '상품V',
 '상품P',
 '상품X',
 '상품B',
 '상품Q',
 '상품U',
 '상품W',
 '상품U',
 '상품C',
 '상품V',
 '상품Q',
 '상품N',
 '상품X',
 '상품P',
 '상품B',
 '상품C',
 '상품Q',
 '상품S',
 '상품E',
 '상품F',
 '상품F',
 '상품F',
 '상품E',
 '상품G',
 '상품U',
 '상품L',
 '상품U',
 '상품I',
 '상품F',
 '상품W',
 '상품K',
 '상품V',
 '상품A',
 '상품F',
 '상품L',
 '상품O',
 '상품S',
 '상품D',
 '상품V',
 '상품J',
 '상품E',
 '상품U',
 '상품W',
 '상품B',
 '상품J',
 '상품L',
 '상품W',
 '상품K',
 '상품B',
 '상품F',
 '상품B',
 '상품M',
 '상품C',
 '상품A',
 '상품N',
 '상품P',
 '상품C',
 '상품X',
 '상품A',
 '상품L',
 '상품K',
 '상품P',
 '상품S',
 '상품Q',
 '상품M',
 '상품R',
 '상품K',
 '상품X',
 '상품X',
 '상품H',
 '상품G',
 '상품G',
 '상품E',
 '상품O',
 '상품E',
 '상품R',
 '상품Y',
 '상품M',
 '상품P',
 '상품B',
 '상품E',
 '상품U',
 '상품V',
 '상품L',
 '상품T',
 '상품W',
 '상품V',
 '상품W',
 '상품B',
 '상품R',
 '상품V',
 '상품W',
 '상품M',
 '상품G',
 '상품G',
 '상품G',
 '상품G',
 '상품M',
 '상품F',
 '상품V',
 '상품W',
 '상품N',
 '상품J',
 '상품H',
 '상품A',
 '상품A',
 '상품F',
 '상품M',
 '상품G',
 '상품D',
 '상품I',
 '상품O',
 '상품W',
 '상품S',
 '상품Q',
 '상품C',
 '상품P',
 '상품I',
 '상품A',
 '상품A',
 '상품S',
 '상품A',
 '상품M',
 '상품D',
 '상품G',
 '상품G',
 '상품T',
 '상품E',
 '상품O',
 '상품T',
 '상품S',
 '상품T',
 '상품X',
 '상품V',
 '상품Q',
 '상품F',
 '상품H',
 '상품B',
 '상품B',
 '상품M',
 '상품I',
 '상품R',
 '상품L',
 '상품D',
 '상품K',
 '상품V',
 '상품K',
 '상품F',
 '상품B',
 '상품V',
 '상품T',
 '상품K',
 '상품J',
 '상품A',
 '상품O',
 '상품J',
 '상품H',
 '상품I',
 '상품S',
 '상품S',
 '상품E',
 '상품N',
 '상품O',
 '상품R',
 '상품Q',
 '상품E',
 '상품Y',
 '상품F',
 '상품D',
 '상품A',
 '상품R',
 '상품W',
 '상품P',
 '상품F',
 '상품Y',
 '상품C',
 '상품R',
 '상품Q',
 '상품V',
 '상품E',
 '상품F',
 '상품O',
 '상품V',
 '상품S',
 '상품M',
 '상품E',
 '상품J',
 '상품P',
 '상품F',
 '상품S',
 '상품T',
 '상품W',
 '상품W',
 '상품U',
 '상품L',
 '상품Q',
 '상품S',
 '상품Q',
 '상품Q',
 '상품D',
 '상품G',
 '상품U',
 '상품E',
 '상품S',
 '상품F',
 '상품B',
 '상품N',
 '상품F',
 '상품Y',
 '상품D',
 '상품X',
 '상품C',
 '상품S',
 '상품S',
 '상품L',
 '상품B',
 '상품D',
 '상품B',
 '상품M',
 '상품D',
 '상품J',
 '상품I',
 '상품J',
 '상품R',
 '상품C',
 '상품J',
 '상품D',
 '상품R',
 '상품O',
 '상품Q',
 '상품P',
 '상품A',
 '상품F',
 '상품D',
 '상품D',
 '상품K',
 '상품D',
 '상품C',
 '상품V',
 '상품M',
 '상품O',
 '상품M',
 '상품P',
 '상품A',
 '상품K',
 '상품N',
 '상품A',
 '상품X',
 '상품V',
 '상품E',
 '상품P',
 '상품H',
 '상품P',
 '상품X',
 '상품H',
 '상품A',
 '상품U',
 '상품K',
 '상품C',
 '상품R',
 '상품W',
 '상품E',
 '상품V',
 '상품C',
 '상품T',
 '상품D',
 '상품N',
 '상품W',
 '상품P',
 '상품U',
 '상품P',
 '상품N',
 '상품P',
 '상품E',
 '상품T',
 '상품W',
 '상품L',
 '상품C',
 '상품H',
 '상품O',
 '상품W',
 '상품D',
 '상품N',
 '상품N',
 '상품P',
 '상품K',
 '상품C',
 '상품F',
 '상품V',
 '상품U',
 '상품K',
 '상품H',
 '상품E',
 '상품F',
 '상품E',
 '상품C',
 '상품C',
 '상품G',
 '상품X',
 '상품J',
 '상품T',
 '상품H',
 '상품B',
 '상품R',
 '상품R',
 '상품V',
 '상품K',
 '상품I',
 '상품B',
 '상품B',
 '상품U',
 '상품I',
 '상품X',
 '상품S',
 '상품F',
 '상품V',
 '상품O',
 '상품S',
 '상품J',
 '상품X',
 '상품Q',
 '상품D',
 '상품V',
 '상품J',
 '상품H',
 '상품H',
 '상품A',
 '상품I',
 '상품L',
 '상품I',
 '상품R',
 '상품G',
 '상품V',
 '상품C',
 '상품E',
 '상품A',
 '상품U',
 '상품X',
 '상품N',
 '상품O',
 '상품K',
 '상품V',
 '상품V',
 '상품B',
 '상품M',
 '상품T',
 '상품Q',
 '상품U',
 '상품R',
 '상품F',
 '상품F',
 '상품R',
 '상품R',
 '상품G',
 '상품C',
 '상품C',
 '상품F',
 '상품T',
 '상품Y',
 '상품D',
 '상품A',
 '상품Y',
 '상품F',
 '상품F',
 '상품M',
 '상품B',
 '상품H',
 '상품I',
 '상품F',
 '상품O',
 '상품A',
 '상품Q',
 '상품D',
 '상품F',
 '상품G',
 '상품O',
 '상품S',
 '상품T',
 '상품D',
 '상품I',
 '상품P',
 '상품K',
 '상품R',
 '상품V',
 '상품D',
 '상품C',
 '상품B',
 '상품C',
 '상품D',
 '상품F',
 '상품R',
 '상품H',
 '상품A',
 '상품S',
 '상품X',
 '상품P',
 '상품I',
 '상품Y',
 '상품C',
 '상품B',
 '상품A',
 '상품V',
 '상품W',
 '상품G',
 '상품V',
 '상품C',
 '상품N',
 '상품L',
 '상품I',
 '상품R',
 '상품B',
 '상품W',
 '상품E',
 '상품R',
 '상품N',
 '상품G',
 '상품U',
 '상품N',
 '상품Y',
 '상품L',
 '상품W',
 '상품D',
 '상품O',
 '상품N',
 '상품J',
 '상품A',
 '상품H',
 '상품D',
 '상품K',
 '상품B',
 '상품C',
 '상품M',
 '상품T',
 '상품X',
 '상품V',
 '상품L',
 '상품A',
 '상품Y',
 '상품T',
 '상품N',
 '상품G',
 '상품M',
 '상품T',
 '상품F',
 '상품M',
 '상품M',
 '상품I',
 '상품Y',
 '상품G',
 '상품B',
 '상품U',
 '상품X',
 '상품F',
 '상품J',
 '상품A',
 '상품R',
 '상품V',
 '상품P',
 '상품A',
 '상품O',
 '상품Y',
 '상품R',
 '상품X',
 '상품R',
 '상품A',
 '상품Y',
 '상품Q',
 '상품V',
 '상품O',
 '상품O',
 '상품M',
 '상품G',
 '상품S',
 '상품K',
 '상품J',
 '상품O',
 '상품R',
 '상품Q',
 '상품M',
 '상품C',
 '상품W',
 '상품G',
 '상품C',
 '상품P',
 '상품N',
 '상품N',
 '상품A',
 '상품E',
 '상품V',
 '상품D',
 '상품U',
 '상품S',
 '상품N',
 '상품Y',
 '상품R',
 '상품N',
 '상품W',
 '상품J',
 '상품L',
 '상품D',
 '상품S',
 '상품Y',
 '상품W',
 '상품T',
 '상품L',
 '상품V',
 '상품R',
 '상품H',
 '상품E',
 '상품O',
 '상품E',
 '상품V',
 '상품Q',
 '상품H',
 '상품I',
 '상품M',
 '상품M',
 '상품X',
 '상품L',
 '상품F',
 '상품E',
 '상품S',
 '상품N',
 '상품I',
 '상품O',
 '상품F',
 '상품B',
 '상품N',
 '상품O',
 '상품P',
 '상품V',
 '상품L',
 '상품I',
 '상품N',
 '상품U',
 '상품J',
 '상품X',
 '상품E',
 '상품O',
 '상품D',
 '상품C',
 '상품K',
 '상품K',
 '상품R',
 '상품X',
 '상품S',
 '상품W',
 '상품U',
 '상품J',
 '상품C',
 '상품I',
 '상품Q',
 '상품E',
 '상품V',
 '상품D',
 '상품R',
 '상품F',
 '상품B',
 '상품K',
 '상품A',
 '상품T',
 '상품A',
 '상품U',
 '상품Y',
 '상품Q',
 '상품L',
 '상품R',
 '상품H',
 '상품S',
 '상품Q',
 '상품S',
 '상품W',
 '상품H',
 '상품G',
 '상품M',
 '상품A',
 '상품M',
 '상품M',
 '상품Q',
 '상품T',
 '상품X',
 '상품U',
 '상품O',
 '상품S',
 '상품E',
 '상품C',
 '상품C',
 '상품R',
 '상품J',
 '상품G',
 '상품L',
 '상품Y',
 '상품P',
 '상품O',
 '상품K',
 '상품C',
 '상품A',
 '상품N',
 '상품J',
 '상품N',
 '상품X',
 '상품U',
 '상품A',
 '상품J',
 '상품G',
 '상품S',
 '상품J',
 '상품Q',
 '상품X',
 '상품R',
 '상품C',
 '상품Y',
 '상품U',
 '상품L',
 '상품B',
 '상품Q',
 '상품R',
 '상품A',
 '상품P',
 '상품L',
 '상품L',
 '상품H',
 '상품D',
 '상품D',
 '상품R',
 '상품A',
 '상품S',
 '상품Y',
 '상품C',
 '상품V',
 '상품A',
 '상품N',
 '상품M',
 '상품E',
 '상품C',
 '상품A',
 '상품A',
 '상품N',
 '상품W',
 '상품X',
 '상품I',
 '상품L',
 '상품Y',
 '상품P',
 '상품D',
 '상품V',
 '상품O',
 '상품L',
 '상품B',
 '상품J',
 '상품S',
 '상품X',
 '상품D',
 '상품B',
 '상품K',
 '상품R',
 '상품V',
 '상품N',
 '상품A',
 '상품Q',
 '상품I',
 '상품P',
 '상품E',
 '상품B',
 '상품S',
 '상품Q',
 '상품O',
 '상품W',
 '상품D',
 '상품K',
 '상품J',
 '상품X',
 '상품J',
 '상품C',
 '상품V',
 '상품C',
 '상품D',
 '상품H',
 '상품O',
 '상품K',
 '상품U',
 '상품N',
 '상품E',
 '상품D',
 '상품Y',
 '상품B',
 '상품G',
 '상품X',
 '상품X',
 '상품B',
 '상품S',
 '상품T',
 '상품O',
 '상품W',
 '상품Q',
 '상품M',
 '상품Q',
 '상품O',
 '상품J',
 '상품B',
 '상품K',
 '상품S',
 '상품F',
 '상품C',
 '상품O',
 '상품S',
 '상품T',
 '상품H',
 '상품R',
 '상품P',
 '상품A',
 '상품U',
 '상품H',
 '상품J',
 '상품S',
 '상품A',
 '상품Q',
 '상품G',
 '상품P',
 '상품Q',
 '상품R',
 '상품X',
 '상품Y',
 '상품R',
 '상품P',
 '상품Q',
 '상품I',
 '상품D',
 '상품F',
 '상품X',
 '상품Y',
 '상품O',
 '상품D',
 '상품S',
 '상품O',
 '상품F',
 '상품S',
 '상품F',
 '상품G',
 '상품T',
 '상품J',
 '상품B',
 '상품O',
 '상품M',
 '상품O',
 '상품O',
 '상품F',
 '상품J',
 '상품V',
 '상품I',
 '상품S',
 '상품H',
 '상품C',
 '상품I',
 '상품B',
 '상품W',
 '상품J',
 '상품B',
 ...]

In [18]:
# df.loc[0,'item_name'] #인덱스의 값이 0이고 컬럼의 값이 'item_name'의 데이터를 추출
# df.iloc[0,1] #인덱스의 위치가 0 (첫번째) 이고 컬럼의 위치가 1(두번째)인 데이터를 추출

In [19]:
df['item_name']=new_list
df.head()

      purchase_date item_name  item_price customer_name
0  2019-06-13 18:02       상품A       100.0           김가온
1  2019-07-13 13:05       상품S         NaN           김우찬
2  2019-05-11 19:42       상품a         NaN           김유찬
3  2019-02-12 23:40       상품Z      2600.0           김재현
4   2019-04-22 3:09       상품a         NaN           김강현

In [20]:
df=uriage.copy()

In [23]:
# 반복 실행하면서 데이터프레임에 변경이 된 데이터를 바로 대입

for i in range(len(df)):
    df.iloc[i,1]=df.iloc[i,1].replace(' ','')

In [24]:
df.head()

      purchase_date item_name  item_price customer_name
0  2019-06-13 18:02       상품A       100.0           김가온
1  2019-07-13 13:05       상품S         NaN           김우찬
2  2019-05-11 19:42       상품a         NaN           김유찬
3  2019-02-12 23:40       상품Z      2600.0           김재현
4   2019-04-22 3:09       상품a         NaN           김강현

In [25]:
# map()
df=uriage.copy()
df.head()

      purchase_date item_name  item_price customer_name
0  2019-06-13 18:02       상품A       100.0           김가온
1  2019-07-13 13:05     상 품 S         NaN           김우찬
2  2019-05-11 19:42     상 품 a         NaN           김유찬
3  2019-02-12 23:40       상품Z      2600.0           김재현
4   2019-04-22 3:09       상품a         NaN           김강현

In [27]:
df['item_name'].map(
    lambda x : x.replace(' ','')
)

0       상품A
1       상품S
2       상품a
3       상품Z
4       상품a
       ...
2994    상품Y
2995    상품M
2996    상품Q
2997    상품H
2998    상품D
Name: item_name, Length: 2999, dtype: str

In [28]:
# 공백제거 + 대소문자 통일 -> 한번에 처리
'a b c'.replace(' ','').upper()

'ABC'

In [30]:
uriage['item_name'].str.replace(' ','').str.upper()

0       상품A
1       상품S
2       상품A
3       상품Z
4       상품A
       ...
2994    상품Y
2995    상품M
2996    상품Q
2997    상품H
2998    상품D
Name: item_name, Length: 2999, dtype: str

In [35]:
# item_name의 데이터들이 정형화 되었는가?
# item_name의 고유(unique)값(중복 데이터는 제거)들을 출력해보자.
uriage['item_name'].unique

<bound method Series.unique of 0         상품A
1       상 품 S
2       상 품 a
3         상품Z
4         상품a
        ...
2994      상품Y
2995      상품M
2996      상품Q
2997      상품H
2998      상품D
Name: item_name, Length: 2999, dtype: str>

In [36]:
# 데이터들의 빈도수 확인
uriage['item_name'].value_counts()

item_name
상품A      133
상품S      133
상품R      133
상품P      132
상품C      130
        ...
상 품I       1
 상품 W      1
 상품 X      1
상품 M       1
상 품P       1
Name: count, Length: 99, dtype: int64

In [37]:
# 결측치를 채워준다 -> 어떻게 채울것인가?
# 데이터를 확인 -> 특정 상품의 item_price가 결측치가 아닌 데이터와 결측치인 데이터를 확인
# 조건식1: 특정 상품명(uriage['item_name']=='상품A')
# 조건식2: 결측치인가 (uriage['item_name'].isna())
flag=uriage['item_name']=='상품A'
flag_null=uriage['item_price'].isna()

In [40]:
# 상품명이 상품A이고 가격이 결측치가 아닌 데이터를 확인
# bool 형태로 이루어진 Series의 부정은 : 음수처리(-), 비트연산자(~)
uriage.loc[
    flag & ~flag_null, 'item_price'
].value_counts()

item_price
100.0    114
Name: count, dtype: int64

In [41]:
flag2=uriage['item_name']=='상품B'

In [45]:
uriage.loc[
    flag2 & ~flag_null,'item_price'
].value_counts()

item_price
200.0    95
Name: count, dtype: int64

In [47]:
flag3=uriage['item_name']=='상품C'

In [49]:
# 결측치에 데이터를 채운다
# 상품A인 데이터들의 item_price의 평균 값을
# 상품A인 데이터에서 item_price가 결측치인 부분에 채워준다.

# 상품명이 상품A이고 item_price가 결측치가 아닌 데이터에서 item_price의 평균
mean_price=uriage.loc[flag&~flag_null,'item_price'].mean()
mean_price

np.float64(100.0)

In [52]:
# fillna() 사용
# 상품명이 상품A이고 iteme_price가 결측치인 데이터에 결측치를 mean_price로 채워준다.
# 스리즈 형태로 출력 -> 데이터가 변화x -> 대입이 필요
uriage.loc[flag & flag_null, 'item_price']=uriage.loc[flag & flag_null, 'item_price'].fillna(mean_price)

In [54]:
# flag_null은 결측치를 채우기 전에 만든 결측치인 조건식
uriage.loc[flag & flag_null, 'item_price']

14      100.0
300     100.0
361     100.0
667     100.0
838     100.0
844     100.0
957     100.0
1260    100.0
1394    100.0
1474    100.0
1892    100.0
1937    100.0
1977    100.0
2063    100.0
2278    100.0
2636    100.0
2669    100.0
2732    100.0
2821    100.0
Name: item_price, dtype: float64

In [56]:
mean_price2=uriage.loc[
    flag2 & ~flag_null, 'item_price' #~flag_null 생략가능
].mean()
# 상품C이고 가격이 존재하는 데이터의 평균 (결측치를 제외하고 평균을 구하겠다.)
# pandas에서 결측치를 포함한 연산은 결측치를 제외하고 연산
mean_price2

np.float64(300.0)

In [57]:
# Series = 단일 데이터 --> Series의 모든 Value가 단일 데이터로 채워진다.
# Series(상품C의 가격이 결측치인) = 단일 데이터(평균값) --> Series의 모든 Value가 단일 데이터
uriage.loc[
    flag2 & flag_null, 'item_price'
] = mean_price2

In [60]:
uriage.loc[
    flag2 & flag_null, 'item_price'
]

114     300.0
144     300.0
417     300.0
672     300.0
721     300.0
827     300.0
852     300.0
945     300.0
1113    300.0
1294    300.0
1422    300.0
1515    300.0
1726    300.0
1778    300.0
1890    300.0
2293    300.0
2301    300.0
2381    300.0
2726    300.0
2992    300.0
Name: item_price, dtype: float64

In [61]:
# 모든 상품 이름을 기준으로 반복문 실행
# 각 상품의 가격의 평균을 구하고 해당 값을 결측치에 채워준다
# 모든 상품의 목록 필요 (unique)
item_list=uriage['item_name'].unique()
item_list

<StringArray>
[   '상품A',  '상 품 S',  '상 품 a',    '상품Z',    '상품a',    '상품S',   '상품 a',
    '상품V',    '상품O',   '상 품U',    '상품L',  '상  품V',   '상 품O',    '상품C',
    '상품I',    '상품r',    '상품X',   '상품 g',    '상품R',    '상품P',    '상품Q',
    '상품y',   '상품 A',    '상품N',    '상품W',   '상 품E',    '상품K',    '상품B',
    '상품F',   '상 품s',   ' 상품W', ' 상 품 n',   '상 품F',    '상품D',    '상품M',
    '상품Y',    '상품U',    '상품H',    '상품T',    '상품J',  '상  품O',    '상품E',
  '상  품Q',  ' 상품 S',  ' 상품 M',  '상  품T',    '상품G',   '상 품G',  ' 상품 P',
  ' 상품 E',   '상 품N',   '상 품Y',   '상품 J',   '상품 V',   '상품 K',   '상 품V',
   '상 품D',   '상 품A',   '상품 F',   '상품 H',   '상 품K',   '상 품T',   '상품 X',
   '상품 Q',   '상 품X',   '상 품H',   '상 품C',   '상품 B',   '상품 O',   '상품 T',
    '상품v',    '상품p',    '상품i',   '상품 w',  '상 품 s',  '상 품 q',    '상품s',
    '상품l',    '상품t',    '상품k',    '상품g',    '상품o',   '상품 R',   '상품 S',
   '상 품M',    '상품j',    '상품d',   '상품 I',   '상품 E',   '상품 o',    '상품c',
   '상품 v',    '상품e',    '상품x',   '상 품I',  ' 상품 W',  ' 상품 X',   '상품 M',
   '상 품P']
Length: 99, dtype: str

In [66]:
# 조건식 2 생성 (item_price가 결측치인) -> 상품명과 상관없이 item_price의 결측치
flag_null=uriage['item_price'].isna()

for item_name in item_list:
    # item_list의 각 원소들이 대입
    # print(item_name)
    # 조건식 1 생성 -> 반복실행할때마다 다른 조건식이 들어감
    flag=uriage['item_name']==item_name
    
    # 가격의 평균을 구한다.
    mean_price=uriage.loc[
        flag & ~flag_null, 'item_price'
    ].mean()
    # flag와 flag_null을 모두 만족하는 item_price에 mean_price를 대입
    uriage.loc[
        flag&flag_null, 'item_price'
    ]=mean_price

In [70]:
# uriage에 item_price 결측치의 개수를 확인
uriage['item_price'].isna().sum()

np.int64(6)

In [72]:
for i in range(len(item_list)):
    # item_list의 위치 값들이 대입
    # print(i)
    # 각각의 상품명에 따라 item_price의 평균 확인
    flag=uriage['item_name']==item_list[i]

    mean_price=uriage.loc[flag, 'item_price'].mean()

    print(f"{item_list[i]} : {mean_price}")

상품A : 100.0
상 품 S : nan
상 품 a : 100.0
상품Z : 2600.0
상품a : nan
상품S : 1900.0
상품 a : nan
상품V : 2200.0
상품O : 1500.0
상 품U : 2100.0
상품L : 1200.0
상  품V : 2200.0
상 품O : 1500.0
상품C : 300.0
상품I : 900.0
상품r : 1800.0
상품X : 2400.0
상품 g : 700.0
상품R : 1800.0
상품P : 1600.0
상품Q : 1700.0
상품y : 2500.0
상품 A : 100.0
상품N : 1400.0
상품W : 2300.0
상 품E : 500.0
상품K : 1100.0
상품B : 200.0
상품F : 600.0
상 품s : 1900.0
 상품W : 2300.0
 상 품 n : 1400.0
상 품F : 600.0
상품D : 400.0
상품M : 1300.0
상품Y : 2500.0
상품U : 2100.0
상품H : 800.0
상품T : 2000.0
상품J : 1000.0
상  품O : nan
상품E : 500.0
상  품Q : 1700.0
 상품 S : 1900.0
 상품 M : 1300.0
상  품T : 2000.0
상품G : 700.0
상 품G : 700.0
 상품 P : 1600.0
 상품 E : 500.0
상 품N : 1400.0
상 품Y : 2500.0
상품 J : 1000.0
상품 V : 2200.0
상품 K : 1100.0
상 품V : 2200.0
상 품D : 400.0
상 품A : 100.0
상품 F : 600.0
상품 H : 800.0
상 품K : 1100.0
상 품T : 2000.0
상품 X : 2400.0
상품 Q : 1700.0
상 품X : 2400.0
상 품H : 800.0
상 품C : 300.0
상품 B : nan
상품 O : 1500.0
상품 T : 2000.0
상품v : 2200.0
상품p : 1600.0
상품i : 900.0
상품 w : 2300.0
상 품 s : 1900.0
상 품 q : 1700.0
상품s : 1900.0
상품l : 1200.0
상품t : 2000.0
상품k : 1100.0
상품g : 700.0
상품o : 1500.0
상품 R : 1800.0
상품 S : 1900.0
상 품M : 1300.0
상품j : 1000.0
상품d : 400.0
상품 I : 900.0
상품 E : 500.0
상품 o : 1500.0
상품c : 300.0
상품 v : nan
상품e : 500.0
상품x : 2400.0
상 품I : 900.0
 상품 W : 2300.0
 상품 X : 2400.0
상품 M : 1300.0
상 품P : 1600.0