In [1]:
import pandas as pd

In [2]:
# csv 폴더 안에 있는 Sales Records.csv 파일 로드 
sales = pd.read_csv("../csv/Sales Records.csv")

In [3]:
# 데이터 파일을 로드했으면 확인 
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          10000 non-null  str
 1   Country         10000 non-null  str
 2   Item Type       10000 non-null  str
 3   Sales Channel   10000 non-null  str
 4   Order Priority  10000 non-null  str
 5   Order Date      10000 non-null  str
 6   Order ID        10000 non-null  int64
 7   Ship Date       10000 non-null  str
 8   Units Sold      10000 non-null  int64
 9   Unit Price      10000 non-null  float64
 10  Unit Cost       10000 non-null  float64
 11  Total Revenue   10000 non-null  float64
 12  Total Cost      10000 non-null  float64
 13  Total Profit    10000 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.1 MB

In [4]:
sales.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+04,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,1.000000e+04
mean,5.498719e+08,5002.855900,268.143139,188.806639,1.333355e+06,9.382658e+05,3.950893e+05
std,2.607835e+08,2873.246454,217.944092,176.445907,1.465026e+06,1.145914e+06,3.775550e+05
min,1.000892e+08,2.000000,9.330000,6.920000,1.679400e+02,1.245600e+02,4.338000e+01
25%,3.218067e+08,2530.750000,109.280000,56.670000,2.885511e+05,1.647855e+05,9.832914e+04
50%,5.485663e+08,4962.000000,205.700000,117.110000,8.000512e+05,4.816058e+05,2.890990e+05
75%,7.759981e+08,7472.000000,437.200000,364.690000,1.819143e+06,1.183822e+06,5.664227e+05
max,9.999342e+08,10000.000000,668.270000,524.960000,6.680027e+06,5.241726e+06,1.738178e+06

In [5]:
# 데이터프레임의 상단의 5개의 데이터를 확인 
sales.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,1/27/2011,292494523,2/12/2011,4484,651.21,524.96,2920025.64,2353920.64,566105.00
1,Europe,Latvia,Beverages,Online,C,12/28/2015,361825549,1/23/2016,1075,47.45,31.79,51008.75,34174.25,16834.50
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,1/13/2011,141515767,2/1/2011,6515,154.06,90.93,1003700.90,592408.95,411291.95
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,9/11/2012,500364005,10/6/2012,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,10/27/2015,127481591,12/5/2015,3491,47.45,31.79,165647.95,110978.89,54669.06

### 연습 
1. 원본의 데이터의 복사본을 생성(df)
2. 'Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Oerder Priority' 컬럼을 제거
3. 컬럼의 이름을 변경 -> 대륙, 국가, 상품종류, 판매채널, 주문일자, 발송일자, 판매개수, 단가, 원가
4. 대륙, 국가를 기준으로 오름차순 정렬
5. 인덱스를 초기화하고 기존의 인덱스는 제거 
6. 파생변수 생성 
    - 총단가 = 단가 * 판매개수
    - 총원가 = 원가 * 판매개수
    - 총이윤 = 총단가 - 총원가

In [16]:
# 원본의 데이터의 복사본을 생성 (copy() 함수를 호출하여 복사본을 생성 )
df = sales.copy()
# 컬럼을 제거 
df.drop(
    ['Order ID', 'Total Revenue', 'Total Cost', 
     'Total Profit', 'Order Priority'], 
     axis = 1, inplace = True
)

In [17]:
# drop() 함수를 이용하여 컬럼을 제거하 데이터프레임을 새로운 변수에 대입
# ( 컬럼을 제거한다 + 복사본 데이터를 생성 )
df2 = sales.drop(
    ['Order ID', 'Total Revenue', 'Total Cost', 
     'Total Profit', 'Order Priority'], 
     axis = 1
)

In [23]:
# 컬럼의 이름을 변경 -> 2개의 방법을 사용 
# ( rename() 함수 이용 / DataFrame.columns 변수의 데이터를 변경 )
# rename() -> 특정 컬럼의 이름을 변경할 때 주로 사용 ( 컬럼의 이름이 변경된 데이터를 먼저 확인하고 바꾸기 위해 )
# DataFrame.columns의 변수 데이터를 변경할 때는 확인 후 변경이 불가능 ( 모든 컬럼의 이름을 변경 )
df.rename(
    columns = {
        'Region' : '대륙',
        'Country' : '국가', 
        'Item Type' : '상품종류', 
        'Sales Channel' : '판매채널', 
        'Order Date' : '주문일자', 
        'Units Sold' : '판매개수', 
        'Ship Date' : '발송일자', 
        'Unit Price' : '단가', 
        'Unit Cost' : '원가'
    }, inplace = True
)

In [24]:
df2.columns = ['대륙', '국가', '상품종류', '판매채널', '주문일자', 
               '발송일자', '판매개수', '단가', '원가']

In [ ]:
# 대륙, 국가를 기준으로 오름차순 정렬 
# value를 기준으로 정렬을 변경 -> sort_values()
# 잘못된 예시 -> 
    # 1. 대륙을 기준으로 오름차순을 정렬
    # 2. 국가를 기준으로 오름차순을 정렬 -> 1번 작업과 상관 없이 국가별로 오름차순
df.sort_values('대륙', inplace=True)
df.sort_values('국가', inplace=True)

In [ ]:
df

In [32]:
# 대륙별로 오름차순 정렬이 되고 대륙별 국가로 오름차순 정렬이 되는 방법 
# sort_values 함수에 기준이 2개
df.sort_values(['대륙', '국가'], inplace=True)

In [35]:
# 인덱스를 초기화하고 기존의 인덱스는 제거 
# reset_index() -> 기존의 인덱스를 제거한다 drop 매개변수를 사용
df.reset_index(drop=True , inplace=True)

In [36]:
# 파생변수를 생성 (총단가, 총원가, 총이윤)
# 총단가 , 총원가 -> 기존의 데이터에서 계산식 
# 총이윤 -> 파생변수에서 파생된 새로운 변수 
df['총단가'] = df['단가'] * df['판매개수']      
# 행렬 간의 곱 -> Series, DataFrame이든 values의 타입은 행렬 -> value * value
# -> 행렬 * 행렬 (두개의 행렬의 크기가 같아야 한다.)
df['총원가'] = df['원가'] * df['판매개수']
df['총이윤'] = df['총단가'] - df['총원가']
# df['총이윤'] = ( df['단가'] * df['판매개수'] ) - ( df['원가'] * df['판매개수'] )

In [37]:
df.head()

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
0,Asia,Bangladesh,Personal Care,Online,11/6/2010,11/13/2010,3246,81.73,56.67,265295.58,183950.82,81344.76
1,Asia,Bangladesh,Fruits,Offline,3/4/2011,3/12/2011,1138,9.33,6.92,10617.54,7874.96,2742.58
2,Asia,Bangladesh,Snacks,Offline,10/17/2011,11/23/2011,1421,152.58,97.44,216816.18,138462.24,78353.94
3,Asia,Bangladesh,Cosmetics,Online,4/20/2016,4/23/2016,1717,437.20,263.33,750672.40,452137.61,298534.79
4,Asia,Bangladesh,Office Supplies,Online,1/29/2016,3/6/2016,400,651.21,524.96,260484.00,209984.00,50500.00

In [38]:
# 어떤 대륙이 총이윤의 합계가 가장 클까?
# 대륙별 고유값 리스트를 생성 -> unique() // value_counts()
# 대륙 컬럼을 기준으로 비교연산자를 사용해서 필터링 -> 총이윤의 합산 (반복 실행)
df['대륙'].unique()

<StringArray>
[                             'Asia',             'Australia and Oceania',
 'Central America and the Caribbean',                            'Europe',
      'Middle East and North Africa',                     'North America',
                'Sub-Saharan Africa']
Length: 7, dtype: str

In [ ]:
df['대륙'].value_counts()  # 결과의 타입은? -> Series -> index의 값들은 추출하면 고유값 리스트

대륙
Europe                               2633
Sub-Saharan Africa                   2603
Asia                                 1469
Middle East and North Africa         1264
Central America and the Caribbean    1019
Australia and Oceania                 797
North America                         215
Name: count, dtype: int64

In [42]:
list_1 = df['대륙'].value_counts().index

In [ ]:
data_list = []
for data in list_1:
    # data -> 대입이 되는 데이터는? -> 각 대륙의 이름 
    # print(data)
    # 조건식 생성 
    flag = df['대륙'] == data
    # 조건식을 이용하여 필터 -> 총이윤의 합산
    result = df.loc[flag, '총이윤'].sum()
    # print(result)
    # 대륙의 이름과 총이윤의 합산을 dict 형태로 생성하여 새로운 리스트에 추가 
    dict_data = { '대륙' : data, '총이윤 합산': result }
    data_list.append(dict_data)
data_list

In [ ]:
# data_list를 데이터프레임으로 변경 
pd.DataFrame(data_list)

In [49]:
# 데이터의 그룹화 -> 같은 데이터들을 결합하여 연산한 뒤 새로운 데이터로 구성 
# 그룹화 함수 -> groupby( 그룹화를 할 컬럼의 이름(2개 이상이라면 []로 입력) )

group_data = df.groupby('대륙')

group_data

In [ ]:
# 그룹화 데이터에서 특정 그룹만 추출 -> 그룹(gorup)을 가져오다(get) -> get_group()
group_data.get_group('Asia')
# loc를 이용해서 대륙이 Asia와 같은 조건식으로 필터링과 같은 데이터

In [55]:
# 그룹화된 데이터에서 그룹끼리의 연산(그룹화 연산)
group_data.sum()['총이윤']
# 합산 -> 문자의 합산? -> 문자끼리 연결
# 숫자의 합산 -> 누적합

대륙
Asia                                 5.874033e+08
Australia and Oceania                3.240712e+08
Central America and the Caribbean    4.033578e+08
Europe                               1.027000e+09
Middle East and North Africa         5.099239e+08
North America                        9.949552e+07
Sub-Saharan Africa                   9.996421e+08
Name: 총이윤, dtype: float64

In [58]:
# 그룹화 연산의 평균 
# group_data.mean()['총이윤']
# gorup_data에서 컬럼의 dtype이 숫자형이 아니라면 평균에서 에러 발생
# 그룹화를 할때 문자열 컬럼은 제외하고 그룹화 -> 그룹화 연산

In [67]:
# 컬럼을 필터(특정 컬럼들을 선택) -> 그룹화 -> 그룹화 연산 
# 대륙별 총 이윤의 합계와 평균을 구해보자
# 컬럼의 필터 -> 총이윤
# df[['총이윤', '대륙']].groupby('대륙').sum().mean()
# sum() -> mean() 
# 총이윤의 합산에서 평균 
# 합산 따로 평균 따로 
group_data2 = df[['총이윤', '대륙']].groupby('대륙').agg(['mean', 'sum'])

In [78]:
# 데이터프레임이 멀티 컬럼으로 이루어진 데이터프레임 
# 데이터에 접근하기 위한 방법은 컬럼도 하나씩 선택 
# 컬럼을 선택하기 위해서는 가장 상단의 컬럼부터 하나씩 선택 
group_data2['총이윤']['mean']['Asia']

np.float64(399866.09724302246)

In [ ]:
test_data = {
    '총이윤' :{
        'mean' : {
            'Asia' : 100
        }, 
        'sum' : {
            'Asia' : 1000
        }
    }
}
# 3차원 데이터에서 단일 데이터까지 추출 ( 3번의 필터  )
# test_data['총이윤']['mean']['Asia']
# 에러 발생 -> dict 데이터에서 key가 총이윤만 존재
# test_data['mean']

In [80]:
# group_data2의 인덱스와 컬럼을 확인 
print(group_data2.index)
print(group_data2.columns)

Index(['Asia', 'Australia and Oceania', 'Central America and the Caribbean',
       'Europe', 'Middle East and North Africa', 'North America',
       'Sub-Saharan Africa'],
      dtype='str', name='대륙')
MultiIndex([('총이윤', 'mean'),
            ('총이윤',  'sum')],
           )

In [ ]:
group_data2[ ('총이윤', 'mean') ]

In [83]:
# 멀티 인덱스를 생성 
# 그룹화 기준 컬럼을 2개 이상 ( 대륙, 판매채널 )
# 총 이윤의 합산
group_data3 = df[ ['대륙', '판매채널', '총이윤'] ].groupby(
    ['대륙', '판매채널']).sum()

In [87]:
# 유럽에 오프라인 총이윤의 합산을 추출
# 하나씩 풀어 나간다 -> 컬럼 -> 인덱스로 선택
group_data3['총이윤']['Europe']['Offline']

np.float64(533762385.78999996)

In [ ]:
group_data3.index

In [89]:
# loc를 이용해서 데이터를 추출 -> index가 멀티
group_data3.loc[
    ('Europe', 'Offline'), '총이윤'
]

np.float64(533762385.78999996)

In [91]:
# iloc를 이용해서 데이터를 추출 -> 위치를 기준으로 데이터 추출 
group_data3.iloc[6, 0]

np.float64(533762385.78999996)

In [99]:
# reset_index() -> 기존의 인덱스는 유지 
group_data3.reset_index()

                                   대륙     판매채널           총이윤
0                                Asia  Offline  2.734457e+08
1                                Asia   Online  3.139576e+08
2               Australia and Oceania  Offline  1.527809e+08
3               Australia and Oceania   Online  1.712903e+08
4   Central America and the Caribbean  Offline  2.102715e+08
5   Central America and the Caribbean   Online  1.930864e+08
6                              Europe  Offline  5.337624e+08
7                              Europe   Online  4.932372e+08
8        Middle East and North Africa  Offline  2.549156e+08
9        Middle East and North Africa   Online  2.550083e+08
10                      North America  Offline  5.338042e+07
11                      North America   Online  4.611510e+07
12                 Sub-Saharan Africa  Offline  5.023457e+08
13                 Sub-Saharan Africa   Online  4.972964e+08

In [ ]:
# 인덱스의 기준을 컬럼으로 올려서 새로운데이터프레임 생성 
group_data3.unstack()

In [ ]:
# 컬럼의 기준을 인덱스로 이동
group_data3.stack()

대륙                                 판매채널
Asia                               Offline  총이윤    2.734457e+08
                                   Online   총이윤    3.139576e+08
Australia and Oceania              Offline  총이윤    1.527809e+08
                                   Online   총이윤    1.712903e+08
Central America and the Caribbean  Offline  총이윤    2.102715e+08
                                   Online   총이윤    1.930864e+08
Europe                             Offline  총이윤    5.337624e+08
                                   Online   총이윤    4.932372e+08
Middle East and North Africa       Offline  총이윤    2.549156e+08
                                   Online   총이윤    2.550083e+08
North America                      Offline  총이윤    5.338042e+07
                                   Online   총이윤    4.611510e+07
Sub-Saharan Africa                 Offline  총이윤    5.023457e+08
                                   Online   총이윤    4.972964e+08
dtype: float64

In [ ]:
df[['총이윤']].groupby(df['대륙']).sum()
# groupby() 함수의 특징 
# groupby(스리즈) -> 인덱스는 기준으로 데이터를 그룹화

In [105]:
# stack(), unstack() -> 인덱스를 컬럼으로 이동시키거나 컬럼은 인덱스로 이동 
# 이동이 시키고 컬럼이나 인덱스가 존재하지 않는 경우 (예 : 싱글 컬럼은 인덱스로 이동 )
# 데이터 타입이 스리즈의 형태로 변경 

# 멀티 인덱스로 이루어진 스리즈에서 unstack()을 이용하면 데이터프레임 타입이 변경
group_data4 = df.groupby(['대륙', '판매채널'])['총이윤'].sum()

In [ ]:
group_data4.unstack()

In [108]:
# 스리즈 데이터에서 stack() 사용하면?? --> 에러가 발생(stack 함수는 내장되어 있지 않다)
# group_data4.stack()

In [109]:
# pivot -> table의 데이터들을 재구조화 한다. 
# pandas에서 pivot_table()
# pandas 안에 존재, 데이터프레임 안에서도 존재 
# 모듈 안에 있는 pivot_table()
# DataFrame class 안에 있는 pivot_table()
# 매개변수 index : 어떤 값을 기준(인덱스)으로 테이블 데이터를 배치할것인가? (인덱스로 사용할 데이터 지정)
# 매개변수 columns : 어떤 값을 기준(컬럼)으로 테이블 데이터를 매치할것인가? (컬럼으로 사용할 데이터 지정) 
# 매개변수 values : index, columns를 기준으로 데이터를 결합하여 사용할 value는 무엇인가?
# 매개변수 aggfunc : values를 어떤 연산을 할 것인가?

In [ ]:
# 데이터프레임 클래스 안에 존재하는 pivot_table() 함수를 사용 
df.pivot_table(
    index = '대륙', 
    values = '총이윤', 
    aggfunc= 'sum'
)

In [ ]:
df.pivot_table(
    index = '대륙', 
    columns = '판매채널', 
    values = '총이윤', 
    aggfunc= ['sum', 'mean']
)

In [112]:
# 라이브러리(pandas)안에 pivot_table() 함수 호출 
pd.pivot_table( 
    df,             # module 안에서 함수를 호출 시 변경할 데이터를 인자로 입력
    index = '대륙', 
    columns = '판매채널', 
    values = '총이윤', 
    aggfunc= 'sum'
 )

판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

#### 연습 
1. 각 대륙별 총이윤이 가장 많은 아이템은 무엇인가?
    - 대륙, 상품종류 별 그룹화 
    - 그룹화 연산으로는 총이윤의 합계
    - 각 대륙별로 총이윤이 가장 높은 상품종류를 출력하시오
        - 그룹화 -> 그룹화 연산 -> 총이윤을 기준으로 내림차순 -> 인덱스를 리셋 -> 반복문을 이용해서 각 대륙의 첫번째의 인덱스를 추출 -> 데이터프레임에 필터
    - 답안
        - Asia, Oceania, Europe, Saharan-Africa -> Cosmetic
        - America, North Africa -> Household

In [115]:
# 반복문을 이용해서 각 대륙별 총이윤이 가장 높은 상품종류를 찾아보자 
group_data5 = df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum()
group_data5

                                             총이윤
대륙                 상품종류
Asia               Baby Food        6.379205e+07
                   Beverages        8.647186e+06
                   Cereal           5.369351e+07
                   Clothes          3.886401e+07
                   Cosmetics        1.036069e+08
...                                          ...
Sub-Saharan Africa Meat             5.721001e+07
                   Office Supplies  1.269636e+08
                   Personal Care    2.666266e+07
                   Snacks           6.142855e+07
                   Vegetables       6.197819e+07

[84 rows x 1 columns]

In [117]:
# 총이윤은 기준으로 내림차순 정렬 
group_df = group_data5.sort_values('총이윤', ascending=False)

In [120]:
group_df.index

MultiIndex([(                           'Europe',       'Cosmetics'),
            (               'Sub-Saharan Africa',       'Cosmetics'),
            (               'Sub-Saharan Africa',       'Household'),
            (                           'Europe',       'Household'),
            (                           'Europe', 'Office Supplies'),
            (               'Sub-Saharan Africa', 'Office Supplies'),
            (               'Sub-Saharan Africa',       'Baby Food'),
            (                             'Asia',       'Cosmetics'),
            (     'Middle East and North Africa',       'Household'),
            (                           'Europe',          'Cereal'),
            (                             'Asia',       'Household'),
            (                           'Europe',       'Baby Food'),
            (               'Sub-Saharan Africa',          'Cereal'),
            (                             'Asia', 'Office Supplies'),
            ('Central America and the Caribbean',       'Household'),
            (     'Middle East and North Africa',       'Cosmetics'),
            (               'Sub-Saharan Africa',         'Clothes'),
            (                           'Europe',         'Clothes'),
            (            'Australia and Oceania',       'Cosmetics'),
            (                           'Europe',      'Vegetables'),
            (                           'Europe',            'Meat'),
            (                             'Asia',       'Baby Food'),
            (     'Middle East and North Africa', 'Office Supplies'),
            (               'Sub-Saharan Africa',      'Vegetables'),
            (               'Sub-Saharan Africa',          'Snacks'),
            (            'Australia and Oceania',       'Household'),
            (               'Sub-Saharan Africa',            'Meat'),
            ('Central America and the Caribbean', 'Office Supplies'),
            ('Central America and the Caribbean',       'Cosmetics'),
            (                           'Europe',          'Snacks'),
            (                             'Asia',          'Cereal'),
            (     'Middle East and North Africa',       'Baby Food'),
            (                             'Asia',      'Vegetables'),
            (     'Middle East and North Africa',          'Cereal'),
            (     'Middle East and North Africa',         'Clothes'),
            (                             'Asia',         'Clothes'),
            ('Central America and the Caribbean',          'Cereal'),
            (     'Middle East and North Africa',      'Vegetables'),
            (                             'Asia',          'Snacks'),
            (            'Australia and Oceania',          'Cereal'),
            ('Central America and the Caribbean',       'Baby Food'),
            (                             'Asia',            'Meat'),
            (            'Australia and Oceania',       'Baby Food'),
            ('Central America and the Caribbean',         'Clothes'),
            ('Central America and the Caribbean',      'Vegetables'),
            (                           'Europe',   'Personal Care'),
            (            'Australia and Oceania', 'Office Supplies'),
            (            'Australia and Oceania',         'Clothes'),
            (     'Middle East and North Africa',            'Meat'),
            (               'Sub-Saharan Africa',   'Personal Care'),
            (     'Middle East and North Africa',          'Snacks'),
            ('Central America and the Caribbean',          'Snacks'),
            ('Central America and the Caribbean',            'Meat'),
            (            'Australia and Oceania',      'Vegetables'),
            (                    'North America',       'Household'),
            (                    'North America',       'Cosmetics'),
            (            'Australia and Oceania',          'Snacks'),
            (               'Sub-Saharan Africa',       'Beverages'),
            (            'Australia and Oceania',            'Meat'),
            (                             'Asia',   'Personal Care'),
            (     'Middle East and North Africa',   'Personal Care'),
            (                           'Europe',       'Beverages'),
            (                    'North America',       'Baby Food'),
            (                    'North America', 'Office Supplies'),
            ('Central America and the Caribbean',   'Personal Care'),
            (                             'Asia',       'Beverages'),
            (            'Australia and Oceania',   'Personal Care'),
            (     'Middle East and North Africa',       'Beverages'),
            (                    'North America',         'Clothes'),
            ('Central America and the Caribbean',       'Beverages'),
            (                    'North America',          'Cereal'),
            (                    'North America',            'Meat'),
            (                    'North America',          'Snacks'),
            (                    'North America',      'Vegetables'),
            (            'Australia and Oceania',       'Beverages'),
            (               'Sub-Saharan Africa',          'Fruits'),
            (                           'Europe',          'Fruits'),
            (                    'North America',   'Personal Care'),
            (                    'North America',       'Beverages'),
            (     'Middle East and North Africa',          'Fruits'),
            (                             'Asia',          'Fruits'),
            ('Central America and the Caribbean',          'Fruits'),
            (            'Australia and Oceania',          'Fruits'),
            (                    'North America',          'Fruits')],
           names=['대륙', '상품종류'])

In [ ]:
# 멀티 인덱스에서 첫번째 인덱스만 만족하는 조건식?
group_df.loc[ ('Europe', ),  ]

In [125]:
# 인덱스 초기화 하자 ( 기존의 인덱스는 유지 )
group_df.reset_index(inplace=True)

In [137]:
group_df.loc[group_df['대륙'] == 'Asia', ].index[0]

np.int64(7)

In [ ]:
group_df.loc[ [0, 3, 5],  ]    # 인덱스의 값이 0, 3, 5 인 데이터를 출력

In [ ]:
index_list = []
# 반복문을 이용해서 각 대륙의 데이터를 추출하고 그중 첫번째 데이터를 확인 
# 각각 대륙의 고유값 변수을 이용해서 반복문을 실행 
for name in group_df['대륙'].unique():
    # print(name)
    # group_df의 대륙 컬럼이 name과 같은 조건식을 생성 
    flag = group_df['대륙'] == name
    # print(group_df.loc[flag, ].head(1))   # 이 값들은 모두 group_df에 존재 
    # 인덱스들을 뽑아서 새로운 리스트로 만들면 -> loc를 이용해서 한번 에 확인이 가능
    index_list.append(
        group_df.loc[flag, ].index[0]
    )
index_list

In [139]:
group_df.loc[index_list, ]

                                   대륙       상품종류           총이윤
0                              Europe  Cosmetics  1.989963e+08
1                  Sub-Saharan Africa  Cosmetics  1.766093e+08
7                                Asia  Cosmetics  1.036069e+08
8        Middle East and North Africa  Household  1.025355e+08
14  Central America and the Caribbean  Household  8.873831e+07
18              Australia and Oceania  Cosmetics  6.760413e+07
54                      North America  Household  2.148805e+07

In [ ]:
# idxmax() 함수를 이용 -> value가 최대인 인덱스를 출력 
group_data5.sort_values('총이윤',ascending=False)

In [146]:
group_data5.idxmax()

총이윤    (Europe, Cosmetics)
dtype: object

In [149]:
group_data5.groupby(level=0).idxmax()

                                                                              총이윤
대륙
Asia                                                            (Asia, Cosmetics)
Australia and Oceania                          (Australia and Oceania, Cosmetics)
Central America and the Caribbean  (Central America and the Caribbean, Household)
Europe                                                        (Europe, Cosmetics)
Middle East and North Africa            (Middle East and North Africa, Household)
North America                                          (North America, Household)
Sub-Saharan Africa                                (Sub-Saharan Africa, Cosmetics)

In [ ]:
df2 = pd.pivot_table(
    df, 
    index = ['대륙', '상품종류'], 
    values = '총이윤', 
    aggfunc= 'sum'
)
df2

In [ ]:
# 상품의 종류가 몇개인가? 12개
df['상품종류'].unique()

In [154]:
df3 = df2.sort_values(['대륙', '총이윤'], ascending=False)
# sort_values() -> value를 기준으로 차순 정렬 
# pandas에서 sort_values에 인덱스를 넣어도 실행이 될수 있도록 업데이트 
# 구버전에서는 해당 함수가 실행이 되지 않을수 있다.

In [ ]:
for i in range(len(df3)):
    if i % 12 == 0:
        print(df3.iloc[[i], ])

# 주의할점 : sort_values()  함수에 인덱스 기준을 넣는거 (구버전 실행 불가)
#           모든 대륙에서 모든 상품의 종류 데이터가 존재하는지 확인하고 실행

In [164]:
df4 = df2.reset_index()
# 정렬에 기준이 되는 컬럼이 2개인데 하나는 오름차순 나머지 하나는 내림차순 정렬로 하는 방법은?
# 대륙으로는 오름차순(True), 총이윤으로는 내림차순(False)
df4.sort_values('총이윤', ascending=False, inplace=True)

In [166]:
# df4를 그룹화 -> 대륙을 기준으로 그룹화를 하고 
# 해당 데이터프레임들의 첫번째 데이터(상위 1개)만 추출 
df4.groupby('대륙').head(1).sort_values('대륙')

                                   대륙       상품종류           총이윤
4                                Asia  Cosmetics  1.036069e+08
16              Australia and Oceania  Cosmetics  6.760413e+07
30  Central America and the Caribbean  Household  8.873831e+07
40                             Europe  Cosmetics  1.989963e+08
54       Middle East and North Africa  Household  1.025355e+08
66                      North America  Household  2.148805e+07
76                 Sub-Saharan Africa  Cosmetics  1.766093e+08