### 데이터프레임간의 결합
- 일반적으로 데이터는 하나의 table로 저장이 되지 않는다.
    - 데이터는 분할 관리하는것이 일반적 (효율적)
    - 컬럼의 개수를 줄이고 인덱스를 늘리는 형태로 데이터 저장 관리
        - 데이터의 로드 속도가 올라간다.
- 대규모 데이터를 받아올때는 여러개의 파일로 구성

1. 유니온 결합
    - 단순하게 행이나 열을 결합하는 방법
    - pandas 에서는 concat() 함수를 이용하여 유니온 결합
    - 단순한 결합 형태이기 때문에 데이터프레임의 개수에 제한을 두지 않는다.
    - 예:
        - 2022년 데이터 + 2023년 데이터 + 2024년 데이터 + 2025년 데이터 (단순 행결합)
        - 아이디 / 패스워드 데이터 + 개인정보 데이터 (단순 열 결합) -> 추천X
    - pd.concat([데이터프레임1, 데이터프레임2, ...]) 
        - 매개변수
            - axis
                - 기본값 : 0(rows)
                - 행으로 결합할것인가? 열로 결합할 것인가?
            - ignore_index
                - 기본값 : False
                - True로 변경하면 결합이 되는 기준(axis 매개변수의 값)을 초기화
                - axis=0이라면 인덱스를 초기화(기존의 인덱스 제거)
                - axis=1이라면 컬럼을 초기화(기존의 컬럼명 제거)
2. 조인 결합
    - 특정한 조건에 맞게 데이터 간의 열을 결합하는 방식
    - 데이터프레임과 데이터프레임간의 조인 결합 -> 특정 컬럼의 데이터들이 같은 값들로 이루어져 있을때만 열을 추가하는 결합
    - pandas, DataFrame에 merge() 함수
    - 특정 조건에 맞춰서 열을 결합하기 때문에 데이터프레임은 2개 사용
    - pd.merge(데이터프레임1,데이터프레임2)
        - 매개변수
            - on
                - 조건 (두 개의 데이터프레임이 공통적으로 가진 데이터 컬럼의 이름)
                - 두 개의 데이터프레임에서 컬럼이 이름이 다른 경우
                    - 두 개의 데이터프레임을 로드하고 컬럼의 이름을 변경한 뒤 조인결합
                    - left_on, right_on 매개변수를 이용해서 각각의 컬럼명을 입력
                - how
                    - 어떻게 결합할것인가?
                    - inner : 두개의 데이터프레임이 공통적으로 가지고있는 데이터를 기준으로 결합
                    - left : 왼쪽 데이터프레임 (첫번째 인자)을 기준으로 결합
                    - right : 오른쪽 데이터프레임(두번째 인자)을 기준으로 결합
                    - outer : 두개의 데이터프레임 모든 데이터를 결합
    - DateFrame.merge(오른쪽 데이터프레임명)

In [1]:
import pandas as pd

In [3]:
_val={
    'id':['test','test2'],
    'password':['1111','2222']
}
df1=pd.DataFrame(_val)
df1

      id password
0   test     1111
1  test2     2222

In [4]:
_val2={
    'id':['test','test3','test4'],
    'name':['kim','park','lee']
}
df2=pd.DataFrame(_val2)
df2

      id  name
0   test   kim
1  test3  park
2  test4   lee

In [ ]:
# 유니온 결합 : concat() 함수를 이용 (단순 행 결합 / 열 결합)
pd.concat(
    [df1,df2],axis=0,ignore_index=True
)

      id password  name
0   test     1111   NaN
1  test2     2222   NaN
0   test      NaN   kim
1  test3      NaN  park
2  test4      NaN   lee

In [7]:
pd.concat(
    [df1,df2],axis=1, ignore_index=True
)

       0     1      2     3
0   test  1111   test   kim
1  test2  2222  test3  park
2    NaN   NaN  test4   lee

In [8]:
# concat()은 데이터의 구조가 같은 데이터 간의 결합으로 주로 사용

In [9]:
# 조인 결합
pd.merge(df1,df2,on='id',how='inner')

     id password name
0  test     1111  kim

In [10]:
pd.merge(df1,df2,on='id',how='left')

      id password name
0   test     1111  kim
1  test2     2222  NaN

In [11]:
pd.merge(df1,df2,on='id',how='right')

      id password  name
0   test     1111   kim
1  test3      NaN  park
2  test4      NaN   lee

In [12]:
pd.merge(df1,df2,on='id',how='outer')

      id password  name
0   test     1111   kim
1  test2     2222   NaN
2  test3      NaN  park
3  test4      NaN   lee