In [1]:
# 라이브러리 설치
# !pip install pandas

In [ ]:
# 라이브러리를 로드
import pandas as pd
# pandas 라이브러리를 로드하고 별칭은 pd로 사용하겠다 (pandas 키워드 사용 불가)
# pd가 회색으로 표시가 된다면 아직 사용된곳이 없다는 뜻임.

In [28]:
# 1차원 데이터인 스리즈 형태 생성
series_1=pd.Series([5000,6000,6500,6500])

In [5]:
series_1

0    5000
1    6000
2    6500
3    6500
dtype: int64

In [6]:
# Series 생성시 데이터만 입력하여 생성하면 인덱스는 0부터 1씩 증가하는 형태로 생성

In [7]:
# Series 에서 index를 추가하며 생성
series_2=pd.Series([5000,6000,6500,6500],
                   index=['아메리카노','카페라떼','카페모카','마끼아또'])

In [8]:
series_2

아메리카노    5000
카페라떼     6000
카페모카     6500
마끼아또     6500
dtype: int64

In [ ]:
# 특정 데이터에 접근하려면 index를 기준으로 데이터를 추출
series_2['아메리카노']
# 1차원 데이터 Series에서 필터의 값이 단일 데이터라면 -> 데이터 차원의 수는 1 감소
# 1차원 데이터 -> 단일 데이터(0차원 데이터)

np.int64(5000)

In [ ]:
# Series 안에는 변수가 적어도 2개가 존재 -> 클래스를 생성할때 2개의 데이터를 입력값으로 사용
# 그러면 클래스 안에 values, index 변수의 데이터를 수정이 가능한가? -> 수정 가능
# 만약에 Series에서 index의 값을 바꾸고 싶다.
# 클래스 안에 변수를 선택하여 다른 데이터를 대입 -> index의 개수와 같은 1차원 데이터를 대입
series_1.index=['a','b','c','d']

# index에 데이터가 대입이 된다 -> 원본의 Series 데이터가 변화

In [12]:
series_1

a    5000
b    6000
c    6500
d    6500
dtype: int64

In [ ]:
# index의 값을 변경하는 함수 존재 -> 함수 호출 시 출력이 확인 가능 -> 원본의 데이터는 유지
# inplace 쓰면 원본 데이터가 바뀜. 안쓰면 원본데이터는 변경되지 않음
# 근데 좀 조심히 써야함
series_1.rename(
    index={
        'b':'뿡'
    }, inplace=True
)

In [19]:
series_1=series_1.rename(
    index={
        '뿡':3
    }
)

In [ ]:
# 위 두개는 원본 데이터를 변경하는건데 위의 내용을 쓰다가 아래처럼 잘못 쓰면 난감해짐.
# 잘못된 코드.
# rename()함수에 inplace=True라면 원본의 데이터를 수정하고 되돌려주는 데이터는 없다.
series_1=series_1.rename(
    index={
        'c':5
    },inplace=True
)

# 위처럼만 안쓰고 잘 사용하면 백업본 만들고 뭐하고 해서 잘 쓸 수 있는것 같다.

In [30]:
series_1

In [31]:
series_2

아메리카노    5000
카페라떼     6000
카페모카     6500
마끼아또     6500
dtype: int64

In [32]:
# Series에서 values의 타입들이 각각 다르다면 dtype은 뭐라고 나올것인가?
series_3=pd.Series([1,'kim',True])

In [34]:
series_3

0       1
1     kim
2    True
dtype: object

In [35]:
# Series에는 2개의 변수가 존재
# values, index
print(series_2.index)
print(series_2.values)

Index(['아메리카노', '카페라떼', '카페모카', '마끼아또'], dtype='str')
[5000 6000 6500 6500]

In [ ]:
series_2.index[1] = '오곡라떼'

'카페라떼'

In [ ]:
# values의 데이터를 수정
# series_2.values[1]=6300   수정이 불가능
series_2['카페라떼'] = 6300
# 클래스 안에 변수를 통해서 일부의 데이터를 추출하면 수정이 불가능

In [43]:
series_2

아메리카노    5000
카페라떼     6300
카페모카     6500
마끼아또     6500
dtype: int64

In [44]:
# Series와 DataFrame 모두 pandas 안에 있는 클래스 -> 사용하는 함수들도 같은 함수
# DataFrame은 Series를 상속 받아서 사용
# rename() -> Series에서는 index의 값을 변경할때 사용
                # DataFrama에서 index의 값과 columns의 값을 모두 변경이 가능
df.rename(columns={
    'C':'D'
})

NameError: name 'df' is not defined

In [45]:
df

NameError: name 'df' is not defined

In [46]:
df2

NameError: name 'df2' is not defined

In [47]:
df3=df3

NameError: name 'df3' is not defined

In [48]:
df3

NameError: name 'df3' is not defined

In [49]:
df3.rename(index={
    0:10
},inplace=True)

NameError: name 'df3' is not defined

In [50]:
df

NameError: name 'df' is not defined

In [51]:
# Series, DataFrame도 list와 같이 =을 이용해서 복사를 하게 되면 얕은 복사(같은 주소를 사용)
df4=df.copy()

NameError: name 'df' is not defined

In [ ]:
df4.rename(index={
    10:0
},inplace=True)

NameError: name 'df4' is not defined

In [53]:
df4

NameError: name 'df4' is not defined

In [54]:
df

NameError: name 'df' is not defined

In [ ]:
# 함수를 이용해서 DataFrame를 수정한다.
def func_1(data):
    # 입력 받은 데이터프레임을 수정하지 않으려면 (원본 유지) copy() 함수를 이용하여 데이터를 복사
    result=data.copy()
    # 컬럼의 이름을 변경한다.  
    # rename 함수를 이용한다 --> 특정 컬럼의 이름을 변경할때 사용 // DataFrame.columns 변수를 선택해서 변경 (컬럼의 개수와 같은 데이터를 대입) --> 모든 컬럼의 이름을 변경할 때 사용
    result.columns=['A','B','C']
    return result

In [ ]:
func_1(df2)
# func_1() 함수가 처음 하는 일이 data=df
# data의 컬럼의 이름을 변경 -> df의 컬럼의 이름이 변경이 된다

NameError: name 'df' is not defined

In [57]:
df2

NameError: name 'df2' is not defined

#### pandas 라이브러리에서 외부의 데이터를 로드하는 함수들
- csv, tsv
    - 가장 단순한 형태의 데이터 파일
    - pandas에 내장된 read_csv() 함수를 이용해서 데이터 로드
    - csv는 데이터를 ','기준으로 나눠준다.
        - read_csv(경로)를 이용하여 로드
    - tsv는 데이터를 '\t' (탭) 기준으로 나눠준다.
        - read_csv() 함수에서 매개변수 sep 매개변수에 인자값을 '\t'로 설정
- json 
    - 많이 사용이 되는 데이터 파일 (특히 웹에서 많이 사용)
    - python으로 생각하면 dict 형태와 같다.
    - pandas에서 read_json() 함수를 이용하여 데이터 로드
- xml
    - html 구조 언어와 같이 tag를 이용해서 데이터가 구성
        - ex) <data>'abc'</data>
    - pandas에서 read_xml() 함수를 이용하여 데이터 로드
- 위의 3개의 read_xxx() 함수들은 공통적으로 encoding이라는 매개변수를 가지고 있다.
    - 기본값은 'UTF-8' 
    - 데이터 파일을 로드하는데 해당 데이터셋에 한글이 존재하는 경우에 종종 에러가 발생(decode error)
        - 인자값을 'CP949'라는 엔진을 사용하거나, 'EUC-KR'로 사용하면 데이터 로드가 가능
    - 엑셀 파일을 로드하는 함수에는 encoding 매개변수가 존재하지 않는다.
- excel (xls,xlsx)
    - 엑셀 데이터 파일
    - pandas 안에서 read_excel() 함수를 이용해서 데이터 로드
    - 특정 엑셀 파일을 로드 할때 추가적인 라이브러리 설치가 필요한 경우가 존재
        - 특정 라이브러리가 존재하지 않는다면 모듈을 찾을 수 없습니다. 라는 에러가 발생
            - 에러 발생시 해당 라이브러리 설치 (openpyxl)
- 모든 read_xxx() 함수에서 첫번째 인자값은 파일의 경로를 입력

#### 경로
- 절대 경로
    - 절대적인 주소 값
    - 환경이 변하더라도 같은 위치를 언제나 지정
    - ex
        - url -> https://www.google.com
        - window -> c:/users/admin/document/a.txt
        - mac -> ~/Desktop/a.txt
- 상대 경로
    - 상대적인 주소 값
    - 환경이 변할때 위치도 변한다.
    - 종류
        - ./ -> 현재 작업중인 경로 (내가 지금 수정하고 있는 파일의 위치) - 생략 가능
        - ../ -> 현재 작업중인 경로에서 상위 경로로 이동
        - 폴더명/ -> 하위 폴더로 이동

In [60]:
# 절대 경로를 이용하여 데이터 팡일을 로드
# 절대 경로를 윈도우 메뉴로 복사하는 경우 에러가 발생 (\)
# 그런 경우 경로 앞에 r 쓰면 \를 경로로 사용하겠다 라는 뜻.
df = pd.read_csv(r"C:\Users\admin\Desktop\새 폴더\Study\MultiCampus\csv\corona.csv")

In [61]:
# 상대 경로를 이용해서 데이터 파일을 로드
# 현재 파일 경로(./) 에서 상위로 이동(../) -> csv 하위 폴더로 이동 (csv/) -> corona.csv 선택

df2=pd.read_csv("./../csv/corona.csv")

In [63]:
# 데이터들의 상위 5개 출력
# head(n) -> 기본값으로 5개, 개수를 변경하려면 인자에 원하는 숫자를 넣어주면 됨.
df.head(3)

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN

In [65]:
# 데이터의 마지막 N개를 출력한다.
# tail(n)
df.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [67]:
# 데이터의 정보를 출력하는 함수
# info() -> 데이터프레임의 정보를 출력
df.info()
# 여기서 나오는 Null은 "결측치: 데이터 없는것."
# 817 692 623 에는 해당하는 결측치가 존재합니다. 라는 뜻

<class 'pandas.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  820 non-null    int64
 1   createDt    820 non-null    str
 2   deathCnt    820 non-null    int64
 3   decideCnt   820 non-null    int64
 4   seq         820 non-null    int64
 5   stateDt     820 non-null    int64
 6   stateTime   820 non-null    str
 7   updateDt    817 non-null    str
 8   accExamCnt  692 non-null    float64
 9   accDefRate  623 non-null    float64
dtypes: float64(2), int64(5), str(3)
memory usage: 64.2 KB

In [73]:
# 결측치 -> 데이터가 없다.
# 원인1. 데이터가 손상이 생겼다.
# 원인2. 데이터베이스에서 해당 데이터가 입력이 되지 않았다.
# 결측치는 주요 확인을 해야한다. (info() 함수를 이용하여 non-null count 확인)
# 결측치를 찾는 함수가 존재함. (결측치: na // nan, 존재 유무 : isna())
# 결과 값 bool 형태를 합산 -> 인덱스를 기준으로 합산 // 컬럼을 기준으로 합산. (sum()) -> 인자값을 변경하면 인덱스를 기준으로 합산 (매개변수는 축(axis))
# axis의 기본값 (rows) : 인덱스의 값들을 합산
# axis를 columns로 변경하면 : 컬럼의 값들을 합산
df.isna().sum(axis='rows')
# False는 결측치가 아닌것, True는 결측치인것.

Unnamed: 0      0
createDt        0
deathCnt        0
decideCnt       0
seq             0
stateDt         0
stateTime       0
updateDt        3
accExamCnt    128
accDefRate    197
dtype: int64

In [ ]:
# 특정 컬럼에 결측치가 존재하는가?
# sum() 합, any() or이랑 같음.
# and로 묶는 부분은 잘 쓰지 않지만, all() 사용하여 해결할 수 있음.
# axis=1 하면 index를 기준으로 만들어진다.
# any() True가 하나라도 존재하면 True (논리연산자 or)
df.isna().any(axis=1)

0       True
1       True
2       True
3       True
4       True
       ...
815    False
816    False
817    False
818    False
819    False
Length: 820, dtype: bool

In [81]:
# all() 모든 값이 True라면 True (논리연산자 And)
df.isna().all()

Unnamed: 0    False
createDt      False
deathCnt      False
decideCnt     False
seq           False
stateDt       False
stateTime     False
updateDt      False
accExamCnt    False
accDefRate    False
dtype: bool

In [ ]:
# is : 존재의 유무, in : 포함여부
# isna() 는 결측치의 존재 유무 였다면 (함수명에 어떤 데이터를 찾을것인가가 지정 -> 인자 없어도 구동 가능)
# isin()은 특정 데이터가 포함되어있는가? (1차원 데이터셋이 필수 인자)

In [83]:
# 통계 요약 정보를 출력하는 함수
# describe() --> Dtype이 숫자형인 데이터들의 통계 정보를 출력
df.describe()

# 이상치: 이상한거. 정해진 숫자가 1,2,9인데 5가 나오면 이상하잖아. 이게 이상치임.

,Unnamed: 0,deathCnt,decideCnt,seq,stateDt,accExamCnt,accDefRate
count,820.000000,820.000000,8.200000e+02,820.000000,8.200000e+02,6.920000e+02,623.000000
mean,409.500000,3927.832927,1.913097e+06,472.393902,2.020897e+07,7.545057e+06,1.556435
std,236.857904,6164.310693,4.857030e+06,249.701095,7.118265e+03,6.172020e+06,0.543014
min,0.000000,54.000000,7.513000e+03,51.000000,2.020031e+07,2.101440e+05,0.902205
25%,204.750000,415.750000,2.393525e+04,256.750000,2.020100e+07,1.934309e+06,1.078089
50%,409.500000,1812.500000,1.185640e+05,461.500000,2.021042e+07,6.368310e+06,1.416159
75%,614.250000,3120.500000,3.979915e+05,698.250000,2.021112e+07,1.216890e+07,1.816009
max,819.000000,24305.000000,1.818820e+07,904.000000,2.022061e+07,2.151807e+07,3.919308

In [ ]:
# tsv 파일을 로드
# 현재 경로(./) -> 상위로 이동(../) -> csv 폴더로 이동(csv/) -> num_1 폴더로 이동(num_1/) -> chipotle.tsv
# tsv는 sep='\t' 필수
chipotle=pd.read_csv(
    '../csv/num_1/chipotle.tsv', sep='\t'
)

In [91]:
chipotle.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [94]:
# 주민등록.csv 파일을 로드
df3=pd.read_csv("../csv/주민등록.csv",encoding="cp949")

In [98]:
# 상위로 이동 -> csv 폴더로 이동 -> 2022 폴더로 이동 -> 202202_expense_list.json 로드
df4=pd.read_json("../csv/2022/202202_expense_list.json")

In [99]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.4-cp314-cp314-win_amd64.whl.metadata (3.2 kB)
Downloading lxml-6.0.4-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -------------------------------------- - 3.9/4.1 MB 59.3 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 51.8 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.4

In [101]:
# lxml 에러 --> lxml 라이브러리 설치 필요 (위에서 install 함)
df5=pd.read_xml("../csv/2022/202202_expense_list.xml")

In [ ]:
# !pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [105]:
# 엑셀 파일 로드
# ImportError: Import openpyxl (openpyxl 라이브러리 설치 필요)
df6=pd.read_excel("../csv/2022/202202_expense_list.xlsx")

In [106]:
# 결측치 -> 처리
import numpy as np

In [108]:
# 넘파이를 로드하는 이유 -> 결측치 데이터가 생성이 가능
_value = [
    [1,2,np.nan,4,5],
    [1,np.nan,3,4,5],
    [1,2,3,4,np.nan]
]
_cols=['a','b','c','d','e']

df=pd.DataFrame(_value,columns=_cols)
df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [110]:
# 결측치는 연산이 되지 않는다. (결측치의 연산은 언제나 결측치로 만들어진다.)
# 아래처럼 하면 무조건 결측치가 만들어짐
3*np.nan

nan

In [111]:
3+np.nan

nan

In [ ]:
# 결측치를 확인한다 라는 과정은 isna() 를 사용한다.
# 결측치와 결측치는 같은가? 라는 코드를 실행해본다.
np.nan==np.nan

False

In [113]:
# 위 코드를 실행했더니 False가 나온다. (결측치는 무조건 같지 않다라고 나온다.) 
# 그래서 isna()라는 함수가 만들어졌다. 
# 근데 pandas에서는 데이터 연산을 할때 결측치를 제외하고 연산이 된다.
# R이라는 언어에서는 결측치가 포함된 데이터셋을 연산을 하면 결측치가 만들어진다.
# pandas에서는 결측치를 제외하고 연산을 한다.
df.sum()

a     3.0
b     4.0
c     6.0
d    12.0
e    10.0
dtype: float64

In [ ]:
# 데이터프레임에 비교연산자를 사용하면?
df == 1
# 각각의 데이터들을 true false로 계산해서 아래와같이 결과값이 나온다.

      a      b      c      d      e
0  True  False  False  False  False
1  True  False  False  False  False
2  True  False  False  False  False

In [ ]:
# 그냥 결측치와 같은가 라고 물어보면
df==np.nan
# 모든 데이터가 False가 나온다.

       a      b      c      d      e
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False

In [ ]:
df.isna()
# 정확하게 결측치를 찾아서 true라는 결과값을 준다. 

# 결측치는 같다 라는 비교연산자로 결측치를 찾아내지 못하기 때문에 isna()를 사용한다.

       a      b      c      d      e
0  False  False   True  False  False
1  False   True  False  False  False
2  False  False  False  False   True

#### 결측치의 처리
1. 결측치 데이터를 제거
    - 결측치가 포함되어있는 컬럼을 제거
        - 해당 컬럼의 데이터가 중요하지 않은 경우
    - 결측치가 포함되어있는 인덱스를 제거한다. (지우는 경우)
        - 결측치가 포함되어있는 인덱스의 수가 전체 데이터의 수보다 일반적으로는 5% 미만인 경우
        - 결측치가 포함된 인덱스의 데이터 신뢰도가 떨어지는 경우
    - 결측치를 제거하는 함수
        - 결측치(na) + 버리다/지우다(drop)
    - dropna()
        - 매개변수 axis : 기준이 되는 축 지정 기본 값은 rows (=0)
            - 결측치가 포함되어 있는 인덱스를 제거한다.
            - 값을 columns나 1로 변경하면 결측치가 포함된 컬럼을 제거한다.
        - 매개변수 inplace : 기본값은 False
            - 원본 데이터(class 내부에 저장된 변수 데이터)를 변경할 것인가 지정
            - True면 원본 데이터가 수정이 되고, 기본값이면 그냥 확인.
2. 결측치를 특정한 값으로 채워준다
    - 채우다(fill) + 결측치(na)
    - fillna()
        - 인자에 특정 데이터를 입력한다 라고 하면, 
            - 결측치가 해당 인자 값으로 치환이 된다 라고 보면 된다.
        - 매개변수 method 사용
            - ffill : fornt fill -> 결측치 전의 데이터로 채워준다.
            - bfill : back fill -> 결측치 뒤의 데이터로 채워준다.

In [119]:
# 결측치를 제거
# 결측치가 포함된 인덱스를 제거 --> 모든 인덱스가 제거된다. (axis='rows' 또는 0)
# 결측치가 포함된 컬럼을 제거 --> a, d 컬럼을 제외한 모든 컬럼이 제거된다. (axis='columns' 또는 1)
df.dropna(axis='columns')
# axis='rows' 인덱스 3개가 다 사라지고, 컬럼만 남는다.
# axis='columns'

   a  d
0  1  4
1  1  4
2  1  4

In [121]:
df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [122]:
# 결측치를 채운다 fillna()
df.fillna(10)

   a     b     c  d     e
0  1   2.0  10.0  4   5.0
1  1  10.0   3.0  4   5.0
2  1   2.0   3.0  4  10.0

In [ ]:
# 전 인덱스의 데이터로 결측치를 채워준다.
# 전 인덱스가 없으면 그냥 안채움
df.ffill()

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  5.0

In [129]:
# 후 인덱스가 없으면 그냥 안채움
df.bfill()

   a    b    c  d    e
0  1  2.0  3.0  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [ ]:
# 컬럼별 결측치를 다른 값으로 대체
# fillna() 사용 -> 데이터프레임.fillna() : 데이터 프레임의 결측치로 채운다. (이러면 모든 데이터프레임의 결측치로 채워버림)
# 특정 컬럼은 선택한 Series//DataFrame에 fillna()를 사용
# 데이터프레임에서 특정 b컬럼을 선택하고 결측치를 채운다.
# df['b'].fillna(20, inplace=True)
df['b']=df['b'].fillna(20)

In [140]:
df

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

#### 데이터프레임의 필터
- 데이터프레임명.loc[ 인덱스의 조건식, 컬럼의 조건식 ]
    - 인덱스의 값을 기준으로 필터 (인덱스가 같은 경우에만 (True) 출력)
    - 컬럼의 값을 기준으로 필터 (컬럼이 같은 경우에만 (True) 출력)
    - 시작 : 종료 -> 시작값부터 종료값까지 (종료값 포함)
- 데이터프레임명.iloc[인덱스의 위치, 컬럼의 위치]
    - 인덱스의 위치를 기준으로 필터
    - 컬럼의 위치를 기준으로 필터
    - 시작 : 종료 -> 시작 위치부터 종료 위치 전까지 (종료 위치는 미포함)
- 특정 컬럼의 데이터를 확인
    - 데이터프레임 [단일 컬럼] -> 조건이 단일이라면 데이터프레임은 스리즈로 변환하여 추출
    - 데이터프레임 [[컬럼1,컬럼2,...]] -> 조건이 복수의 타입 (리스트나 튜플)이라면 데이터프레임으로 추출

In [142]:
df

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

In [143]:
# loc를 이용하여 필터
# 인덱스의 값이 0부터 2까지
df.loc[0:2,]

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

In [144]:
df.iloc[0:2,]

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0

In [147]:
# 인덱스의 조건이 단일인 경우 -> 차원이 1개 축소
df.index=['A','B','C']

In [152]:
# 컬럼의 조건식 a 인덱스의 조건식은 시작부터 끝까지
df.loc[:,['a']]

   a
A  1
B  1
C  1

In [155]:
flag=df['b']==2.0

In [157]:
df.loc[flag,]

   a    b    c  d    e
A  1  2.0  NaN  4  5.0
C  1  2.0  3.0  4  NaN

In [171]:
# 결측치가 포함되어있는 데이터를 확인
# 인덱스의 조건식으로 결측치가 포함되어있는가?
flag_null=df.isna().any(axis=1)

In [172]:
# 결측치가 포함되어있는 데이터 필터링
df.loc[flag_null,]

   a    b    c  d    e
A  1  2.0  NaN  4  5.0
C  1  2.0  3.0  4  NaN

In [173]:
# 결측치가 포함되어 있지 않은 데이터를 확인
# not() -> 부정 함수 -> T을 F, F을 T로 변경 -> 스리즈에서는 사용이 불가능하다.
# not(flag_null) //여기선 사용이 불가능함.
# 스리즈에서 데이터들을 모두 부정처리 하는 방법
# 음수처리하기
# -flag_null
# 비트연산자(~) 사용 -> 2진수의 0과 1을 뒤집는다.
# TFT -> 101 (비트연산자를 사용) -> 010
~flag_null

A    False
B     True
C    False
dtype: bool

In [176]:
# 반복문을 이용하여 Series의 value들을 부정
# Series 안에는 2개의 변수 확인 index, values
# values 데이터들을 하나씩 추출하여 not() 함수를 이용해서 부정 처리
for i in flag_null:
    # print(not(i))
    flag_list.append(not(i))
flag_list

NameError: name 'flag_list' is not defined

In [178]:
df.loc[flag_list,]

NameError: name 'flag_list' is not defined

In [180]:
# map() -> 1차원 데이터를 각각 원소별 변환이 필요할 때 사용하는 함수
# map(함수, 1차원데이터)

list_1=[1,2,3,4]

def func_1(x):
    return x ** 2

list(
    map(
        func_1, list_1
    )
)

[1, 4, 9, 16]

In [181]:
# map() + lambda 함수
# lambda 함수 : 이름 없는 함수(단순한 계산식을 사용할때 사용함, 휘발성함수-한번사용하면 사라진다고 봐야함)
# lambda 매개변수 : 매개변수의 연산

list(
    map(
        lambda x : x ** 2,
        list_1
    )
)

[1, 4, 9, 16]

In [ ]:
# Serise 안에 map() 함수가 존재한다. 
flag_null.map(
    # x라는 매개변수에는 True, False, True 순차적으로 입력
    lambda x: not(x)
)
# lambda 함수는 연산이 간단한 경우에만 사용

A    False
B     True
C    False
dtype: bool

In [184]:
def func_2(x):
    return not(x)

flag_null.map(
    func_2
)

A    False
B     True
C    False
dtype: bool