#### 웹 크롤링
- 라이브러리
    - requests
        - 웹 서버에 요청을 보내고 응답을 받는 기능
        - 응답 데이터는 bytes, string형으로 들어온다
    - bs4
        - BeautifulSoup class를 이용
        - html로 이루어진 문자 데이터를 pasing 작업을 통해서 데이터의 타입을 변경하여 내부의 데이터에 쉽게 접근하여 추출하기 위한 기능
            - `"<html><body><p>Text</p></body></html>"` -> 태그를 기준으로 데이터에 접근할 수 있는 함숟들이 존재
        - 웹의 기본 구조를 파악을 하고 사용을 하면 조금 더 쉽게 접근이 가능하다.
            - 태그 별 속성의 값
            - 태그의 특징
    - selenium
        - 웹 어플리케이션을 테스트하기 위한 라이브러리
        - 웹 브라우저(chrome, ...)를 python code를 이용하여 제어
            - 함수를 이용해서 특정 버튼을 클릭
            - 특정 위치에 데이터를 입력
        
        - 구글 크롬의 버전이 구버전인 경우 별도의 소프트웨어를 설치가 필요
- 데이터를 불법적으로 가지고 오는 방법 (합법/위법 사이)
    - 사이트들마다 크롤링이 가능한 주소들은 지정
    - 상업적인 용도가 아닌 수업에서의 내용은 큰 지장은 없음

In [1]:
# !pip install bs4 selenium

In [2]:
import requests
from bs4 import BeautifulSoup as bs

In [3]:
# requests 라이브러리를 이용해서 openapi에서는 데이터의 결과물이 xml, json 형태
# https://www.naver.com 에 요청을 보냈을때 어떤 데이터를 줄것인가?
res = requests.get("https://www.naver.com")
# requests.get() https 프로토콜을 이용해서 요청을 보낼 때 에러가 발생하는 경우 -> http 쓰면 됨.

In [4]:
res.content

b'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta property="og:title" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta name="twitter:card" content="summary"> <meta name="twitter:title" content=""> <meta name="twitter:url" content="https://www.naver.com/"> <meta name="twitter:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta name="twitter:description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta name="google-site-verification" content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g"/> <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?1"> <link rel="apple-touch-icon-precomposed" href="https://s.pstatic.net/static/www/nFavicon96.png"/> <link rel="apple-touch-icon" sizes="114x114" href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png"/> <link rel="apple-touch-icon" href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png"/> <link rel="stylesheet" href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_260205.css"> <link rel="canonical" href="https://www.naver.com/"> <link rel="alternate" media="only screen and (max-width: 767px)" href="https://m.naver.com/"> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js" defer="defer"></script>  <script>\nwindow["EAGER-DATA"] = window["EAGER-DATA"] || {};\nwindow["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"\xed\x95\x9c\xeb\xb0\x98\xeb\x8f\x84 \xeb\x8d\xae\xec\xb9\x9c \xec\xb5\x9c\xec\x95\x85 \xed\x99\xa9\xec\x82\xac\xe2\x80\xa6\\"\xea\xb8\xb0\xec\xb9\xa8 \xeb\xb0\xa9\xec\xb9\x98\xed\x96\x88\xeb\x8b\xa4\xea\xb0\x84 \xed\x8f\x90\xeb\xa0\xb4 \xec\xa7\x84\xed\x96\x89\xeb\x90\xa0 \xec\x88\x98\xeb\x8f\x84\\"","url":"https://n.news.naver.com/article/421/0008901749","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F421%2F2026%2F04%2F21%2F0008901749_001_20260421094530050.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/421","name":"\xeb\x89\xb4\xec\x8a\xa41","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F421%2F2025%2F03%2F07%2Flogo_421_100_20250307145710.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5eb"},{"@type":"MATERIAL-PC-FEED","title":"\\"\xec\x95\x85\xec\x96\xb4 \xed\x82\xac\xeb\x9f\xac\xec\x9d\x98 \xeb\x93\xb1\xec\x9e\xa5?\\" \xeb\xac\xbc\xec\x86\x8d\xea\xb9\x8c\xec\xa7\x80 \xec\x9e\xa0\xec\x9e\x85\xed\x95\xb4 \xec\x88\xa8\xed\x86\xb5 \xeb\x81\x8a\xeb\x8a\x94 \xec\x95\x84\xeb\xa7\x88\xec\xa1\xb4\xec\x9d\x98 \xec\xa7\x84\xec\xa0\x95\xed\x95\x9c \xec\xa3\xbc\xec\x9d\xb8","url":"https://in.naver.com/lyuiopiiy/contents/internal/937734327589184","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDRfMzYg%2FMDAxNzc1MjM5NTI3MDcx.mgMexLOS1DsAbaHMUixNTylxwv5ms_anpJJZ1pfEfm0g.NpY-yxW96fOYvGSnnjuybfO7iKpNPjy6OzGGfRPyh_Ag.JPEG%2F%EC%9E%AC%EA%B7%9C%EC%96%B4_3.JPG%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/lyuiopiiy","name":"\xea\xbc\xac\xeb\x8c\x80\xec\x9e\xa5","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA5MzBfMTEz%2FMDAxNzI3NzA2MjE5MzU2.8MhXsoFypqirc-S75MzGJaJXHivJ_fJnOeS4JL_4Yk4g.NNq5sdrig5r8NHGk2SOZPP-EdeyM9myFZT_99yVlG-gg.PNG%2F%25EB%25A7%25B9%25EA%25B5%25AC%25EA%25BC%25AC%25EB%2593%25A4%25EA%25BC%25AC%25EB%25B3%25B5%25EA%25BC%25AC%25EC%2588%259C.png%2F%25EB%25A7%25B9%25EA%25B5%25AC%25EA%25BC%25AC%25EB%2593%25A4%25EA%25BC%25AC%25EB%25B3%25B5%25EA%25BC%25AC%25EC%2588%259C.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5ec"},{"@type":"MATERIAL-PC-FEED","title":"\xec\xb5\x9c\xea\xb7\xbc \xec\xa0\x84 \xec\x84\xb8\xea\xb3\x84\xeb\xa5\xbc \xeb\x92\xa4\xec\xa7\x91\xec\x9d\x80, \xec\xba\x90\xeb\x82\x98\xeb\x8b\xa4\xec\x97\x90\xec\x84\x9c \xed\x8f\xac\xec\xb0\xa9\xeb\x90\x9c \xec\x82\xb4\xec\x95\x84\xec\x9e\x88\xeb\x8a\x94 \xea\xb3\xb5\xeb\xa3\xa1?","url":"https://in.naver.com/tamsatube/contents/internal/942081262279008","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTZfODMg%2FMDAxNzc2MzAwOTIzNDk1.oxiIU7TYUyS8uydVNMO4Iys9fC9gZM4fmpMlLAmZrYUg.wi0TO8I5TGAttcaMrPLhIQmeXQyWsl2CbQVaPrG2Ji0g.PNG%2Fimage.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/tamsatube","name":"\xed\x83\x90\xec\x82\xac\xed\x8a\x9c\xeb\xb8\x8c","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjA0MTRfMjYg%2FMDAxNzc2MTMwMjg5Mzkw.CMCLhfigVUHd0g6eKpXHnPUrapx5_3JgLEI3DiJ6Dbsg.pmwyjmvc8S7zEc1dm-4jV-WaWOARBO7H9B6bseE0zdgg.PNG%2F%25EB%25A1%259C%25EA%25B3%25A0.png%2F%25EB%25A1%259C%25EA%25B3%25A0.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5ed"},{"@type":"MATERIAL-PC-FEED","title":"\xec\xa4\x91\xea\xb0\x84\xec\x9d\xb4 \xec\x97\x86\xeb\x8a\x94 \xed\x95\x9c\xea\xb5\xad\xec\x9d\xb8\xeb\x93\xa4","url":"https://tv.naver.com/h/97744747","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260415_177%2F9DO7d_1776222233831VJkaL_JPEG%2FVxtWl86BOU_03.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/tpwndksl11","name":"\xec\xa7\x80\xec\x8b\x9d\xec\x9d\xb8\xec\x82\xac\xec\x9d\xb4\xeb\x93\x9c \xec\x87\xbc\xec\xb8\xa0","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240125_221%2F4XqBh_1706148115735pLHLm_PNG%2F1706148115717.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:02"},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5ee"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\x82\xb4 \xeb\x8f\x88 \xeb\xba\x8f\xec\x9c\xbc\xeb\xa0\xa4\xeb\x8a\x94 \xec\x82\xac\xea\xb8\xb0\xea\xbe\xbc \xea\xb1\xb0\xeb\xa5\xb4\xeb\x8a\x94 \xeb\xb2\x95\xf0\x9f\x91\x8a\xf0\x9f\x8f\xbb","url":"https://tv.naver.com/h/98076284","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260420_103%2FO4sbH_1776659647484UBXBR_JPEG%2FbMZMcbPR8D_10.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/kbsjoy","name":"KBSJoy","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20250325_77%2FlG6o2_1742884877613ePq5o_JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:48"},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5ef"},{"@type":"MATERIAL-PC-FEED","title":"\xec\x9c\xa0\xeb\x8f\x85 \xec\x83\x9d\xed\x99\x9c\xeb\xa0\xa5 \xeb\x96\xa8\xec\x96\xb4\xec\xa7\x80\xeb\x8a\x94 \xec\xa4\x91\xeb\x85\x84 1\xec\x9d\xb8 \xea\xb0\x80\xea\xb5\xac\xec\x9d\x98 \xed\x98\x84\xec\x8b\xa4","url":"https://tv.naver.com/h/98075586","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260420_55%2FWYzaM_17766591297501Er4X_JPEG%2Ffhu7b75zzf_05.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/papervore","name":"\xec\xb1\x85\xec\x8b\x9d\xec\xa3\xbc\xec\x9d\x98","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20190703_178%2FNPfdv_1562129618733J4gum_PNG%2F1562129618709.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:28"},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5f0"},{"@type":"MATERIAL-PC-FEED","title":"\'\xeb\xad\x94\xea\xb0\x80 \xec\x8e\x84\xed\x95\x9c\xeb\x8d\xb0..\' \xea\xb2\x89\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\xb0\xa9\xed\x95\xb4\xeb\xb3\xb4\xec\x97\xac\xeb\x8f\x84 \xec\xa7\x84\xec\xa7\x9c \xec\xa1\xb0\xec\x8b\xac\xed\x95\xb4\xec\x95\xbc \xeb\x90\xa0 \xec\x82\xac\xeb\x9e\x8c \xed\x8a\xb9\xec\xa7\x95 4\xea\xb0\x80\xec\xa7\x80","url":"https://in.naver.com/ryuae4/contents/internal/939486943819616","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDhfNTkg%2FMDAxNzc1NjQ2ODE3NDgx.dATXdO88ffSAWxbeXxSkcGyiKzYkG4DPipqrqnGkGcUg.OZjPUjfXS8zEq-gMZYtj8LrnvPkfyZreuRipHsxpsTAg.PNG%2F%EC%8D%B8%EB%84%A4%EC%9D%BC1.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/ryuae4","name":"\xeb\xa5\x98\xec\x95\xa0","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMTA2MDRfMjIg%2FMDAxNjIyNzcxMTQ2ODA3.Dxo4Yy37yNTJJZel2534yWknyt4DFXLuH0DUkxuM2fsg.4DKptb4ofGotq4mt7a4fE0uJtQEY2nYruBkLla1Ms-4g.JPEG.ryuae4%2F%25EB%25A5%2598%25EC%2595%25A0%2B%25EC%259D%25B4%25EB%25A6%2584.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5f1"},{"@type":"MATERIAL-PC-FEED","title":"\xec\x9d\xb8\xea\xb0\x84\xea\xb4\x80\xea\xb3\x84\xec\x97\x90\xec\x84\x9c \xed\x95\x9c\xeb\xb2\x88 \xe2\x80\x9c\xec\x95\x84\xeb\x8b\x88\xeb\x8b\xa4\xe2\x80\x9d \xec\x8b\xb6\xec\x9c\xbc\xeb\xa9\xb4 \xeb\xb0\x94\xeb\xa1\x9c \xec\x86\x90\xec\xa0\x88\xed\x95\x98\xeb\x8a\x94 \xec\x82\xac\xeb\x9e\x8c \xed\x8a\xb9\xec\xa7\x95","url":"https://blog.naver.com/smallbigmedia/224246296524","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDlfNzEg%2FMDAxNzc1NzAzNzYzNjQx.L-X4PeG4eLIRZEUM4c1Wj6TFU5foWcT-3KLZdMym3J0g.b0rvJJ9ecA_5QI1NQ0ZdS8hhQ0M7_HTvFvDlD0cbg1Ug.JPEG%2Ftask_01knr2een4e0msfzjdjkbhdzw1_1775703139_img_0.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/smallbigmedia","name":"\xec\x98\xa4\xeb\xb6\x84\xec\x84\x9c\xea\xb0\x80","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA4MTZfMTEw%2FMDAxNzIzNzY3NzMzMDgz.Exh4EqrRgfeJDl8PhBFllgobLnmIDRUK189OMQB6s9sg.zH3FhgWXEcZz0XJlFgEZEnQJx2iQKx6a1wcz9K0KICQg.PNG%2Fgjhkjhk.png%2Fgjhkjhk.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"68a6cf09a173986b7a52e5f2"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-LECTURE-AIRS-0","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"\\"\xec\x95\x84\xed\x8c\x8c\xec\x84\x9c \xeb\xaf\xb8\xec\x95\x88\xed\x95\xb4\\" \xec\x8b\xa0\xea\xb2\xbd\xec\x84\xac\xec\x9c\xa0\xec\xa2\x85 \xec\x97\x84\xeb\xa7\x88\xec\x9d\x98 \xea\xb0\x80\xec\x8a\xb4 \xec\x95\x84\xed\x94\x88 \xec\x82\xac\xeb\x9e\x91","url":"https://happybean.naver.com/donations/H200000007493?p=p&s=nmkp","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fhappybean-phinf.pstatic.net%2F20260402_254%2F1775120933351NBigC_PNG%2Fimage.png%3Ftype%3Df464_260%22&type=ff364_236&service=navermain"},"source":{"name":"\xea\xb8\xb0\xec\x95\x84\xeb\x8c\x80\xec\xb1\x85"},"labels":[{"type":"happybean","text":"\xea\xb8\xb0\xeb\xb6\x80"}],"fundingRate":"91","showLiveBadge":false,"_id":"6441ca92c499cc07f334c439"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\xa9\xb4\xeb\xb6\x80\xed\x84\xb0 \xec\x8c\x88\xea\xb9\x8c\xec\xa7\x80! \xea\xb5\xad\xec\x82\xb0 \xec\xbd\xa9\xec\x9c\xbc\xeb\xa1\x9c \xeb\xa7\x8c\xeb\x93\xa0 \xeb\x91\x90\xeb\xb6\x80 \xec\x84\xb8\xed\x8a\xb8","url":"https://happybean.naver.com/fundings/detail/F2506?p=p&s=nmkp","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fhappybean-phinf.pstatic.net%2F20260416_43%2F1776306599085V4O56_JPEG%2F%25BC%25EB%25BC%25EC%25A4%25ED_364.jpg%3Ftype%3Df464_260%22&type=ff364_236&service=navermain"},"source":{"name":"\xeb\x9d\xbc\xeb\x9d\xbc\xec\x8a\xa4\xed\x8c\x9c"},"labels":[{"type":"happybean","text":"\xed\x8e\x80\xeb\x94\xa9"}],"fundingRate":"796","showLiveBadge":false,"_id":"6441ca92c499cc07f334c43a"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\x8b\xac\xeb\x9d\xbc\xeb\x8f\x84 \xeb\xaa\xa8\xeb\x91\x90 \xec\xb9\x9c\xea\xb5\xac! \xed\x94\x8c\xeb\xa6\xac\xec\x8a\xa4 \xed\x86\xa0\xeb\x81\xbc DIY \xed\x82\xa4\xeb\xa7\x81","url":"https://happybean.naver.com/fundings/detail/F2529?p=p&s=nmkp","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fhappybean-phinf.pstatic.net%2F20260409_267%2F1775720851097kRt1i_JPEG%2F%25B8%25EB1.jpg%3Ftype%3Df464_260%22&type=ff364_236&service=navermain"},"source":{"name":"\xec\x9b\x94\xeb\x93\x9c\xed\x94\x84\xeb\xa0\x8c\xec\xa6\x88"},"labels":[{"type":"happybean","text":"\xed\x8e\x80\xeb\x94\xa9"}],"fundingRate":"12","showLiveBadge":false,"_id":"6441ca92c499cc07f334c43b"},{"@type":"MATERIAL-PC-FEED","title":"\xed\x98\xbc\xec\x9e\x90 \xec\xb0\xa8\xeb\xa6\xac\xeb\x8a\x94 \xec\xb2\xab \xec\x8b\x9d\xed\x83\x81\xec\x9d\xb4 \xeb\xb9\x84\xec\x96\xb4 \xec\x9e\x88\xec\xa7\x80 \xec\x95\x8a\xea\xb8\xb0\xeb\xa5\xbc","url":"https://happybean.naver.com/donations/H200000007378?p=p&s=nmkp","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fhappybean-phinf.pstatic.net%2F20260331_239%2F1774943905953DoOT2_PNG%2Fimage.png%3Ftype%3Df464_260%22&type=ff364_236&service=navermain"},"source":{"name":"\xea\xb8\x80\xeb\xa1\x9c\xeb\xb2\x8c\xec\x89\x90\xec\x96\xb4"},"labels":[{"type":"happybean","text":"\xea\xb8\xb0\xeb\xb6\x80"}],"fundingRate":"30","showLiveBadge":false,"_id":"6441ca92c499cc07f334c43c"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"title":"\xeb\xa7\x88\xec\x9d\x8c\xea\xb9\x8c\xec\xa7\x80 \xec\xb1\x84\xec\x9a\xb0\xeb\x8a\x94 \xed\x81\xb4\xeb\xa6\xad","moreText":"\xed\x95\xb4\xed\x94\xbc\xeb\xb9\x88 \xec\xa0\x84\xec\xb2\xb4\xeb\xb3\xb4\xea\xb8\xb0","moreUrl":"https://happybean.naver.com/","needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-LECTURE-HAPPYBEAN","@template":"FOUR-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"\xec\x9d\x80\xea\xb7\xbc \xeb\x82\xa8\xec\x9e\x90\xeb\x93\xa4\xec\x9d\xb4 \xed\x99\x98\xec\x9e\xa5\xed\x95\x98\xeb\x8a\x94, \xec\x9d\xb8\xea\xb8\xb0 \xeb\xa7\x8e\xec\x9d\x80 \xec\x97\xac\xec\x9e\x90\xeb\x93\xa4\xec\x9d\x98 \xea\xb3\xb5\xed\x86\xb5\xec\xa0\x90\xec\x9d\xb4 \xec\x9e\x88\xeb\x8c\x80..","url":"https://blog.naver.com/yomagazine_/224246944719","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDlfMTM3%2FMDAxNzc1NzM2Mzk4Njk5.ZwUBHAs87xEv9jKNwAV9XcHdGeGv7ensVsPuChJhbz4g.mzgXHj7Ehhvolq5mfTUXbd7IImTbrHHkq_4ya5E7bUAg.JPEG%2F1.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/yomagazine_","name":"\xec\x9a\x94\xeb\xa7\xa4\xea\xb1\xb0\xec\xa7\x84","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTEyMTVfMTYy%2FMDAxNzY1ODAyODE0NDg4.69yoX8_S6mq6brYG3Q1vr4nfnf9U1vuP5si0yVD1DKog.gU_9PFcfuVf7hXIHp1T2CckBoVhKzT120gc9srdpKcYg.PNG%2F%25EC%259A%2594%25EB%25A7%25A5%25EB%25A1%259C%25EA%25B3%25A04.png%2F%25E1%2584%258B%25E1%2585%25AD%25E1%2584%2586%25E1%2585%25A2%25E1%2586%25A8%25E1%2584%2585%25E1%2585%25A9%25E1%2584%2580%25E1%2585%25A94.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"65dd7aed9fe1402b6ccdd3f3"},{"@type":"MATERIAL-PC-FEED","title":"\xec\x98\x81\xec\x96\xb4 \xed\x95\xa0 \xec\xa4\x84 \xec\x95\x8c\xec\x95\x84?","url":"https://m.naver.com/shorts?serviceType=CLIP&mediaType=VOD&seedMediaId=0CDCB5850FE49BEEFD4C2483B04F2C521F17&recType=CLIP_PC&recId=%7B%22targetProfileId%22%3A%22wcxYOgdaZfaxNxBYlAUg%22%2C%22open%22%3Atrue%7D","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNjA0MTVfMTc4%2FMDAxNzc2MjU5NTA5NzQz.D9dtDs-an7V46m9s2X2tbuTkk_gnennwnb971bjM3TMg.K5o-z3dOiRVExSM03VDMrNOmLPfE0031nmI5og-TEvog.JPEG%2Fthumbnail-7869EA6E-FCA5-4B44-ACCC-7324060D7D8D.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://clip.naver.com/@reviewsomsom","name":"\xec\xa7\x80\xea\xb5\xac\xeb\xb3\x84\xed\x94\xbc\xed\x94\x8c","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNTA4MjhfMjc4%2FMDAxNzU2Mzg4MTAyNDky.0o58qAw6bDQQYCIEExbtp-StXW_TVIGj7XgW-b65kycg.QSKorJQcgcPGI4nKez6TUpM4v8SSnT8WdyqUOOsUfhgg.JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:47"},"showLiveBadge":false,"_id":"65dd7aed9fe1402b6ccdd3f4"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\xaf\xb8\xea\xb5\xad \xec\x97\xb4 \xeb\xb0\x9b\xec\x9c\xbc\xeb\x9d\xbc\xea\xb3\xa0 \xec\xa4\x80 \xec\x9d\xb4\xeb\x9e\x80\xec\x9d\x98 \xec\x9a\x94\xea\xb5\xac","url":"https://tv.naver.com/h/97824608","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260416_17%2FUMX5B_1776308738348qdYYx_JPEG%2FYE6cJDUqsh_08.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/gandahyo","name":"\xea\xb0\x84\xeb\x8b\xa4\xed\x9a\xa8","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240806_287%2FYXghe_1722928696360rqmei_JPEG%2F1722928696353.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:13"},"showLiveBadge":false,"_id":"65dd7aed9fe1402b6ccdd3f5"},{"@type":"MATERIAL-PC-FEED","title":"\xec\xb9\x9c\xed\x95\xa0\xec\x88\x98\xeb\xa1\x9d \xec\xa3\xbd\xec\x9d\x84 \xeb\x95\x8c\xea\xb9\x8c\xec\xa7\x80 \xec\x88\xa8\xea\xb2\xa8\xec\x95\xbc \xed\x95\xa0 6\xea\xb0\x80\xec\xa7\x80","url":"https://blog.naver.com/fikabook/224236636960","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDFfMjMy%2FMDAxNzc1MDAzMjEzOTY5.cUmEum7RUSuiNwyV1XptrhxZRyPr0VRv0G5GfXPAvEkg.GfbNW8DajH8LwKBl5fdeb3SAqaJfOBdOF3h3jlR3Cjwg.PNG%2F%EC%B9%9C%ED%95%A0%EC%88%98%EB%A1%9D_%EC%A3%BD%EC%9D%84_%EB%95%8C%EA%B9%8C%EC%A7%80_%EC%88%A8%EA%B2%A8%EC%95%BC_%ED%95%A0_6%EA%B0%80%EC%A7%80_1.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/fikabook","name":"\xed\x94\xbc\xec\xb9\xb4 \xec\xb6\x9c\xed\x8c\x90\xec\x82\xac","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfth

In [5]:
html_text = res.text

In [6]:
# 문자열에서 특정 문자의 위치를 찾는 함수 : find()
html_text.find("네이버")

378

In [7]:
html_text[378:410]

'네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요'

In [8]:
# 문자형태로 이루어진 html 문서를 BeautifulSoup class를 이용해서 객체 변환
# 문자 데이터에서는 특정 영역의 content를 추출하기 어렵다.
# Beautiful에 내장된 함수를 이용해서 데이터를 추출하기 위해 class 생성시 데이터를 대입
soup = bs(html_text, 'html.parser')

In [9]:
type(soup)

bs4.BeautifulSoup

- 태그의 이름을 기준으로 검색
    - soup.태그명
        - 해당 html 문서 안에서 해당 태그 중 첫번째 태그를 되돌려준다.
        - 문자열 함수에서 find() 함수와 비슷한 부분.
    - soup.태그명.string
        - 첫번째 태그에서 콘텐츠(태그 안에 데이터)를 되돌려준다.
            - ex) <p>Test</p> --> 'Test'
    - soup.태그명[속성명]
        - 첫번째 태그에서 특정 속성의 값을 되돌려준다.
            - ex) <a href = "https://www.naver.com"네이버</a> -> https://www.naver.com

In [10]:
soup.a

In [11]:
soup.a.string

'상단영역 바로가기'

In [12]:
soup.a['href']

'#topAsideButton'

- 내장함수
    - find()
        - html 문서 안에서 특정 태그의 첫번째 정보를 출력
        - find(속성명 = 속성값)
            - 태그들 중 특정 속성에 특정한 값을 가진 태그의 첫번째 정보를 출력
        - 함수의 결과 값의 타입은 TAG 데이터의 타입으로 되돌려준다.
    - find_all()
        - html 문서 안에서 특정 태그의 모든 정보를 출력
        - limit 매개변수
            - 찾는 태그의 개수를 지정
        - 함수의 결과 값의 타입은 ResultSEt 타입으로 되돌려준다.
    - find(), find_all() 함수는 Tag 타입에서는 사용이 가능 // ResultSet에서는 사용이 불가능
    - ResultSet 타입은 Tag 데이터들이 모여있는 리스트의 형태와 흡사

In [13]:
type(soup)

bs4.BeautifulSoup

In [14]:
type(soup.find('a'))

bs4.element.Tag

In [15]:
type(soup.find_all('a'))

bs4.element.ResultSet

In [16]:
soup.find('a')

In [ ]:
soup.find_all('a') # a태그는 하이퍼링크인데 왜 8개밖에 안나오지? => 위에 1000개만 받는다.

[<a href="#topAsideButton"><span>상단영역 바로가기</span></a>,
 <a href="#shortcutArea"><span>서비스 메뉴 바로가기</span></a>,
 <a href="#newsstand"><span>새소식 블록 바로가기</span></a>,
 <a href="#shopping"><span>쇼핑 블록 바로가기</span></a>,
 <a href="#feed"><span>관심사 블록 바로가기</span></a>,
 <a href="#account"><span>MY 영역 바로가기</span></a>,
 <a href="#widgetboard"><span>위젯 보드 바로가기</span></a>,
 <a href="#viewSetting"><span>보기 설정 바로가기</span></a>]

In [19]:
a_tag = soup.find('a')

In [20]:
a_tag.find('span')

In [22]:
# ResultSet는 find(), find_all() 함수 사용이 불가능 -> 에러 발생
# a_list.find('span')
a_list=soup.find_all('a')

In [23]:
# 모든 a태그에서 모든 content를 추출하여 새로운 리스트로 생성
# a_list에 있는 첫번째 tag를 선택하여 .string을 이용하여 텍스트 추출 (8번 반복)
# a_list는 타입이 ResultSet인데 for문에서 바로 사용이 가능할까?
a_datas = []
for tag_data in a_list:
    # print(tag_data.string)
    # break
    a_datas.append(tag_data.string)

a_datas

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [24]:
# map() + lamda
# python
list(
    map(
        lambda x : x.string,
        a_list
    )
)

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [25]:
[ data.string for data in a_list ]

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [27]:
# 네이버 증권 사이트 크롤링

# requests 라이브러리를 이용해서 html 문서를 받는다.
result = requests.get("https://finance.naver.com/")
# 응답 데이터를 문자형으로 변환 -> BeautifulSoup 파싱
soup = bs( result.text, 'html.parser')

soup

<html lang="ko">
<head>
<title>Npay 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="Npay 증권" name="apple-mobile-web-app-title">
<meta content="Npay 증권" property="og:title">
<meta content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png" property="og:image"/>
<meta content="https://finance.naver.com" property="og:url"/>
<meta content="국내 해외 증시 지수, 시장지표, 뉴스, 증권사 리서치 등 제공" property="og:description"/>
<meta content="article" property="og:type"/>
<meta content="" property="og:article:thumbnailUrl"/>
<meta content="Npay 증권" property="og:article:author"/>
<meta content="http://FINANCE.NAVER.COM" property="og:article:author:url"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/finance_header.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/finance.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock3.css" rel="stylesheet" type="text/css"/>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/release/common.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindoComponent/jindo.Component.1.0.3.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/nhn.autocomplete.stock.js" type="text/javascript"></script>
<script>
	var ieVersion = (function () {
        var version = -1;
        if (
          navigator.appName == 'Microsoft Internet Explorer' &&
          navigator.userAgent.toLowerCase().indexOf('msie') != -1 &&
          new RegExp('MSIE ([0-9]{1,}[\./0-9]{0,})').exec(navigator.userAgent) != null
        ) {
          version = parseInt(RegExp.$1);
        }
        return version;
      })();
</script>
<!-- smart channel 광고 -->
<script async="" src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js">
</script>
<script type="text/javascript">
		(function(){
			if (ieVersion === -1 || ieVersion > 10) {
				window.gladsdk = window.gladsdk || { cmd: [] };

				gladsdk.cmd.push(function() {
						gladsdk.defineAdSlot({
							adUnitId: "p_new_stock",
							adSlotElementId: "_SmartChannelTopBanner",
							uct: "KR",
							customParam: {
								calp:






									"home"
							},
						});

						gladsdk.addEventListener(gladsdk.event.AD_LOADED, function(ad) {
							//console.log(gladsdk.event.AD_LOADED);
						});
						gladsdk.addEventListener(gladsdk.event.AD_CLICKED, function(ad) {
							//console.log(gladsdk.event.AD_CLICKED);
						});
						gladsdk.addEventListener(gladsdk.event.AD_IMPRESSED, function(ad) {
							//console.log(gladsdk.event.AD_IMPRESSED);
						});
						gladsdk.addEventListener(gladsdk.event.ERROR, function(ad, error) {
							//TODO: 오류 로깅처리
							//console.log(gladsdk.event.ERROR);
						});
					});

				gladsdk.cmd.push(function() {
					gladsdk.defineAdSlot({
						adUnitId: "p_new_stock_top_sidebox",
						adSlotElementId: "_SmartChannelTopBannerSidebox",
						uct: "KR",
						customParam: {
							calp:






							"home"
						},
					});

					gladsdk.addEventListener(gladsdk.event.AD_LOADED, function(ad) {
						//console.log(gladsdk.event.AD_LOADED);
					});
					gladsdk.addEventListener(gladsdk.event.AD_CLICKED, function(ad) {
						//console.log(gladsdk.event.AD_CLICKED);
					});
					gladsdk.addEventListener(gladsdk.event.AD_IMPRESSED, function(ad) {
						//console.log(gladsdk.event.AD_IMPRESSED);
					});
					gladsdk.addEventListener(gladsdk.event.ERROR, function(ad, error) {
						//TODO: 오류 로깅처리
						//console.log(gladsdk.event.ERROR);
					});
				});
			}
		})();
	</script>
<link href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
    (function(){
		document.write(
				[
					'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="180x180" href="https://ssl.pstatic.net/imgstock/favi/favicon-180x180.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>',
					'<link rel="icon" type="image/png" sizes="16x16" href="https://ssl.pstatic.net/imgstock/favi/favicon-16x16.png"/>',
					'<link rel="icon" type="image/png" sizes="32x32" href="https://ssl.pstatic.net/imgstock/favi/favicon-32x32.png"/>',
					'<link rel="icon" type="image/png" sizes="96x96" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="icon" type="image/png" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>'
				]
			.join('\n')
		);
    })();
    </script>
</meta></meta></head>
<body onload="getGNB();">
<script type="text/javascript">







var nsc="finance.home";


var ccsrv="cc.naver.com";




	var gnb_service='finance';



var gnb_logout=document.URL; //GNB에서 로그아웃 후 redirect 될 URL
var gnb_searchbox='off'; //미니 검색창을 on 할지 off 할지. default는 off
var gnb_shortnick='off'; //닉네임 말줄임(10자)을 on할지 off 할지. default는 off.


var gnb_naverme_layer_open_callback = function(){
	   var naverLayerSize = gnbNaverMeLayer.getLayerSize();

		var me_layers = document.getElementById("me_layers");
		me_layers.width=naverLayerSize.width;
		me_layers.height=naverLayerSize.height;};

var gnb_naverme_layer_close_callback = function(){

			var me_layers = document.getElementById("me_layers");
			me_layers.width="0";
			me_layers.height="0";};
</script>
<div id="u_skip">
<a href="#menu" tabindex="1"><span>메인 메뉴로 바로가기</span></a>
<a href="#start" tabindex="2"><span>본문으로 바로가기</span></a>
</div>
<div id="header">
<div class="header_area">
<div class="header_inner">
<div class="logo_area">
<h1 class="service">
<a class="logo_link" href="https://www.naver.com/" onclick="clickcr(this, 'STA.naver', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 22 22" width="22" xmlns="http://www.w3.org/2000/svg">
<path d="M22 11C22 13.1756 21.3549 15.3023 20.1462 17.1113C18.9375 18.9202 17.2195 20.3301 15.2095 21.1627C13.1995 21.9952 10.9878 22.2131 8.85401 21.7886C6.72022 21.3642 4.76021 20.3166 3.22183 18.7782C1.68345 17.2398 0.635805 15.2798 0.211368 13.146C-0.213069 11.0122 0.00476298 8.80047 0.837327 6.79048C1.66989 4.78049 3.07979 3.06253 4.88873 1.85383C6.69768 0.645137 8.82441 0 11 0C13.9174 0 16.7153 1.15893 18.7782 3.22183C20.8411 5.28473 22 8.08262 22 11ZM12.8398 5.83V11.3602L8.98976 5.83H5.83V16.1838H9.1575V10.637L13.0075 16.17H16.1783V5.83H12.8398Z" fill="#000"></path>
</svg>
<span class="blind">네이버</span>
</a>
<a class="logo_link" href="https://new-m.pay.naver.com/" onclick="clickcr(this, 'STA.pay', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 37 22" width="37" xmlns="http://www.w3.org/2000/svg">
<path d="M34.4319 5.21944L31.3913 12.1478L27.9518 5.21944H25.3072L30.1783 14.8317L28.1703 19.3358H30.7384L37 5.2331L34.4319 5.21944ZM23.6171 15.9331H21.1037V14.9328C20.1894 15.7342 19.0108 16.1685 17.7953 16.1518C14.7901 16.1518 12.4379 13.692 12.4379 10.5763C12.4379 7.46057 14.7874 5.00079 17.7953 5.00079C19.0104 4.9833 20.189 5.41657 21.1037 6.21701V5.21944H23.6171V15.9331ZM21.3987 10.5899C21.3987 8.57019 19.9891 7.03694 18.1204 7.03694C16.2517 7.03694 14.842 8.57019 14.842 10.5899C14.842 12.6097 16.249 14.1429 18.1204 14.1429C19.9918 14.1429 21.3987 12.596 21.3987 10.5899ZM0.00819554 19.3358H2.63088V15.023C3.52823 15.7695 4.66309 16.1699 5.83001 16.1518C8.83516 16.1518 11.1901 13.692 11.1901 10.5763C11.1901 7.46057 8.83789 5.00079 5.83001 5.00079C4.61166 4.9789 3.42899 5.4126 2.51341 6.21701V5.21944H0L0.00819554 19.3358ZM5.51856 7.03694C7.38722 7.03694 8.79691 8.57019 8.79691 10.5899C8.79691 12.6097 7.38722 14.1429 5.51856 14.1429C3.6499 14.1429 2.24021 12.6097 2.24021 10.5899C2.24021 8.57019 3.63351 7.03694 5.51856 7.03694Z" fill="#000"></path>
</svg>
<span class="blind">페이</span>
</a>
<a class="logo_link" href="/" onclick="clickcr(this, 'STA.finance', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 34 22" width="34" xmlns="http://www.w3.org/2000/svg">
<path d="M2.43006 8.88998L1.85406 6.99998C5.29206 6.31598 7.00206 5.34398 7.45206 4.31798H2.71806V2.35598H14.3641V4.31798H9.75606C9.70206 4.65998 9.61206 4.98398 9.46806 5.28998L15.2101 6.98198L14.4901 8.88998L8.02806 6.92798C6.84006 7.75598 5.00406 8.40398 2.43006 8.88998ZM0.612061 11.5V9.53798H16.4521V11.5H0.612061ZM6.53406 12.796H10.5301C13.2301 12.796 14.7961 14.128 14.7961 15.91C14.7961 17.71 13.2301 19.024 10.5301 19.024H6.53406C3.85206 19.024 2.28606 17.71 2.28606 15.91C2.28606 14.128 3.85206 12.796 6.53406 12.796ZM6.96606 17.044H10.1161C11.7901 17.044 12.4921 16.594 12.4921 15.892C12.4921 15.19 11.7901 14.776 10.1161 14.776H6.96606C5.29206 14.776 4.57206 15.19 4.57206 15.892C4.57206 16.594 5.29206 17.044 6.96606 17.044Z" fill="#000"></path>
<path d="M25.1904 13.354V11.536H29.4564V2.03198H31.7604V15.334H29.4564V13.354H25.1904ZM21.3384 10.564C20.9244 10.582 20.5464 10.582 20.1684 10.582H17.4504L17.3604 8.61998H20.3844C21.5004 8.61998 22.9584 8.56598 24.4884 8.45798C24.7224 6.99998 24.8484 5.63198 24.8664 4.62398H18.4404V2.66198H27.0984V3.56198C27.0984 5.16398 26.9724 6.76598 26.7564 8.25998L28.2684 8.09798L28.5024 10.006C26.9724 10.222 25.2264 10.384 23.5704 10.474C23.4984 11.5 23.3904 12.562 23.2644 13.714L21.0684 13.588C21.1764 12.508 21.2664 11.536 21.3384 10.564ZM22.4724 14.254V16.756H32.3724V18.844H20.1684V14.254H22.4724Z" fill="#000"></path>
</svg>
<span class="blind">증권</span>
</a>
</h1>
</div>
<div class="right_area">
<div class="search_area">
<form action="/search/search.naver" method="get" name="search" onsubmit="return delayed_submit(this)" style="margin:0; padding:0;">
<label class="blind" for="stock_items">증권 종목명·지수명 검색</label>
<input accesskey="s" autocomplete="off" class="search_input" id="stock_items" name="query" placeholder="종목명·지수명 입력" title="종목명·지수명 검색" type="text"/>
<input id="_endUrl" name="endUrl" type="hidden" value="">
<button class="search_button" onclick="clickcr(this, 'STA.search', '', '', event);" type="submit">
<svg fill="none" height="16" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M6.9999 2.59996C4.56985 2.59996 2.5999 4.56991 2.5999 6.99996C2.5999 9.43002 4.56985 11.4 6.9999 11.4C9.42996 11.4 11.3999 9.43002 11.3999 6.99996C11.3999 4.56991 9.42996 2.59996 6.9999 2.59996ZM1.3999 6.99996C1.3999 3.90717 3.90711 1.39996 6.9999 1.39996C10.0927 1.39996 12.5999 3.90717 12.5999 6.99996C12.5999 10.0928 10.0927 12.6 6.9999 12.6C3.90711 12.6 1.3999 10.0928 1.3999 6.99996Z" fill="#404048" fill-rule="evenodd"></path>
<path clip-rule="evenodd" d="M10.2421 10.2424C10.4765 10.0081 10.8564 10.0081 11.0907 10.2424L14.424 13.5758C14.6583 13.8101 14.6583 14.19 14.424 14.4243C14.1897 14.6586 13.8098 14.6586 13.5755 14.4243L10.2421 11.091C10.0078 10.8567 10.0078 10.4768 10.2421 10.2424Z" fill="#404048" fill-rule="evenodd"></path>
</svg>
<span class="blind">검색</span>
</button>
<div class="auto_area">
<span class="blind">자동완성</span>
<div id="autoFrame" style="display: none;">
<div class="wrap" id="atcmp" style="display:none;">
<div class="wrap_in">
<div class="words">
<ul class="_resultBox">
<li>
<a class="_au_real_list" href="#" onclick="clickcr(this, 'AUT.list', '', '', event); return false;">
<span class="num _au_real_list">@code@</span>
<span class="_au_real_list">@txt@</span>
<span class="type _au_real_list">@market@</span>
</a>
<div class="_au_full" style="display:none">@full_txt@</div>
<div class="_au_code" style="display:none">@in_code@</div>
<div class="_au_name" style="display:none">@in_name@</div>
<div class="_au_link" style="display:none">@in_link@</div>
<div class="_au_market" style="display:none">@in_market@</div>
</li>
</ul>
<div class="search_notice">
<p class="text">
												공모주와 해외 종목은 모바일 페이지로 이동합니다.
											</p>
</div>
</div>
</div>
<!-- 현재 자동완성 기능을 사용하고 계십니다 -->
<div class="wrap" id="atcmpIng" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												현재 자동완성 기능을 사용하고 계십니다.
											</p>
</div>
</div>
</div>
<!--// 현재 자동완성 기능을 사용하고 계십니다 -->
<!-- 자동완성 기능이 활성화 -->
<div class="wrap" id="atcmpStart" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												자동완성 기능이 활성화되었습니다.
											</p>
</div>
</div>
</div>
</div>
</div>
</div>
</input></form>
</div>
<div class="gnb_area">
<div id="gnb">
<script charset="EUC-KR" type="text/javascript">
							var gnb_service = "finance";
							var gnb_template = location.protocol === "http:" ? "gnb_quirks_euckr" : "gnb_utf8" ;
							var gnb_logout=encodeURIComponent(location.href);
							var gnb_brightness = 1;
							var gnb_one_naver = 0;
						</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?20260421" type="text/javascript">
</script>
</div>
</div>
</div>
</div>
</div>
<div class="lnb_area">
<div class="lnb_inner">
<div id="menu">
<ul class="menu">
<li class="m1 first on"><a href="/" onclick="clickcr(this, 'LNB.home', '', '', event);"><span class="tx">증권 홈</span><span class="blind">선택됨</span></a></li>
<li class="m2"><a href="/sise/" onclick="clickcr(this, 'LNB.sise', '', '', event);"><span class="tx">국내증시</span></a></li>
<li class="m3"><a href="/world/" onclick="clickcr(this, 'LNB.world', '', '', event);"><span class="tx">해외증시</span></a></li>
<li class="m4"><a href="/marketindex/" onclick="clickcr(this, 'LNB.market', '', '', event);"><span class="tx">시장지표</span></a></li>
<li class="m6"><a href="/research/" onclick="clickcr(this, 'LNB.research', '', '', event);"><span class="tx">리서치</span></a></li>
<li class="m7"><a href="/news/"><span class="tx">뉴스</span></a></li>
<li class="m8"><a href="/mystock/" onclick="clickcr(this, 'LNB.mystock', '', '', event);"><span class="tx">MY</span></a></li>
</ul>
<!-- 새로운 증권보기 버튼 -->
<div class="area_stock_button">
<a class="link_new" href="https://stock.naver.com">
<span class="icon_refresh"></span>
						새로운 증권 보기
						<span class="icon_new">
<span class="blind">NEW</span>
</span>
</a>
<span class="tooltip">
						더 편리해진 증권을 만나보세요
						<span class="icon_arrow"></span>
</span>
</div>
<!-- //새로운 증권보기 버튼 -->
</div>
</div>
</div>
<script type="text/JavaScript">
		/* lcs 집계 */
        ;(function(){
            var eventType = "onpageshow" in window ? "pageshow" : "load";
            jindo.$Fn(function(){
                lcs_do();
            }).attach(window, eventType);
        })();

		/* 검색 자동완성 [ 인자1 : 검색input의 ID, 인자2 : iframe 태그 ID ]   */
		// AutoComplete 생성
		var acDomain = "ac.stock.naver.com";
		if (location.hostname.indexOf("staging-") > -1) {
			acDomain = "staging-" + acDomain;
		} else if (location.hostname.indexOf("test-") > -1) {
			acDomain = "test-" + acDomain;
		} else if (location.hostname.indexOf("dev-") > -1 || location.hostname.indexOf("localhost") > -1 || location.hostname.indexOf("local-") > -1) {
			acDomain = "dev-" + acDomain;
		}

        var acUrl = "https://" + acDomain + "/ac";

		smartSearch = new nhn.Autocomplete(
			// InputManager 생성
			new nhn.AcInputManager(jindo.$("stock_items")),
			// DataManager 생성
			new nhn.AcDataManager(acUrl, "xhr", "get", {}),
			// ViewManager 생성
			new nhn.AcStockViewManager(jindo.$("autoFrame"), jindo.$("nautocomplete"), {
                                        strMax: 200,
                                        listMax: [7, 2, 2],
                                        aRedirectUrl: [
										"https://" + window.location.hostname,
                            			"https://finance.naver.com",
                            			"https://finance.naver.com"],
										mobileUrl: "https://m.stock.naver.com"}),
			// Autocomplete Option
            {formId:"search", cookieDomain:location.hostname, cookieName:"NaverCommonStock_disable"});

			smartSearch.attach({
	            onFocus: function () {
	                var weInput = jindo.$Element('stock_items');
	                if (weInput && weInput.hasClass("snb_default")) {
	                        weInput.text("");
	                        weInput.removeClass('snb_default');
	                }
	            }
	        });

		/* 통합검색  start ----->  */
		var sSearchHintText = '종목명·지수명·환율명·원자재명 입력';
		function itegrationSearch() {
			var query = jindo.$('stock_items').value;

			if ( query == ''  || encodeURIComponent(query) == encodeURIComponent(sSearchHintText))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}

            var url = "https://search.naver.com/search.naver?sm=sta_hty.finance&where=nexearch&ie=UTF8&query=" + encodeURIComponent(query);
            window.open(url, "_blank");

			return false;
		}

		function delayed_submit(object) {
			if (navigator.userAgent.indexOf('MSIE') == -1) {
				window.setTimeout(function() {stock_search(object)}, 300);
			} else {
				stock_search(object);
			}
			return false;
		}

		function stock_search (object) {
			// endUrl check
			if (object.endUrl.value) {
				if (object.endUrl.value.startsWith("https://m.stock.naver.com")) {
					// 검색정보 초기화
					var _endUrl = object.endUrl.value;
					object.query.value = "";
					object.endUrl.value = "";
					document.getElementById("atcmp").style.display="none";
					window.open(_endUrl, "_blank");
				} else {
					location.href = object.endUrl.value;
				}

				return;
			}

			// query check
			query = object.query.value.replace(/^\s*/,'').replace(/\s*$/,'');	// trim
			object.query.value=query;

			if ( query == '' || query == sSearchHintText.replace(/^\s*/,'').replace(/\s*$/,''))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}
			else {
				object.submit();
			}
		}
		/* <---------- 통합검색  end */

		function popup()
		{
			win = window.open('/template/group_limit_pop.jsp','finan_popup','width=569 height=278 scrollbars=no status=no');
			win.focus();
		}
	</script>
<iframe frameborder="0" height="0" id="me_layers" name="test" scrolling="no" style="display:block;top: 22px; right: 209px; position: absolute; z-index: 15;" title="네이버미 영역" width="0"></iframe>
</div>
<div id="wrap">
<hr/>
<div class="blind" id="start"><strong name="start">본문시작</strong></div>
<dl class="blind">
<dt>오늘의 코스피/코스닥 지수</dt>
<dd>2026년 04월 21일 장중</dd>
<dd>코스피 지수 6,374.45 전일대비 상승 155.36 플러스 2.50 퍼센트</dd>
<dd>코스닥 지수 1,175.93 전일대비 상승 1.08 플러스 0.09 퍼센트</dd>
</dl>
<div class="home_spot view_on">
<div class="bx_spot">
<div class="tab_spot tab2" id="tab_search">
<ul>
<li><a href="#" onclick="javascript:showMainRecentMyStockSearchStock('tab_search', 'tab_spot tab1', '000000', 'recent');clickcr(this, 'mys.recent', '', '', event);return false;"><span>최근조회종목</span></a></li>
<li><a href="#" onclick="javascript:showMainRecentMyStockSearchStock('tab_search', 'tab_spot tab2', '000000', 'mystock');clickcr(this, 'mys.interest', '', '', event);return false;"><span>MY STOCK</span></a></li>
</ul>
</div>
<div class="section_tab" id="recent_search_tab">
<strong class="blind" id="recent_mystock_blind">최근 조회종목 리스트</strong>
<ul class="tab_list">
</ul>
</div>
<input alt="닫기" class="btn_spot" onclick="clickcr(this, (jindo.$Element('tab_search').hasClass('tab1') ? 'mys*r.close' : 'mys*i.close'), '', '', event);" src="https://ssl.pstatic.net/static/nfinance/btn_spot_close.gif" style="display:none" type="image"/>
<input alt="펼치기" class="btn_spot" onclick="clickcr(this, (jindo.$Element('tab_search').hasClass('tab1') ? 'mys*r.open' : 'mys*i.open'), '', '', event);" src="https://ssl.pstatic.net/static/nfinance/btn_spot_open.gif" style="display:none" type="image"/>
</div>
</div>
<div class="home" id="container">
<div id="content">
<div class="article">
<div class="section">

In [28]:
# html 문서 안에서 태그명이 div이고 class 속성의 값이 section_sise_top인 태그를 모두 찾아서 길이를 구하자.
len(
    soup.find_all(
        'div',
        attrs = {
            'class' : 'section_sise_top'
        }
    )
)

1

In [29]:
# 1개 라면 find_all()이 아닌 find() 이용해서 데이터 추출
div_data = soup.find(
    'div',
    attrs = {
        'class' : 'section_sise_top'
    }
)

div_data

<div class="section_sise_top">
<h2 class="h_type"><span>TOP 종목</span></h2>
<!-- KRX, NXT 탭 -->
<div class="area_tab_type">
<ul class="top_tab_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="top_tab_item top_tab_krx is_active">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.krx', '', '', event);return false;">KRX</a>
</li>
<li class="top_tab_item top_tab_nxt">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.nxt', '', '', event);return false;">NXT</a>
</li>
</ul>
<div class="text_nxt">
                                넥스트레이드(NXT)
                                <button class="buttton_tooltip" type="button">
<span class="icon">
<span class="blind">도움말</span>
</span>
</button>
<div class="area_tooltip">
<p>
<strong>넥스트레이드(NXT)</strong>
                                        넥스트레이드(NXT)란 대한민국
                                        최초의 대체거래소(ATS,
                                        Alternative Trading
                                        System)입니다. 아래는
                                        넥스트레이드에서 거래가 가능한
                                        종목들입니다.
                                    </p>
<span class="arrow"></span>
</div>
</div>
</div>
<!-- //KRX, NXT 탭 -->
<ul class="tab_sort_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="tab_sort_item is_active"><a class="link tab_sort_sale" href="#" onclick="clickcr(this, 'spe.sale', '', '', event);return false;"><span class="tab1"><span class="blind">거래상위</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_ceiling" href="#" onclick="clickcr(this, 'spe.ceiling', '', '', event);return false;"><span class="tab2"><span class="blind">상승</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_bottom" href="#" onclick="clickcr(this, 'spe.bottom', '', '', event);return false;"><span class="tab3"><span class="blind">하락</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_value" href="#" onclick="clickcr(this, 'spe.value', '', '', event);return false;"><span class="tab4"><span class="blind">시가총액 상위</span></span></a></li>
</ul>
<div class="group_type krx_group_type tab1 is_active">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>181</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 10</td>
<td>
<em class="down">
				-5.24%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,562</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 407</td>
<td>
<em class="up">
				+18.89%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,200</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,100</td>
<td>
<em class="up">
				+18.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>306</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7</td>
<td>
<em class="up">
				+2.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 70</td>
<td>
<em class="up">
				+1.80%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,091</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+4.30%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,371</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 148</td>
<td>
<em class="up">
				+12.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 50</td>
<td>
<em class="up">
				+1.28%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,418</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 96</td>
<td>
<em class="up">
				+7.26%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab1 is_active" style="display:none">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems1">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=014940" onclick="clickcr(this, 'spe.slist', '014940', '1', event);">오리엔탈정공</a></th>
<td>8,510</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 490</td>
<td>
<em class="up">
				+6.11%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=005930" onclick="clickcr(this, 'spe.slist', '005930', '2', event);">삼성전자</a></th>
<td>218,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,500</td>
<td>
<em class="up">
				+1.63%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=006360" onclick="clickcr(this, 'spe.slist', '006360', '3', event);">GS건설</a></th>
<td>42,750</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,700</td>
<td>
<em class="up">
				+12.35%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=004980" onclick="clickcr(this, 'spe.slist', '004980', '4', event);">성신양회</a></th>
<td>11,780</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 750</td>
<td>
<em class="up">
				+6.80%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010140" onclick="clickcr(this, 'spe.slist', '010140', '5', event);">삼성중공업</a></th>
<td>30,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,450</td>
<td>
<em class="up">
				+5.08%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=378340" onclick="clickcr(this, 'spe.slist', '378340', '6', event);">필에너지</a></th>
<td>19,800</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,270</td>
<td>
<em class="up">
				+19.78%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=161000" onclick="clickcr(this, 'spe.slist', '161000', '7', event);">애경케미칼</a></th>
<td>15,200</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,350</td>
<td>
<em class="up">
				+9.75%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=077970" onclick="clickcr(this, 'spe.slist', '077970', '8', event);">STX엔진</a></th>
<td>51,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,800</td>
<td>
<em class="up">
				+10.39%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=034020" onclick="clickcr(this, 'spe.slist', '034020', '9', event);">두산에너빌리티</a></th>
<td>115,400</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,400</td>
<td>
<em class="up">
				+3.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=101730" onclick="clickcr(this, 'spe.slist', '101730', '10', event);">위메이드맥스</a></th>
<td>6,690</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 170</td>
<td>
<em class="up">
				+2.61%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=005440" onclick="clickcr(this, 'spe.slist', '005440', '11', event);">현대지에프홀딩스</a></th>
<td>14,960</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 730</td>
<td>
<em class="up">
				+5.13%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.slist', '336370', '12', event);">솔루스첨단소재</a></th>
<td>14,140</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,130</td>
<td>
<em class="up">
				+28.43%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=028050" onclick="clickcr(this, 'spe.slist', '028050', '13', event);">삼성E&amp;A</a></th>
<td>51,400</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,100</td>
<td>
<em class="up">
				+4.26%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.slist', '107640', '14', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 16,700</td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=114190" onclick="clickcr(this, 'spe.slist', '114190', '15', event);">강원에너지</a></th>
<td>15,570</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,010</td>
<td>
<em class="up">
				+6.94%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/nxt_sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type krx_group_type tab2">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=045510" onclick="clickcr(this, 'spe.clist', '045510', '1', event);">정원엔시스</a></th>
<td>1,297</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 299 </td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.clist', '222080', '2', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 3,760 </td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=036930" onclick="clickcr(this, 'spe.clist', '036930', '3', event);">주성엔지니어링</a></th>
<td>118,900</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 27,400 </td>
<td>
<em class="up">
				+29.95%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=256940" onclick="clickcr(this, 'spe.clist', '256940', '4', event);">킵스파마</a></th>
<td>10,850</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 2,500 </td>
<td>
<em class="up">
				+29.94%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.clist', '107640', '5', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 16,700 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=312610" onclick="clickcr(this, 'spe.clist', '312610', '6', event);">에이에프더블류</a></th>
<td>1,424</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 328 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=900100" onclick="clickcr(this, 'spe.clist', '900100', '7', event);">애머릿지</a></th>
<td>508</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 117 </td>
<td>
<em class="up">
				+29.92%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=189330" onclick="clickcr(this, 'spe.clist', '189330', '8', event);">씨이랩</a></th>
<td>8,950</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 2,060 </td>
<td>
<em class="up">
				+29.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=073570" onclick="clickcr(this, 'spe.clist', '073570', '9', event);">리튬포어스</a></th>
<td>756</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 174 </td>
<td>
<em class="up">
				+29.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=424760" onclick="clickcr(this, 'spe.clist', '424760', '10', event);">벨로크</a></th>
<td>2,370</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 545 </td>
<td>
<em class="up">
				+29.86%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.clist', '078130', '11', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 108 </td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131400" onclick="clickcr(this, 'spe.clist', '131400', '12', event);">이브이첨단소재</a></th>
<td>2,050</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 471 </td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=051980" onclick="clickcr(this, 'spe.clist', '051980', '13', event);">중앙첨단소재</a></th>
<td>2,135</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 489 </td>
<td>
<em class="up">
				+29.71%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=127980" onclick="clickcr(this, 'spe.clist', '127980', '14', event);">화인써키트</a></th>
<td>6,760</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,500 </td>
<td>
<em class="up">
				+28.52%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.clist', '336370', '15', event);">솔루스첨단소재</a></th>
<td>14,140</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,130 </td>
<td>
<em class="up">
				+28.43%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_rise.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">상승 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab2" style="display:none">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.clist', '107640', '1', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 16,700 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.clist', '336370', '2', event);">솔루스첨단소재</a></th>
<td>14,140</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,130 </td>
<td>
<em class="up">
				+28.43%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=378340" onclick="clickcr(this, 'spe.clist', '378340', '3', event);">필에너지</a></th>
<td>19,800</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,270 </td>
<td>
<em class="up">
				+19.78%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=006400" onclick="clickcr(this, 'spe.clist', '006400', '4', event);">삼성SDI</a></th>
<td>644,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 106,000 </td>
<td>
<em class="up">
				+19.70%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=348370" onclick="clickcr(this, 'spe.clist', '348370', '5', event);">엔켐</a></th>
<td>48,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7,200 </td>
<td>
<em class="up">
				+17.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=171090" onclick="clickcr(this, 'spe.clist', '171090', '6', event);">선익시스템</a></th>
<td>117,300</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 16,400 </td>
<td>
<em class="up">
				+16.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=469610" onclick="clickcr(this, 'spe.clist', '469610', '7', event);">이노테크</a></th>
<td>26,550</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,700 </td>
<td>
<em class="up">
				+16.19%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=443060" onclick="clickcr(this, 'spe.clist', '443060', '8', event);">HD현대마린솔루션</a></th>
<td>225,500</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 29,800 </td>
<td>
<em class="up">
				+15.23%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078600" onclick="clickcr(this, 'spe.clist', '078600', '9', event);">대주전자재료</a></th>
<td>148,900</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 18,900 </td>
<td>
<em class="up">
				+14.54%
				</em>
</td>
</tr>
<tr class="up">

In [30]:
# div_data에서 table 태그 중 class의 값이 tbl_home인 태그의 개수가 어떻게 되는가?
len(
    div_data.find_all(
        'table',
        attrs={
            'class' : 'tbl_home'
        }
    )
)

8

In [31]:
tables = div_data.find_all(
    'table',
    attrs={
        'class' : 'tbl_home'
    }
)

In [ ]:
tables[0]
# thead는 테이블의 제목 (columns 이름) -> 따로 추출하여 columns 사용
# tbody 테이블의 데이터 (values) -> 따로 추출해서 values 사용

<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>181</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 10</td>
<td>
<em class="down">
				-5.24%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,562</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 407</td>
<td>
<em class="up">
				+18.89%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,200</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,100</td>
<td>
<em class="up">
				+18.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>306</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7</td>
<td>
<em class="up">
				+2.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 70</td>
<td>
<em class="up">
				+1.80%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,091</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+4.30%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,371</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 148</td>
<td>
<em class="up">
				+12.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 50</td>
<td>
<em class="up">
				+1.28%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,418</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 96</td>
<td>
<em class="up">
				+7.26%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>
</table>

In [33]:
# 반복문에서 사용할 변수명을 그대로 이용하여 1차 작업 (반복 실행할 코드를 테스트)
table_data = tables[0]

In [34]:
# columns에서 사용할 데이터들을 추출 -> table 데이터 에서 thead 태그를 추출
head_data = table_data.find('thead')

In [35]:
head_data

<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>

In [ ]:
# head_data에서 th 태그를 모두 찾는다.
th_list = head_data.find_all('th')
# th_list[0].get_text()
# 각각 th 태그에서 content를 추출하여 리스트로 만든다.
# 콘텐츠를 추출하는 방법 string 또는 get_text()
# case1
cols = []
for th in th_list:
    cols.append( th.string )
cols

# case2
cols2 = list(
    map(
        lambda x : x.string,
        th_list
    )
)
cols2

# case 3
cols3 = [ th.string for th in th_list ]
cols3

['종목명', '현재가', '전일대비', '등락률']

In [42]:
body_data = table_data.find('tbody')
body_data

<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>181</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 10</td>
<td>
<em class="down">
				-5.24%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,562</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 407</td>
<td>
<em class="up">
				+18.89%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,200</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,100</td>
<td>
<em class="up">
				+18.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>306</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7</td>
<td>
<em class="up">
				+2.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 70</td>
<td>
<em class="up">
				+1.80%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,091</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+4.30%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,371</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 148</td>
<td>
<em class="up">
				+12.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 50</td>
<td>
<em class="up">
				+1.28%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,418</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 96</td>
<td>
<em class="up">
				+7.26%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>

In [43]:
tr_list = body_data.find_all(
    'tr'
)
len(tr_list)

15

In [46]:
# 첫번째 tr 데이터에서 value를 추출 -> 15번 반복
tr = tr_list[0]
tr

<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>181</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 10</td>
<td>
<em class="down">
				-5.24%
				</em>
</td>
</tr>

In [52]:
# 두 개의 태그를 모두 찾는다?
row_list = tr.find_all(['th','td'])
row_list

[<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>,
 <td>181</td>,
 <td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 10</td>,
 <td>
 <em class="down">
 				-5.24%
 				</em>
 </td>]

In [ ]:
# row_list 에서 콘텐츠 데이터를 추출 -> string, get_text()
# get_text() : 태그 안에 모든 콘텐츠를 추출
# string : 콘텐츠 데이터가 한 군데에 존재할때 추출 가능
row_list[2].span.string

'하락'

In [54]:
value_data = [data.get_text().strip() for data in row_list]
value_data

['KODEX 200선물인버스2X', '181', '하락 10', '-5.24%']

In [55]:
values = []

for tr in tr_list:
    row_list = tr.find_all(['th','td'])
    value_data = [data.get_text().strip() for data in row_list]
    values.append(value_data)

values

[['KODEX 200선물인버스2X', '181', '하락 10', '-5.24%'],
 ['KODEX 인버스', '1,396', '하락 36', '-2.51%'],
 ['KODEX 2차전지산업레버리지', '2,562', '상승 407', '+18.89%'],
 ['대우건설', '33,200', '상승 5,100', '+18.15%'],
 ['국일제지', '470', '상승 108', '+29.83%'],
 ['에스아이리소스', '306', '상승 7', '+2.34%'],
 ['파인텍', '2,015', '상승 442', '+28.10%'],
 ['드림시큐리티', '3,950', '상승 70', '+1.80%'],
 ['SGA솔루션즈', '1,091', '상승 45', '+4.30%'],
 ['삼성 인버스 2X WTI원유 선물 ETN', '23', '상승 1', '+4.55%'],
 ['KEC', '1,371', '상승 148', '+12.10%'],
 ['씨아이에스', '16,310', '상승 3,760', '+29.96%'],
 ['신성이엔지', '3,950', '상승 50', '+1.28%'],
 ['진원생명과학', '1,418', '상승 96', '+7.26%'],
 ['TIGER 200선물인버스2X', '192', '하락 12', '-5.88%']]

In [56]:
import pandas as pd

In [57]:
pd.DataFrame(values, columns = cols)

                       종목명     현재가      전일대비      등락률
0         KODEX 200선물인버스2X     181     하락 10   -5.24%
1                KODEX 인버스   1,396     하락 36   -2.51%
2         KODEX 2차전지산업레버리지   2,562    상승 407  +18.89%
3                     대우건설  33,200  상승 5,100  +18.15%
4                     국일제지     470    상승 108  +29.83%
5                  에스아이리소스     306      상승 7   +2.34%
6                      파인텍   2,015    상승 442  +28.10%
7                   드림시큐리티   3,950     상승 70   +1.80%
8                  SGA솔루션즈   1,091     상승 45   +4.30%
9   삼성 인버스 2X WTI원유 선물 ETN      23      상승 1   +4.55%
10                     KEC   1,371    상승 148  +12.10%
11                   씨아이에스  16,310  상승 3,760  +29.96%
12                   신성이엔지   3,950     상승 50   +1.28%
13                  진원생명과학   1,418     상승 96   +7.26%
14        TIGER 200선물인버스2X     192     하락 12   -5.88%

In [58]:
# 8개의 테이블 중 1개 완성
# 8번 반복을 하는 반복문을 생성 -> 각각의 데이터프레임이 생성 -> 각각 다른 전역 변수에 저장 (golbals()["변수명"])

# 전역변수의 이름을 반복 실행할때마다 변경하기 위한 기본값
vari_num = 1

for table_data in tables:
    head_data = table_data.find('thead')
    cols = [ th.string for th in th_list ]

    body_data = table_data.find('tbody')
    tr_list = body_data.find_all('tr')
    values = []

    for tr in tr_list:
        row_list = tr.find_all( ['th', 'td'])
        value_data = [ data.get_text().strip() for data in row_list ]
        values.append(value_data)

    globals()[f"df{vari_num}"] = pd.DataFrame(values, columns = cols)

    vari_num += 1

In [59]:
df1

                       종목명     현재가      전일대비      등락률
0         KODEX 200선물인버스2X     181     하락 10   -5.24%
1                KODEX 인버스   1,396     하락 36   -2.51%
2         KODEX 2차전지산업레버리지   2,562    상승 407  +18.89%
3                     대우건설  33,200  상승 5,100  +18.15%
4                     국일제지     470    상승 108  +29.83%
5                  에스아이리소스     306      상승 7   +2.34%
6                      파인텍   2,015    상승 442  +28.10%
7                   드림시큐리티   3,950     상승 70   +1.80%
8                  SGA솔루션즈   1,091     상승 45   +4.30%
9   삼성 인버스 2X WTI원유 선물 ETN      23      상승 1   +4.55%
10                     KEC   1,371    상승 148  +12.10%
11                   씨아이에스  16,310  상승 3,760  +29.96%
12                   신성이엔지   3,950     상승 50   +1.28%
13                  진원생명과학   1,418     상승 96   +7.26%
14        TIGER 200선물인버스2X     192     하락 12   -5.88%

In [60]:
df2

         종목명      현재가       전일대비      등락률
0     오리엔탈정공    8,510     상승 490   +6.11%
1       삼성전자  218,000   상승 3,500   +1.63%
2       GS건설   42,750   상승 4,700  +12.35%
3       성신양회   11,780     상승 750   +6.80%
4      삼성중공업   30,000   상승 1,450   +5.08%
5       필에너지   19,800   상승 3,270  +19.78%
6      애경케미칼   15,200   상승 1,350   +9.75%
7      STX엔진   51,000   상승 4,800  +10.39%
8    두산에너빌리티  115,400   상승 4,400   +3.96%
9     위메이드맥스    6,690     상승 170   +2.61%
10  현대지에프홀딩스   14,960     상승 730   +5.13%
11   솔루스첨단소재   14,140   상승 3,130  +28.43%
12     삼성E&A   51,400   상승 2,100   +4.26%
13    한중엔시에스   72,500  상승 16,700  +29.93%
14     강원에너지   15,570   상승 1,010   +6.94%

In [61]:
df3

        종목명      현재가        전일대비      등락률
0     정원엔시스    1,297     상한가 299  +29.96%
1     씨아이에스   16,310   상한가 3,760  +29.96%
2   주성엔지니어링  118,900  상한가 27,400  +29.95%
3      킵스파마   10,850   상한가 2,500  +29.94%
4    한중엔시에스   72,500  상한가 16,700  +29.93%
5   에이에프더블류    1,424     상한가 328  +29.93%
6      애머릿지      508     상한가 117  +29.92%
7       씨이랩    8,950   상한가 2,060  +29.90%
8     리튬포어스      756     상한가 174  +29.90%
9       벨로크    2,370     상한가 545  +29.86%
10     국일제지      470     상한가 108  +29.83%
11  이브이첨단소재    2,050     상한가 471  +29.83%
12   중앙첨단소재    2,135     상한가 489  +29.71%
13    화인써키트    6,760    상승 1,500  +28.52%
14  솔루스첨단소재   14,140    상승 3,130  +28.43%

In [62]:
df4

          종목명      현재가        전일대비      등락률
0      한중엔시에스   72,500  상한가 16,700  +29.93%
1     솔루스첨단소재   14,140    상승 3,130  +28.43%
2        필에너지   19,800    상승 3,270  +19.78%
3       삼성SDI  644,000  상승 106,000  +19.70%
4          엔켐   48,950    상승 7,200  +17.25%
5       선익시스템  117,300   상승 16,400  +16.25%
6        이노테크   26,550    상승 3,700  +16.19%
7   HD현대마린솔루션  225,500   상승 29,800  +15.23%
8      대주전자재료  148,900   상승 18,900  +14.54%
9       에스엔시스   41,050    상승 5,200  +14.50%
10       삼성전기  770,000   상승 90,000  +13.24%
11  이수스페셜티케미컬  126,300   상승 14,700  +13.17%
12       GS건설   42,750    상승 4,700  +12.35%
13         태성   65,800    상승 6,600  +11.15%
14        프로텍   73,900    상승 7,000  +10.46%

In [63]:
df5

         종목명     현재가       전일대비      등락률
0     에프엔씨엔터   4,140    하락 -910  -18.02%
1        라닉스   2,700    하락 -505  -15.76%
2        우리로  10,350  하락 -1,750  -14.46%
3   와이바이오로직스  23,500  하락 -3,950  -14.39%
4   이노인스트루먼트   2,100    하락 -345  -14.11%
5     한국정보통신  13,680  하락 -2,230  -14.02%
6     지놈앤컴퍼니   6,070    하락 -950  -13.53%
7        광전자  11,190  하락 -1,710  -13.26%
8         레이   8,970  하락 -1,360  -13.17%
9     서울전자통신     578     하락 -86  -12.95%
10     엑스게이트  14,320  하락 -2,120  -12.90%
11       앱클론  48,850  하락 -6,950  -12.46%
12       셀리드   3,605    하락 -505  -12.29%
13    에스투더블유  18,980  하락 -2,620  -12.13%
14     케이씨에스  20,300  하락 -2,800  -12.12%

In [64]:
df6

         종목명      현재가        전일대비      등락률
0   와이바이오로직스   23,500   하락 -3,950  -14.39%
1     에스투더블유   19,000   하락 -2,600  -12.04%
2       보로노이  307,000  하락 -35,500  -10.36%
3      알지노믹스  186,200  하락 -15,800   -7.82%
4    에이프릴바이오   58,400   하락 -4,600   -7.30%
5    아이티센글로벌   46,850   하락 -3,650   -7.23%
6   온코닉테라퓨틱스   22,700   하락 -1,750   -7.16%
7       위메이드   24,100   하락 -1,850   -7.13%
8         미코   22,350   하락 -1,700   -7.07%
9    나이스정보통신   32,300   하락 -2,450   -7.05%
10     큐리오시스   57,700   하락 -4,100   -6.63%
11   DN오토모티브   38,850   하락 -2,750   -6.61%
12     인벤티지랩   60,300   하락 -4,100   -6.37%
13    로킷헬스케어   93,300   하락 -6,300   -6.33%
14      신풍제약   11,920     하락 -800   -6.29%

In [ ]:
# !pip install html5lib

In [86]:
import requests
import pandas as pd
from io import StringIO
dfs=[]

res = requests.get("https://finance.naver.com/")
res.encoding = 'euc-kr'

dfs = pd.read_html(StringIO(res.text))

In [92]:
dfs[1]

         종목명     현재가      전일대비      등락률
0     오리엔탈정공    8450    상승 430   +5.36%
1       삼성전자  219000  상승 4,500   +2.10%
2       GS건설   42950  상승 4,900  +12.88%
3       필에너지   20950  상승 4,420  +26.74%
4      애경케미칼   15530  상승 1,680  +12.13%
5      삼성중공업   30150  상승 1,600   +5.60%
6       성신양회   11780    상승 750   +6.80%
7   현대지에프홀딩스   15280  상승 1,050   +7.38%
8      STX엔진   50000  상승 3,800   +8.23%
9    두산에너빌리티  115700  상승 4,700   +4.23%
10   솔루스첨단소재   14010  상승 3,000  +27.25%
11    위메이드맥스    6880    상승 360   +5.52%
12     강원에너지   16500  상승 1,940  +13.32%
13     삼성E&A   51700  상승 2,400   +4.87%
14      한화엔진   60200  상승 5,900  +10.87%